# Generated by Django 2.2.10 on 2021-02-19 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_auto_20210218_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdataset',
            name='importedfilename',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spdataset',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spdataset',
            name='timestampcreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='spdataset',
            name='timestampmodified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
