import { getMappingLineData } from '../wbplanviewnavigator';
import { runTest } from './testmain';

export default function (): void {
  runTest(
    'WbPlanViewNavigator.getMappingLineData',
    [
      [
        [
          {
            baseTableName: 'collectionobject',
            mappingPath: ['determinations', '#1', 'taxon', '$Family', 'name'],
            showHiddenFields: false,
            iterate: true,
            generateFieldData: 'all',
          },
        ],
        JSON.stringify([
          {
            customSelectSubtype: 'simple',
            selectLabel: 'Collection Object',
            fieldsData: {
              altcatalognumber: {
                optionLabel: 'Alt Cat Number',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              catalognumber: {
                optionLabel: 'Catalog Number',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              catalogeddate: {
                optionLabel: 'Cataloged Date',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              guid: {
                optionLabel: 'GUID',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              projectnumber: {
                optionLabel: 'Project Number',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              accession: {
                optionLabel: 'Accession',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'accession',
              },
              cataloger: {
                optionLabel: 'Cataloger',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'agent',
              },
              collectionobjectattribute: {
                optionLabel: 'Col Obj Attribute',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'collectionobjectattribute',
              },
              collectingevent: {
                optionLabel: 'Collecting Event',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'collectingevent',
              },
              determinations: {
                optionLabel: 'Determinations',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: true,
                isRelationship: true,
                tableName: 'determination',
              },
              preparations: {
                optionLabel: 'Preparations',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'preparation',
              },
            },
            tableName: 'collectionobject',
            isOpen: true,
          },
          {
            customSelectSubtype: 'toMany',
            selectLabel: 'Determination',
            fieldsData: {
              '#1': {
                optionLabel: '#1',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: true,
                tableName: 'determination',
              },
              add: {
                optionLabel: 'Add',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'determination',
              },
            },
            tableName: 'determination',
            isOpen: true,
          },
          {
            customSelectSubtype: 'simple',
            selectLabel: 'Determination',
            fieldsData: {
              iscurrent: {
                optionLabel: 'Current',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              determineddate: {
                optionLabel: 'Determined Date',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              guid: {
                optionLabel: 'GUID',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              typestatusname: {
                optionLabel: 'Type Status',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              determiner: {
                optionLabel: 'Determiner',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'agent',
              },
              taxon: {
                optionLabel: 'Taxon',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: true,
                isRelationship: true,
                tableName: 'taxon',
              },
            },
            tableName: 'determination',
            isOpen: true,
          },
          {
            customSelectSubtype: 'tree',
            selectLabel: 'Taxon',
            fieldsData: {
              $Kingdom: {
                optionLabel: 'Kingdom',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Phylum: {
                optionLabel: 'Phylum',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subphylum: {
                optionLabel: 'Subphylum',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Superclass: {
                optionLabel: 'Superclass',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Class: {
                optionLabel: 'Class',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subclass: {
                optionLabel: 'Subclass',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Infraclass: {
                optionLabel: 'Infraclass',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Superorder: {
                optionLabel: 'Superorder',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Order: {
                optionLabel: 'Order',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Family: {
                optionLabel: 'Family',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: true,
                tableName: 'taxon',
              },
              $Subfamily: {
                optionLabel: 'Subfamily',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Genus: {
                optionLabel: 'Genus',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subgenus: {
                optionLabel: 'Subgenus',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Species: {
                optionLabel: 'Species',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subspecies: {
                optionLabel: 'Subspecies',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
            },
            tableName: 'taxon',
            isOpen: true,
          },
          {
            customSelectSubtype: 'simple',
            selectLabel: 'Taxon',
            fieldsData: {
              author: {
                optionLabel: 'Author',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              commonname: {
                optionLabel: 'Common Name',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              fullname: {
                optionLabel: 'Full Name',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              guid: {
                optionLabel: 'GUID',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              name: {
                optionLabel: 'Name',
                isEnabled: true,
                isRequired: true,
                isHidden: false,
                isDefault: true,
                isRelationship: false,
              },
              source: {
                optionLabel: 'Source',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
            },
            tableName: 'taxon',
            isOpen: true,
          },
        ]),
      ],
    ],
    (args: Parameters<typeof getMappingLineData>[0]) =>
      JSON.stringify(getMappingLineData(args))
  );
}
