import { getMappingLineData } from '../wbplanviewnavigator';
import { loadDataModel, runTest } from './testmain';

export default function (): void {
  loadDataModel();

  runTest(
    'WbPlanViewNavigator.getMappingLineData',
    [
      [
        [
          {
            baseTableName: 'collectionobject',
            mappingPath: ['determinations', '#1', 'taxon', '$Family', 'name'],
            generateLastRelationshipData: true,
            customSelectType: 'OPENED_LIST',
            showHiddenFields: false,
            iterate: true,
          },
        ],
        JSON.stringify([
          {
            customSelectType: 'OPENED_LIST',
            customSelectSubtype: 'simple',
            selectLabel: 'Collection Object',
            fieldsData: {
              altcatalognumber: {
                label: 'Alt Cat Number',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              catalognumber: {
                label: 'Catalog Number',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              catalogeddate: {
                label: 'Cataloged Date',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              guid: {
                label: 'GUID',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              projectnumber: {
                label: 'Project Number',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              accession: {
                label: 'Accession',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'accession',
              },
              cataloger: {
                label: 'Cataloger',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'agent',
              },
              collectionobjectattribute: {
                label: 'Col Obj Attribute',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'collectionobjectattribute',
              },
              collectingevent: {
                label: 'Collecting Event',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'collectingevent',
              },
              determinations: {
                label: 'Determinations',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: true,
                isRelationship: true,
                tableName: 'determination',
              },
              preparations: {
                label: 'Preparations',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'preparation',
              },
            },
            tableName: 'collectionobject',
            isOpen: true,
          },
          {
            customSelectType: 'OPENED_LIST',
            customSelectSubtype: 'toMany',
            selectLabel: 'Determination',
            fieldsData: {
              '#1': {
                label: '#1',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: true,
                tableName: 'determination',
              },
              add: {
                label: 'Add',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'determination',
              },
            },
            tableName: 'determination',
            isOpen: true,
          },
          {
            customSelectType: 'OPENED_LIST',
            customSelectSubtype: 'simple',
            selectLabel: 'Determination',
            fieldsData: {
              iscurrent: {
                label: 'Current',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              determineddate: {
                label: 'Determined Date',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              guid: {
                label: 'GUID',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              typestatusname: {
                label: 'Type Status',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              determiner: {
                label: 'Determiner',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: true,
                tableName: 'agent',
              },
              taxon: {
                label: 'Taxon',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: true,
                isRelationship: true,
                tableName: 'taxon',
              },
            },
            tableName: 'determination',
            isOpen: true,
          },
          {
            customSelectType: 'OPENED_LIST',
            customSelectSubtype: 'tree',
            selectLabel: 'Taxon',
            fieldsData: {
              $Kingdom: {
                label: 'Kingdom',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Phylum: {
                label: 'Phylum',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subphylum: {
                label: 'Subphylum',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Superclass: {
                label: 'Superclass',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Class: {
                label: 'Class',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subclass: {
                label: 'Subclass',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Infraclass: {
                label: 'Infraclass',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Superorder: {
                label: 'Superorder',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Order: {
                label: 'Order',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Family: {
                label: 'Family',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: true,
                tableName: 'taxon',
              },
              $Subfamily: {
                label: 'Subfamily',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Genus: {
                label: 'Genus',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subgenus: {
                label: 'Subgenus',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Species: {
                label: 'Species',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
              $Subspecies: {
                label: 'Subspecies',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isRelationship: true,
                isDefault: false,
                tableName: 'taxon',
              },
            },
            tableName: 'taxon',
            isOpen: true,
          },
          {
            customSelectType: 'OPENED_LIST',
            customSelectSubtype: 'simple',
            selectLabel: 'Taxon',
            fieldsData: {
              author: {
                label: 'Author',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              commonname: {
                label: 'Common Name',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              fullname: {
                label: 'Full Name',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              guid: {
                label: 'GUID',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
              name: {
                label: 'Name',
                isEnabled: true,
                isRequired: true,
                isHidden: false,
                isDefault: true,
                isRelationship: false,
              },
              source: {
                label: 'Source',
                isEnabled: true,
                isRequired: false,
                isHidden: false,
                isDefault: false,
                isRelationship: false,
              },
            },
            tableName: 'taxon',
            isOpen: true,
          },
        ]),
      ],
    ],
    (args: Parameters<typeof getMappingLineData>[0]) =>
      JSON.stringify(getMappingLineData(args))
  );
}
