import logging

logger = logging.getLogger(__name__)

def log_sqlalchemy_query(query):
    # Call this function to debug the raw SQL query generated by SQLAlchemy
    # TODO: verify theis import
    from django.conf import settings
    from sqlalchemy.dialects import mysql
    if not settings.DEBUG:
        return
    compiled_query = query.statement.compile(dialect=mysql.dialect())
    raw_sql = str(compiled_query).replace('\n', ' ') + ';'
    logger.debug('='.join(['' for _ in range(80)]))
    logger.debug("SQL: %s", raw_sql)
    logger.debug("Params: %s", compiled_query.params)
    logger.debug('='.join(['' for _ in range(80)]))
    # Run in the storred_queries.execute file, in the execute function, right before the return statement, line 546
    # from specifyweb.specify.utils import log_sqlalchemy_query; log_sqlalchemy_query(query)
