export const staticAppResources = {
  directories: [
    {
      id: 3,
      disciplineType: null,
      isPersonal: false,
      timestampCreated: '2012-08-10T16:12:08',
      timestampModified: '2012-08-10T16:12:08',
      userType: 'Global Prefs',
      version: 683,
      collection: null,
      createdByAgent: '/api/specify/agent/3/',
      discipline: null,
      modifiedByAgent: null,
      specifyUser: null,
      spPersistedAppResources: '/api/specify/spappresource/?spappresourcedir=3',
      spPersistedViewSets: '/api/specify/spviewsetobj/?spappresourcedir=3',
      resource_uri: '/api/specify/spappresourcedir/3/',
      _tableName: 'SpAppResourceDir',
      scope: 'global',
    },
    {
      id: 4,
      disciplineType: 'Ichthyology',
      isPersonal: true,
      timestampCreated: '2012-10-01T10:29:36',
      timestampModified: '2012-10-01T10:29:36',
      userType: 'manager',
      version: 3,
      collection: '/api/specify/collection/32768/',
      createdByAgent: '/api/specify/agent/3/',
      discipline: '/api/specify/discipline/3/',
      modifiedByAgent: null,
      specifyUser: '/api/specify/specifyuser/1/',
      spPersistedAppResources: '/api/specify/spappresource/?spappresourcedir=4',
      spPersistedViewSets: '/api/specify/spviewsetobj/?spappresourcedir=4',
      resource_uri: '/api/specify/spappresourcedir/4/',
      _tableName: 'SpAppResourceDir',
      scope: 'user',
    },
  ],
  disciplines: [],
  collections: [
    {
      id: 65_536,
      catalogNumFormatName: 'KUITeach',
      code: 'KUITeach',
      collectionName: 'KUFishTeaching',
      collectionType: null,
      dbContentVersion: null,
      description:
        'University of Kansas Biodiversity Institute Fish Teaching Collection',
      developmentStatus: null,
      estimatedSize: 0,
      guid: 'ab904d04-984b-431b-a28b-553af134e52b',
      institutionType: null,
      isEmbeddedCollectingEvent: false,
      isaNumber: null,
      kingdomCoverage: null,
      preservationMethodType: null,
      primaryFocus: null,
      primaryPurpose: null,
      regNumber: '1390919514.42',
      remarks: null,
      scope: null,
      timestampCreated: '2014-01-28T08:35:06',
      timestampModified: '2014-01-28T15:53:46',
      version: 4,
      webPortalURI: null,
      webSiteURI: null,
      adminContact: null,
      createdByAgent: '/api/specify/agent/2151/',
      discipline: '/api/specify/discipline/3/',
      institutionNetwork: null,
      modifiedByAgent: '/api/specify/agent/2151/',
      collectionObjectType: '/api/specify/collectionobjecttype/3/',
      contentContacts: '/api/specify/agent/?collcontentcontact=65536',
      technicalContacts: '/api/specify/agent/?colltechcontact=65536',
      leftSideRelTypes:
        '/api/specify/collectionreltype/?leftsidecollection=65536',
      rightSideRelTypes:
        '/api/specify/collectionreltype/?rightsidecollection=65536',
      pickLists: '/api/specify/picklist/?collection=65536',
      prepTypes: '/api/specify/preptype/?collection=65536',
      resource_uri: '/api/specify/collection/65536/',
      collectionObjects: '/api/specify/CollectionObject?collection=65536',
      userGroups: '/api/specify/SpPrincipal?scope=65536',
      _tableName: 'Collection',
    },
  ],
  users: [
    {
      id: 4,
      accumMinLoggedIn: null,
      email: 'larussell@vertnet.org',
      isLoggedIn: false,
      isLoggedInReport: false,
      loginCollectionName: null,
      loginDisciplineName: null,
      loginOutTime: '2014-03-20T12:49:34',
      name: 'Vertnet',
      timestampCreated: '2013-02-04T13:17:46',
      timestampModified: '2013-02-04T13:17:46',
      userType: 'Manager',
      version: 73,
      createdByAgent: '/api/specify/agent/2151/',
      modifiedByAgent: null,
      agents: '/api/specify/agent/?specifyuser=4',
      spAppResources: '/api/specify/spappresource/?specifyuser=4',
      spAppResourceDirs: '/api/specify/spappresourcedir/?specifyuser=4',
      spQuerys: '/api/specify/spquery/?specifyuser=4',
      taskSemaphores: '/api/specify/sptasksemaphore/?owner=4',
      workbenches: '/api/specify/workbench/?specifyuser=4',
      workbenchTemplates: '/api/specify/workbenchtemplate/?specifyuser=4',
      resource_uri: '/api/specify/specifyuser/4/',
      isAdmin: true,
      password: '',
      _tableName: 'SpecifyUser',
    },
    {
      id: 5,
      accumMinLoggedIn: null,
      email: 'c104m065@ku.edu',
      isLoggedIn: false,
      isLoggedInReport: false,
      loginCollectionName: null,
      loginDisciplineName: null,
      loginOutTime: '2014-04-12T12:49:47',
      name: 'cmeyer',
      timestampCreated: '2014-01-28T08:36:10',
      timestampModified: '2014-01-28T08:36:10',
      userType: 'Manager',
      version: 30,
      createdByAgent: '/api/specify/agent/2151/',
      modifiedByAgent: null,
      agents: '/api/specify/agent/?specifyuser=5',
      spAppResources: '/api/specify/spappresource/?specifyuser=5',
      spAppResourceDirs: '/api/specify/spappresourcedir/?specifyuser=5',
      spQuerys: '/api/specify/spquery/?specifyuser=5',
      taskSemaphores: '/api/specify/sptasksemaphore/?owner=5',
      workbenches: '/api/specify/workbench/?specifyuser=5',
      workbenchTemplates: '/api/specify/workbenchtemplate/?specifyuser=5',
      resource_uri: '/api/specify/specifyuser/5/',
      isAdmin: false,
      password: '',
      _tableName: 'SpecifyUser',
    },
  ],
  appResources: [
    {
      id: 3,
      allPermissionLevel: null,
      description: 'QueryExtraList',
      groupPermissionLevel: null,
      level: 0,
      metaData: null,
      mimeType: 'text/xml',
      name: 'QueryExtraList',
      ownerPermissionLevel: null,
      timestampCreated: '2012-08-10T16:12:05',
      version: 2,
      createdByAgent: '/api/specify/agent/3/',
      group: null,
      modifiedByAgent: '/api/specify/agent/3/',
      spAppResourceDir: '/api/specify/spappresourcedir/2/',
      specifyUser: '/api/specify/specifyuser/1/',
      spAppResourceDatas: '/api/specify/spappresourcedata/?spappresource=3',
      spReports: '/api/specify/spreport/?appresource=3',
      resource_uri: '/api/specify/spappresource/3/',
      _tableName: 'SpAppResource',
    },
    {
      id: 4,
      allPermissionLevel: null,
      description: null,
      groupPermissionLevel: null,
      level: 3,
      metaData: null,
      mimeType: null,
      name: 'preferences',
      ownerPermissionLevel: null,
      timestampCreated: '2012-08-10T16:12:08',
      version: 683,
      createdByAgent: '/api/specify/agent/3/',
      group: null,
      modifiedByAgent: null,
      spAppResourceDir: '/api/specify/spappresourcedir/3/',
      specifyUser: '/api/specify/specifyuser/1/',
      spAppResourceDatas: '/api/specify/spappresourcedata/?spappresource=4',
      spReports: '/api/specify/spreport/?appresource=4',
      resource_uri: '/api/specify/spappresource/4/',
      _tableName: 'SpAppResource',
    },
  ],
  viewSets: [
    {
      id: 5,
      description: null,
      fileName: null,
      level: 2,
      metaData: null,
      name: 'fish.views',
      timestampCreated: '2014-01-28T08:44:29',
      timestampModified: '2014-01-28T08:44:29',
      version: 6,
      createdByAgent: '/api/specify/agent/2151/',
      modifiedByAgent: null,
      spAppResourceDir: '/api/specify/spappresourcedir/16/',
      spAppResourceDatas: '/api/specify/spappresourcedata/?spviewsetobj=5',
      resource_uri: '/api/specify/spviewsetobj/5/',
      _tableName: 'SpViewSetObj',
    },
  ],
} as const;
