# Generated by Django 4.2.24 on 2026-01-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0044_alter_deletion_cascade'),
        ('businessrules', '0008_fix_global_default_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquenessrule',
            name='discipline',
            field=models.ForeignKey(blank=True, db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, to='specify.discipline'),
        ),
    ]
