version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/specifyweb/frontend/js_src"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      template: "{prefix}-{dependency}-{version}"
      max-length: 40

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      template: "{prefix}-{dependency}-{version}"
      max-length: 40

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      template: "{prefix}-{dependency}-{version}"
      max-length: 40

