.PHONY: all clean runserver

all: specifyweb/settings/build_version.py specifyweb/settings/secret_key.py
	$(MAKE) -C specifyweb/frontend/js_src

specifyweb/settings/build_version.py: .FORCE
	echo "VERSION = '`git describe`'" > $@

specifyweb/settings/secret_key.py:
	echo "# Make this unique, and don't share it with anybody.\n# This value was autogenerated." > $@
	printf "SECRET_KEY = '%b'\n" $$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 50) >> $@

clean:
	rm -f specifyweb/settings/build_version.py
	rm -f specifyweb/settings/secret_key.py
	$(MAKE) -C specifyweb/frontend/js_src clean

runserver:
	python specifyweb/manage.py runserver

.FORCE:
