# Generated by Django 3.2.15 on 2025-01-17 18:10

from django.db import migrations

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE spappresourcedata spard
            SET spard.data = REPLACE(spard.data, 'separator=""', 'separator="; "')
            WHERE spard.SpAppResourceID IN (
                SELECT spar.SpAppResourceID
                FROM spappresource spar
                WHERE spar.Name = 'DataObjFormatters'
            );
            """,
            reverse_sql='' # This should not be reversed
        )
    ]
