import os
import sys
import sqlalchemy
from sqlalchemy.orm import sessionmaker
sys.dont_write_bytecode = True

from django.utils.crypto import get_random_string

try:
    from . import local_specify_settings as specify_settings
except ImportError:
    from . import specify_settings

DEBUG = True
TEMPLATE_DEBUG = DEBUG

ADMINS = (
    # ('Your Name', 'your_email@example.com'),
)

MANAGERS = ADMINS

DATABASES = {
    'default': {
        'ENGINE': 'specifyweb.hibernateboolsbackend.backends.mysql',
        'NAME': specify_settings.DATABASE_NAME,
        'USER': specify_settings.MASTER_NAME,
        'PASSWORD': specify_settings.MASTER_PASSWORD,
        'HOST': '',
        'PORT': '',
     }
 }


TESTING_DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
#        'ENGINE': 'hibernateboolsbackend.backends.mysql',
        'NAME': "specifytest",
        'USER': "Master",
        'PASSWORD': "Master",
        'HOST': '127.0.0.1',
        'PORT': '3307',
    }
}

if 'test' in sys.argv:
    TESTING = True
    DATABASES = TESTING_DATABASES
    SA_DATABASE_URL = 'sqlite:///:memory:'
else:
    TESTING = False
    SA_DATABASE_URL = 'mysql://%s:%s@localhost/%s' % (specify_settings.MASTER_NAME,
                                                      specify_settings.MASTER_PASSWORD,
                                                      specify_settings.DATABASE_NAME)

SA_SESSION = sessionmaker(
    bind=sqlalchemy.create_engine(SA_DATABASE_URL))

SPECIFY_THICK_CLIENT = os.path.expanduser(specify_settings.THICK_CLIENT_LOCATION)

SPECIFY_CONFIG_DIR = os.path.join(SPECIFY_THICK_CLIENT, "config")

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# On Unix systems, a value of None will cause Django to use the same
# timezone as the operating system.
# If running in a Windows environment this must be set to the same as your
# system time zone.
TIME_ZONE = 'America/Chicago'

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en-us'

SITE_ID = 1

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale
USE_L10N = True

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/home/media/media.lawrence.com/media/"
MEDIA_ROOT = ''

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = ''

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
STATIC_ROOT = ''

# URL prefix for static files.
# Example: "http://media.lawrence.com/static/"
STATIC_URL = '/static/'

# URL prefix for admin static files -- CSS, JavaScript and images.
# Make sure to use a trailing slash.
# Examples: "http://foo.com/static/admin/", "/static/admin/".
ADMIN_MEDIA_PREFIX = '/static/admin/'

# Additional locations of static files
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    ('config', SPECIFY_CONFIG_DIR),
)

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

try:
    from .secret_key import SECRET_KEY
except ImportError:
    with open(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'secret_key.py'), 'w') as fp:
        fp.write("""
# Make this unique, and don't share it with anybody.
# This value was autogenerated.
SECRET_KEY = '%s'
""" % get_random_string(50, 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'))

    from .secret_key import SECRET_KEY

# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
#     'django.template.loaders.eggs.Loader',
)

MIDDLEWARE_CLASSES = (
#    'middleware.profilemiddleware.ProfileMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'specifyweb.context.middleware.ContextMiddleware'
)

ROOT_URLCONF = 'specifyweb.settings.urls'

TEMPLATE_DIRS = (
    # Put strings here, like "/home/html/django_templates" or "C:/www/django/templates".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)

INSTALLED_APPS = (
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'specifyweb.specify',
    'specifyweb.stored_queries',
    'specifyweb.businessrules',
    'specifyweb.express_search',
    'specifyweb.context',
    'specifyweb.attachment_gw',
    'specifyweb.frontend',
)

AUTH_USER_MODEL = 'specify.Specifyuser'

AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend', )

LOGIN_REDIRECT_URL = '/'

# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
            }
     },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'specify': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    }
}

try:
    from .local_settings import *
except ImportError:
    pass

WEB_ATTACHMENT_URL = specify_settings.WEB_ATTACHMENT_URL
WEB_ATTACHMENT_KEY = specify_settings.WEB_ATTACHMENT_KEY
WEB_ATTACHMENT_COLLECTION = specify_settings.WEB_ATTACHMENT_COLLECTION
WEB_ATTACHMENT_REQUIRES_KEY_FOR_GET = specify_settings.WEB_ATTACHMENT_REQUIRES_KEY_FOR_GET
