title: "[Feature Request] "
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in improving this project! Please fill out the following sections to help us understand your feature request better.
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      value: |
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: "A clear and concise description of what you want to happen."
      value: |
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
      value: |
        ...
      render: bash
  - type: input
    id: reported-by
    attributes:
      label: Reported By
      description: "Name of institution"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for your feedback! We appreciate your suggestions and will review them as soon as possible.
