import { requireContext } from '../../../tests/helpers';
import { parentTableRelationship } from '../parentTables';

requireContext();

test('Parent table relationships are calculated properly', () =>
  expect(parentTableRelationship()).toMatchInlineSnapshot(`
    {
      "AccessionAgent": "[relationship accession]",
      "AccessionAttachment": "[relationship accession]",
      "AccessionAuthorization": "[relationship accession]",
      "AccessionCitation": "[relationship accession]",
      "AgentAttachment": "[relationship agent]",
      "AgentGeography": "[relationship agent]",
      "AgentIdentifier": "[relationship agent]",
      "AgentSpecialty": "[relationship agent]",
      "AgentVariant": "[relationship agent]",
      "AttachmentMetadata": "[relationship attachment]",
      "AttachmentTag": "[relationship attachment]",
      "BorrowAgent": "[relationship borrow]",
      "BorrowAttachment": "[relationship borrow]",
      "BorrowMaterial": "[relationship borrow]",
      "BorrowReturnMaterial": "[relationship borrowMaterial]",
      "CollectingEventAttachment": "[relationship collectingEvent]",
      "CollectingEventAttr": "[relationship collectingEvent]",
      "CollectingEventAuthorization": "[relationship collectingEvent]",
      "CollectingTripAttachment": "[relationship collectingTrip]",
      "CollectingTripAuthorization": "[relationship collectingTrip]",
      "CollectionObjectAttachment": "[relationship collectionObject]",
      "CollectionObjectAttr": "[relationship collectionObject]",
      "CollectionObjectCitation": "[relationship collectionObject]",
      "CollectionObjectProperty": "[relationship collectionObject]",
      "Collector": "[relationship collectingEvent]",
      "CommonNameTxCitation": "[relationship commonNameTx]",
      "ConservDescriptionAttachment": "[relationship conservDescription]",
      "ConservEventAttachment": "[relationship conservEvent]",
      "DNASequenceAttachment": "[relationship dnaSequence]",
      "DNASequencingRunAttachment": "[relationship dnaSequencingRun]",
      "DNASequencingRunCitation": "[relationship sequencingRun]",
      "DeaccessionAgent": "[relationship deaccession]",
      "DeaccessionAttachment": "[relationship deaccession]",
      "DeterminationCitation": "[relationship determination]",
      "Determiner": "[relationship determination]",
      "DisposalAgent": "[relationship disposal]",
      "DisposalAttachment": "[relationship disposal]",
      "DisposalPreparation": "[relationship disposal]",
      "ExchangeInAttachment": "[relationship exchangeIn]",
      "ExchangeInPrep": "[relationship exchangeIn]",
      "ExchangeOutAttachment": "[relationship exchangeOut]",
      "ExchangeOutPrep": "[relationship exchangeOut]",
      "ExsiccataItem": "[relationship exsiccata]",
      "FieldNotebookAttachment": "[relationship fieldNotebook]",
      "FieldNotebookPage": "[relationship pageSet]",
      "FieldNotebookPageAttachment": "[relationship fieldNotebookPage]",
      "FieldNotebookPageSet": "[relationship fieldNotebook]",
      "FieldNotebookPageSetAttachment": "[relationship fieldNotebookPageSet]",
      "GeographyTreeDefItem": "[relationship treeDef]",
      "GeologicTimePeriodTreeDefItem": "[relationship treeDef]",
      "GiftAgent": "[relationship gift]",
      "GiftAttachment": "[relationship gift]",
      "GiftPreparation": "[relationship gift]",
      "LatLonPolygon": "[relationship locality]",
      "LatLonPolygonPnt": "[relationship latLonPolygon]",
      "LithoStratTreeDefItem": "[relationship treeDef]",
      "LoanAgent": "[relationship loan]",
      "LoanAttachment": "[relationship loan]",
      "LoanPreparation": "[relationship loan]",
      "LoanReturnPreparation": "[relationship loanPreparation]",
      "LocalityAttachment": "[relationship locality]",
      "LocalityCitation": "[relationship locality]",
      "LocalityDetail": "[relationship locality]",
      "PcrPerson": "[relationship dnaSequence]",
      "PermitAttachment": "[relationship permit]",
      "PickListItem": "[relationship pickList]",
      "PreparationAttachment": "[relationship preparation]",
      "PreparationAttr": "[relationship preparation]",
      "PreparationProperty": "[relationship preparation]",
      "RecordSetItem": "[relationship recordSet]",
      "ReferenceWorkAttachment": "[relationship referenceWork]",
      "RepositoryAgreementAttachment": "[relationship repositoryAgreement]",
      "SpAppResourceData": "[relationship spAppResource]",
      "SpAuditLogField": "[relationship spAuditLog]",
      "SpExportSchemaItem": "[relationship spExportSchema]",
      "SpExportSchemaItemMapping": "[relationship exportSchemaItem]",
      "SpLocaleContainerItem": "[relationship container]",
      "SpQueryField": "[relationship query]",
      "StorageAttachment": "[relationship storage]",
      "StorageTreeDefItem": "[relationship treeDef]",
      "TaxonAttachment": "[relationship taxon]",
      "TaxonCitation": "[relationship taxon]",
      "TaxonTreeDefItem": "[relationship treeDef]",
      "TreatmentEventAttachment": "[relationship treatmentEvent]",
      "WorkbenchRow": "[relationship workbench]",
      "WorkbenchRowImage": "[relationship workbenchRow]",
    }
  `));
