# Generated by Django 3.2.15 on 2024-12-27 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue5451Test',
            fields=[
                ('id', models.AutoField(db_column='issue5451testID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('timestampmodified', models.DateTimeField(blank=True, db_column='TimestampModified', default=django.utils.timezone.now, null=True)),
                ('timestampcreated', models.DateTimeField(db_column='TimestampCreated', default=django.utils.timezone.now)),
                ('collectionobject', models.OneToOneField(db_column='CollectionObjectID', on_delete=django.db.models.deletion.CASCADE, related_name='issue5451', to='specify.collectionobject')),
            ],
            options={
                'db_table': 'issue5451test',
            },
        ),
    ]
