/**
 * Localization strings used in Batch Identify tool
 *
 * @module
 */

import { createDictionary } from './utils';

export const batchIdentifyText = createDictionary({
  batchIdentify: {
    'en-us': 'Batch Identify',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  instructions: {
    'en-us':
      'Enter catalog numbers using any non-numeric delimiters (commas, spaces, text prefixes, etc.). Use a dash to declare numeric ranges like 0001 - 0150.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  catalogNumbersNotFound: {
    'en-us': 'Catalog Numbers Not Found',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  identify: {
    'en-us': 'Identify',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  successMessage: {
    'en-us': 'All records were identified to the specified taxon.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  updatedRecordSet: {
    'en-us': 'Batch Identify Updated Records',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  noCatalogNumbersParsed: {
    'en-us': 'Enter at least one numeric catalog number.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  validatingCatalogNumbers: {
    'en-us': 'Validating catalog numbers...',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  placeholder: {
    'en-us': '0001 0002 0003 - 0150',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  previewQueryName: {
    'en-us': 'Batch Identify Preview',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  unknownTaxonTree: {
    'en-us': 'Unknown Taxon Tree',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionObjectTypes: {
    'en-us': 'Collection Object Types',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  invalidRecordSetTitle: {
    'en-us': 'Mixed Record Set',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  invalidRecordSetMessage: {
    'en-us':
      'The selected record set contains collection objects from more than one taxon tree.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  invalidRecordSetInstructions: {
    'en-us':
      'Choose a different record set, or edit the query used to create this record set so all collection objects use the same taxon tree.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    nb: '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
} as const);
