/**
 * Localization strings used for displaying Attachments
 *
 * @module
 */

import { createDictionary } from "./utils";

export const batchEditText = createDictionary({
  batchEdit: {
    "en-us": "Batch Edit",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  batchEditPrefs: {
    "en-us": "Batch Edit Preferences",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  numberOfRecords: {
    "en-us": "Number of records selected from the query",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  removeField: {
    "en-us":
      "Field not supported for batch edit. Either remove the field, or make it hidden.",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  addTreeRank: {
    "en-us":
      "The following ranks will be added to the query to enable batch editing",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  pickTreesToFilter: {
    "en-us":
      "The selected rank(s) are found in multiple trees. Pick tree(s) to batch edit with",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  datasetName: {
    "en-us": "{queryName:string} {datePart:string}",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  errorInQuery: {
    "en-us": "Following errors were found in the query",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  missingRanksInQuery: {
    "en-us": "Query requires additional ranks for batch editing",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  createUpdateDataSetInstructions: {
    "en-us": "Use the query builder to make a new batch edit dataset",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  showRollback: {
    "en-us": "Show rollback button",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  showRollbackDescription: {
    "en-us":
      "Rollback in Batch Edit is an experimental feature. This preference will hide the button",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  commit: {
    "en-us": "Commit",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  startCommitDescription: {
    "en-us":
      "Commiting the Data Set will update, add, and delete the data from the spreadsheet to the  Specify database.",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  startRevertDescription: {
    "en-us":
      "Rolling back the dataset will re-update the values, delete created records, and create new records",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  commitSuccessfulDescription: {
    "en-us":
      'Click on the "Results" button to see the number of records affected in each database table',
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  dateSetRevertDescription: {
    "en-us":
      "This rolled-back Data Set is saved, however, it cannot be edited. Please re-run the query",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  committing: {
    "en-us": "Committing",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  beStatusCommit: {
    "en-us": "Data Set Commit Status",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  startCommit: {
    "en-us": "Begin Data Set Commit?",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  commitErrors: {
    "en-us": "Commit Failed due to Error Cells",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  commitErrorsDescription: {
    "en-us": "The Commit failed due to one or more cell value errors.",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  commitCancelled: {
    "en-us": "Commit Cancelled",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  commitCancelledDescription: {
    "en-us": "Commit Cancelled Description",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  commitSuccessful: {
    "en-us": "Commit Completed with No Errors",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  batchEditRecordSetName: {
    "en-us": 'BE commit of "{dataSet:string}"',
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  deferForMatch: {
    "en-us": "Use only visible fields for match",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  deferForMatchDescription: {
    "en-us":
      "If true, invisible database fields will not be used for matching. Default value is {default:boolean}",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  deferForNullCheck: {
    "en-us": "Use only visible fields for empty record check",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  deferForNullCheckDescription: {
    "en-us":
      "If true, invisible database fields will not be used for determining whether the record is empty or not. Default value is {default: boolean}",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  batchEditDisabled: {
    "en-us":
      "Batch Edit is disabled for system tables and scoping hierarchy tables",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  cannotEditAfterRollback: {
    "en-us":
      "(Batch Edit datasets cannot be edited after rollback - Read Only)",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  enableRelationships: {
    "en-us": "Enable relationships",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
  enableRelationshipsDescription: {
    "en-us":
      "Allows batch editing relationships of the base table. Rollback is disabled when relationships are enabled",
    "de-ch": "",
    "es-es": "",
    "fr-fr": "",
    "pt-br": "",
    "ru-ru": "",
    "uk-ua": "",
  },
} as const);
