/**
 * Localization strings used by Record Merging tool
 *
 * @module
 */

import { createDictionary } from './utils';

// Refer to "Guidelines for Programmers" in ./README.md before editing this file

export const mergingText = createDictionary({
  recordMerging: {
    'en-us': 'Record Merging',
    'ru-ru': 'Объединение записей',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  mergeRecords: {
    'en-us': 'Merge Records',
    'ru-ru': 'Объединить записи',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  mergedRecord: {
    'en-us': 'Merged Record',
    'ru-ru': 'Объединенная запись',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  showConflictingFieldsOnly: {
    'en-us': 'Show conflicting fields only',
    'ru-ru': 'Показать только конфликтующие поля',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  preview: {
    'en-us': 'Preview',
    'ru-ru': 'Открыть',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  newMergedRecord: {
    'en-us': 'New merged record',
    'ru-ru': 'Новая объединенная запись',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  duplicateRecord: {
    'en-us': 'Preview {index:number|formatted}',
    'ru-ru': 'Предпросмотр {index:number|formatted}',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  nRecords: {
    'en-us': '{count:number|formatted} records',
    'ru-ru': '{count:number|formatted} записей',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  subViewControls: {
    'en-us': 'Sub-view Controls',
    'ru-ru': 'Под-вид Контролы',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  mergeFields: {
    comment: 'Example: "Merge Addresses"',
    'en-us': 'Merge {field:string}',
    'ru-ru': 'Объединить {field:string}',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'uk-ua': '',
  },
  autoPopulate: {
    'en-us': 'Auto-populate',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  dismissFromMerging: {
    'en-us': 'Dismiss from merging',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  agentContainsGroupDescription: {
    'en-us': 'Agents contain group members',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  recordNotBeMergedReason: {
    'en-us': 'The following records cannot be merged. Reason:',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  someCannotBeMerged: {
    'en-us': 'Some records cannot be merged',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergeOthers: {
    'en-us': 'Merge others',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  warningMergeText: {
    'en-us': `
      Before proceeding, please note that the following action may interrupt
      other users. This action may cause delays or temporary unavailability of
      certain features for Specify users. Please consider the impact on their
      experience. This merge cannot be undone
    `,
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergeFailed: {
    'en-us': 'Merge Failed',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergeSucceeded: {
    'en-us': 'Merge Succeeded',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  merging: {
    'en-us': 'Merging',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergingHasStarted: {
    'en-us': 'The merge process has started.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergingHasSucceeded: {
    'en-us': 'The merge process has succeeded.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergingHasFailed: {
    'en-us': 'The merge process has failed.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergingHasBeenCanceled: {
    'en-us': 'The merge process has been canceled.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  retryMerge: {
    'en-us': 'Retry merge.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  mergingWentWrong: {
    'en-us': 'Something went wrong during the merging process.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  linkedRecords: {
    'en-us': 'Linked Records',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'ru-ru': '',
    'uk-ua': '',
  },
} as const);
