/**
 * Localization strings for the Specify Configuration Setup.
 *
 * @module
 */

import { createDictionary } from './utils';

// Refer to "Guidelines for Programmers" in ./README.md before editing this file

export const setupToolText = createDictionary({
  guidedSetup: {
    'en-us': 'Guided Setup',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  setupProgress: {
    'en-us': 'Progress:',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  overview: {
    'en-us': 'Overview',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  settingUp: {
    'en-us': 'Setting up the database...',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  creating: {
    'en-us': 'Creating the',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  setupError: {
    'en-us': 'An error occurred during the last setup attempt.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institution: {
    'en-us': 'Institution',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionDescription: {
    'en-us': 'Enter Institution Information.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionName: {
    'en-us': 'Name',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionNameDescription: {
    'en-us':
      'The full, official name of the institution (e.g., "University of Kansas Biodiversity Institute").',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionCode: {
    'en-us': 'Code',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionCodeDescription: {
    'en-us':
      'A short, unique code or acronym for the institution (e.g., "KUBI").',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionAddress: {
    'en-us': 'Address',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionAddressDescription: {
    'en-us': 'The address of the institution. Optional.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionIsAccessionGlobal: {
    'en-us': 'Define Accession Globally',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  institutionIsAccessionGlobalDescription: {
    'en-us':
      'Global scope allows you to share Accessions between all divisions. Divisional scope ensures Accessions are specific to each division.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  address: {
    'en-us': 'Address',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressDescription: {
    'en-us': 'The street address of the institution.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressCity: {
    'en-us': 'City',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressCityDescription: {
    'en-us': 'The city where the institution is located.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressState: {
    'en-us': 'Province/State',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressStateDescription: {
    'en-us': 'The state or province.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressCountry: {
    'en-us': 'Country',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressCountryDescription: {
    'en-us': 'The country.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressPostalCode: {
    'en-us': 'Zip/Postal Code',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressPostalCodeDescription: {
    'en-us': 'The postal code.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressPhone1: {
    'en-us': 'Phone',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addressPhone1Description: {
    'en-us': 'A contact phone number.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  treeRanks: {
    'en-us': 'Tree Ranks',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  rank: {
    'en-us': 'Rank',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  fullNameDirection: {
    'en-us': 'Full Name Direction',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  preloadTree: {
    'en-us': 'Populate tree with default records',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  preloadTreeDescription: {
    'en-us': 'Download default records for this tree.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  treeToPreload: {
    'en-us': 'Tree to download:',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  selectATree: {
    'en-us': 'Select a tree',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  include: {
    'en-us': 'Include',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  includeDescription: {
    'en-us': 'Include places the Level in the tree definition.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  enforced: {
    'en-us': 'Enforced',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  enforcedDescription: {
    'en-us':
      'Is Enforced ensures that the level can not be skipped when adding nodes lower down the tree.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  inFullName: {
    'en-us': 'In Full Name',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  inFullNameDescription: {
    'en-us':
      'Is in Full Name includes the level when building a full name expression, which can be queried and used in reports.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  fullNameSeparator: {
    'en-us': 'Separator',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  fullNameSeparatorDescription: {
    'en-us':
      'Separator refers to the character that separates the levels when displaying the full name.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  storageTree: {
    'en-us': 'Storage Tree',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  geographyTree: {
    'en-us': 'Geography Tree',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  taxonTree: {
    'en-us': 'Taxon Tree',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  division: {
    'en-us': 'Division',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  divisionName: {
    'en-us': 'Name',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  divisionAbbrev: {
    'en-us': 'Abbreviation',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  discipline: {
    'en-us': 'Discipline',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  disciplineName: {
    'en-us': 'Name',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  disciplineType: {
    'en-us': 'Type',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionName: {
    'en-us': 'Collection Name',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionCode: {
    'en-us': 'Code',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionCatalogNumFormatName: {
    'en-us': 'Catalog Number Format',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUser: {
    'en-us': 'Specify User',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserName: {
    'en-us': 'Username',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserNameDescription: {
    'en-us': 'The username for the primary administrator account.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserPassword: {
    'en-us': 'Password',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserPasswordDescription: {
    'en-us': 'The password for the account.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserConfirmPassword: {
    'en-us': 'Confirm Password',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserConfirmPasswordDescription: {
    'en-us': 'Must match the password entered above.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserFirstName: {
    'en-us': 'First Name',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserFirstNameDescription: {
    'en-us':
      'The first name of the agent associated with the account. Optional.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserLastName: {
    'en-us': 'Last Name',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  specifyUserLastNameDescription: {
    'en-us': 'The last name of the agent associated with the account.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addNewGeographyTree: {
    'en-us': 'Add new Geography Tree',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addNewTaxonTree: {
    'en-us': 'Add new Taxon Tree',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  hierarchyStructureTitle: {
    'en-us': 'View the Institutional Hierarchy',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  hierarchyStructureHint: {
    'en-us': 'Click any block to open its edit form.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  hierarchySwitchToHorizontal: {
    'en-us': 'Switch to horizontal',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  hierarchySwitchToVertical: {
    'en-us': 'Switch to vertical',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  hierarchyAddNew: {
    'en-us': 'Add',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  hierarchyDiagram: {
    'en-us': 'Institutional Hierarchy',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  emptyTaxonTree: {
    'en-us': 'An empty taxon tree will be created',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionCreationStarted: {
    'en-us':
      'The newly created collection is being set up. It may take some time for the collection to become available.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'hr-hr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
} as const);
