/**
 * Localization strings used in the Statistics Page
 *
 * @module
 */

import { createDictionary } from './utils';

// Refer to "Guidelines for Programmers" in ./README.md before editing this file

/* eslint-disable @typescript-eslint/naming-convention */
export const statsText = createDictionary({
  holdings: {
    'en-us': 'Holdings',
    'ru-ru': 'Холдинги',
    'es-es': 'Mantenimientos',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  collectionObjects: {
    'en-us': 'Collection Objects',
    'ru-ru': 'Объекты коллекции',
    'es-es': 'Objetos de la Colección',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  typeSpecimens: {
    'en-us': 'Type Specimens',
    'es-es': 'Especímenes Tipo',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  curation: {
    'en-us': 'Curation',
    'es-es': 'Curación',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  loans: {
    'en-us': 'Loans',
    'ru-ru': 'Заемы',
    'es-es': 'Préstamos',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  itemsOnLoans: {
    'en-us': 'Items on Loan',
    'ru-ru': 'Предметы в Займы',
    'es-es': 'Artículos en Préstamo',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  openLoansStat: {
    'en-us': 'Open Loans',
    'ru-ru': 'Открытые Займы',
    'es-es': 'Préstamos Abiertos',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  overdueLoans: {
    'en-us': 'Overdue Loans',
    'ru-ru': 'Просроченные Займы',
    'es-es': 'Préstamos Atrasados',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  localityGeography: {
    'en-us': 'Locality / Geography',
    'ru-ru': 'Местность / География',
    'es-es': 'Localidad / Geografía',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  localities: {
    'en-us': 'Localities',
    'ru-ru': 'Местности',
    'es-es': 'Localidades',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  geographyEntries: {
    'en-us': 'Geography Entries',
    'ru-ru': 'География Записи',
    'es-es': 'Entradas de Geografía',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  countries: {
    'en-us': 'Countries',
    'ru-ru': 'Страны',
    'es-es': 'Países',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  georeferencedLocalities: {
    'en-us': 'Georeferenced Localities',
    'ru-ru': 'Места с географической привязкой',
    'es-es': 'Localidades Georreferenciadas',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  digitization: {
    'en-us': 'Digitization',
    'es-es': 'Digitalización',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  digitizedLastSevenDays: {
    'en-us': 'Digitized Last 7 Days',
    'es-es': 'Digitalizado Últimos 7 Días',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  digitizedLastMonth: {
    'en-us': 'Digitized Last Month',
    'es-es': 'Digitalizado Último Mes',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  digitizedLastYear: {
    'en-us': 'Digitized Last Year',
    'es-es': 'Digitalizado Último Año',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  chooseStatistics: {
    'en-us': 'Choose Statistics',
    'ru-ru': 'Выберите статистику',
    'es-es': 'Seleccionar Estadísticas',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  selectFromQueries: {
    'en-us': 'Select From Queries',
    'es-es': 'Seleccionar de Consultas',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  selectFromAvailableDefault: {
    'en-us': 'Select From Available Default Statistics',
    'es-es': 'Seleccionar de Estadísticas Predeterminadas Disponibles',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collection: {
    'en-us': 'Collection',
    'ru-ru': 'Коллекция',
    'es-es': 'Colección',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  personal: {
    'en-us': 'Personal',
    'ru-ru': 'Личный',
    'es-es': 'Personal',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  private: {
    'en-us': 'Private',
    'es-es': 'Privado',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionObjectsCataloged: {
    'en-us': 'Collection Objects Cataloged',
    'ru-ru': 'Объекты коллекции каталогизированы',
    'es-es': 'Objetos de la Colección Catalogados',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  collectionObjectsDetermined: {
    'en-us': 'Collection Objects Determined',
    'ru-ru': 'Объекты коллекции определены',
    'es-es': 'Objetos de la Colección Determinados',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  lastRefreshed: {
    'en-us': 'Last refreshed',
    'es-es': 'Última Actualización',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  categoryName: {
    'en-us': 'Category Name',
    'ru-ru': 'Название категории',
    'es-es': 'Nombre de la Categoría',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  itemName: {
    'en-us': 'Item Name',
    'ru-ru': 'Название предмета',
    'es-es': 'Nombre del Item',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  itemValue: {
    'en-us': 'Item Value',
    'ru-ru': 'Стоимость товара',
    'es-es': 'Valor del Ítem',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  downloadAsTSV: {
    'en-us': 'Download as TSV',
    'ru-ru': 'Скачать как TSV',
    'es-es': 'Descargar como TSV',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  shared: {
    'en-us': 'Shared',
    'ru-ru': 'Общий',
    'es-es': 'Compartido',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'uk-ua': '',
  },
  statistics: {
    'en-us': 'Statistics',
    'es-es': 'Estadísticas',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  deleteCategory: {
    'en-us': 'Delete Category',
    'es-es': 'Eliminar Categoría',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  editPage: {
    'en-us': 'Edit Page',
    'es-es': 'Editar Página',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addPage: {
    'en-us': 'Add Page',
    'es-es': 'Agregar Página',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  addACategory: {
    'en-us': 'Add a Category',
    'es-es': 'Agregar una Categoría',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  refresh: {
    'en-us': 'Refresh',
    'es-es': 'Actualizar',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionObjectsWithImages: {
    'en-us': 'Collection Objects with images',
    'es-es': 'Objetos de la Colección con imágenes',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  collectionObjectsWithAttachments: {
    'en-us': 'Collection Objects with attachments',
    'es-es': 'Objetos de la Colección con adjuntos',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  error: {
    'en-us': 'Error',
    'es-es': 'Error',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  taxonRepresented: {
    'en-us': 'Taxa Represented',
    'es-es': 'Taxones Representados',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  geographiesRepresented: {
    'en-us': 'Geographies Represented',
    'es-es': 'Geografías Representadas',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  percentGeoReferenced: {
    'en-us': 'Percent Georeferenced',
    'es-es': 'Porcentaje Georreferenciado',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  percentImaged: {
    'en-us': 'Percent Imaged',
    'es-es': 'Porcentaje Capturado',
    'de-ch': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  deleteWarning: {
    'en-us': 'Are you sure you want to delete the category?',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  categoryToDelete: {
    'en-us': 'This will permanently delete the following category',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  layoutPreference: {
    'en-us': 'Defines the layout of the statistics page',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  showPreparationsTotal: {
    'en-us': 'Show {preparationTableName:string} Totals',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  showPreparationsTotalDescription: {
    'en-us':
      'If enabled, the default {preparationTableName:string} statistics panel will include a total count for each {lowerPreparationTableName:string} of a particular {prepTypeTableName:string} alongside the overall total. This is useful for lot-based collections.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  autoRefreshRate: {
    'en-us': 'Auto-Refresh Rate (Hours)',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
  autoRefreshRateDescription: {
    'en-us':
      'The time interval, in hours, at which the statistics page will automatically refresh its data. Default is 24.',
    'de-ch': '',
    'es-es': '',
    'fr-fr': '',
    'pt-br': '',
    'ru-ru': '',
    'uk-ua': '',
  },
} as const);
/* eslint-enable @typescript-eslint/naming-convention */
