/**
 * Localization strings used in the Tree Viewer
 *
 * @module
 */

import { createDictionary } from './utils';

// Refer to "Guidelines for Programmers" in ./README.md before editing this file

export const treeText = createDictionary({
  trees: {
    'en-us': 'Trees',
    'ru-ru': 'Деревья',
    'es-es': 'Árboles',
    'fr-fr': 'Arbres',
    'uk-ua': 'дерева',
    'de-ch': 'Hierarchien',
    'pt-br': 'Árvores',
    'hr-hr': '',
  },
  badStructure: {
    'en-us': 'Bad tree structure.',
    'ru-ru': 'Неправильная структура дерева.',
    'es-es': 'Estructura de árbol incorrecta.',
    'fr-fr': 'Mauvaise arborescence.',
    'uk-ua': 'Погана структура дерева.',
    'de-ch': 'Fehlerhafte Baumstruktur.',
    'pt-br': 'Má estrutura da árvore.',
    'hr-hr': '',
  },
  move: {
    'en-us': 'Move',
    'ru-ru': 'Двигаться',
    'es-es': 'Mover',
    'fr-fr': 'Déplacer',
    'uk-ua': 'рухатися',
    'de-ch': 'Verschieben',
    'pt-br': 'Mover',
    'hr-hr': '',
  },
  merge: {
    'en-us': 'Merge',
    'ru-ru': 'Слияние',
    'es-es': 'Unir',
    'fr-fr': 'Fusionner',
    'uk-ua': 'Об’єднати',
    'de-ch': 'Zusammenführen',
    'pt-br': 'Fusão',
    'hr-hr': '',
  },
  undoSynonymy: {
    'en-us': 'Undo Synonymy',
    'ru-ru': 'Отменить синонимию',
    'es-es': 'Deshacer sinonimia',
    'fr-fr': 'Annuler la synonymie',
    'uk-ua': 'Скасувати синонімію',
    'de-ch': 'Synonymie rückgängig machen',
    'pt-br': 'Desfazer Sinônimo',
    'hr-hr': '',
  },
  synonymize: {
    'en-us': 'Synonymize',
    'ru-ru': 'Подбирать синонимы',
    'es-es': 'Sinonimizar',
    'fr-fr': 'Synonymiser',
    'uk-ua': 'Синонімізувати',
    'de-ch': 'Synonymisieren',
    'pt-br': 'Sinônimos',
    'hr-hr': '',
  },
  actionFailed: {
    'en-us': 'Operation failed',
    'ru-ru': 'Операция провалилась',
    'es-es': 'Operación fallida',
    'fr-fr': "L'opération a échoué",
    'uk-ua': 'Операція не вдалася',
    'de-ch': 'Vorgang fehlgeschlagen',
    'pt-br': 'Operação falhou',
    'hr-hr': '',
  },
  actionFailedDescription: {
    'en-us':
      'The operation could not be completed due to the following errors:',
    'ru-ru': 'Операция не может быть завершена из-за следующих ошибок:',
    'es-es':
      'La operación no se pudo completar debido a los siguientes errores:',
    'fr-fr':
      "L'opération n'a pas pu être terminée en raison des erreurs suivantes :",
    'de-ch':
      'Der Vorgang konnte aufgrund der folgenden Fehler nicht ausgeführt werden:',
    'uk-ua': 'Операцію не вдалося завершити через такі помилки:',
    'pt-br': 'A operação não pôde ser concluída devido aos seguintes erros:',
    'hr-hr': '',
  },
  moveNode: {
    'en-us': 'Move node',
    'ru-ru': 'Переместить узел',
    'es-es': 'Mover nodo',
    'fr-fr': 'Déplacer le nœud',
    'uk-ua': 'Перемістити вузол',
    'de-ch': 'Knoten verschieben',
    'pt-br': 'Mover nó',
    'hr-hr': '',
  },
  addChild: {
    'en-us': 'Add Child',
    'ru-ru': 'Добавить ребенка',
    'es-es': 'Agregar hijo',
    'fr-fr': 'Ajouter un enfant',
    'uk-ua': 'Додати дитину',
    'de-ch': 'Kind hinzuzufügen',
    'pt-br': 'Adicionar filho',
    'hr-hr': '',
  },
  moveNodeHere: {
    'en-us': 'Move "{nodeName:string}" here',
    'ru-ru': 'Переместите "{nodeName:string}" сюда',
    'es-es': 'Mover "{nodeName:string}" aquí',
    'fr-fr': 'Déplacer « {nodeName:string} » ici',
    'uk-ua': 'Перемістіть сюди "{nodeName:string}"',
    'de-ch': 'Verschiebe "{nodeName:string}" hierhin',
    'pt-br': 'Mova "{nodeName:string}" para cá',
    'hr-hr': '',
  },
  moveNodePreparationsHere: {
    'en-us': 'Move all "{nodeName:string}" preparations here',
    'de-ch':
      'Verschieben Sie alle Vorbereitungen mit dem Präfix "{nodeName:string}" hierher.',
    'es-es': 'Mover todas las preparaciones "{nodeName:string}" aquí',
    'fr-fr': 'Déplacer toutes les préparations « {nodeName:string} » ici',
    'ru-ru': 'Переместите сюда все приготовления "{nodeName:string}".',
    'uk-ua': 'Перемістіть сюди всі препарати "{nodeName:string}"',
    'pt-br': 'Mova todos os preparativos "{nodeName:string}" para cá.',
    'hr-hr': '',
  },
  nodeMoveMessage: {
    'en-us':
      'The {treeName:string} node "{nodeName:string}" will be placed, along with all of its descendants, under the new parent "{parentName:string}".',
    'ru-ru':
      'Узел {treeName:string} "{nodeName:string}" будет помещен вместе со всеми его потомками под новый родительский узел "{parentName:string}".',
    'es-es':
      'El nodo {treeName:string} "{nodeName:string}" se colocará, junto con todos sus descendientes, bajo el nuevo padre "{parentName:string}".',
    'fr-fr':
      'Le nœud {treeName:string} « {nodeName:string} » sera placé, avec tous ses descendants, sous le nouveau parent « {parentName:string} ».',
    'uk-ua':
      'Вузол {treeName:string} "{nodeName:string}" буде розміщено разом із усіма його нащадками під новим батьківським вузлом "{parentName:string}".',
    'de-ch':
      'Der {treeName:string} Knoten "{nodeName:string}" wird zusammen mit allen seinen Unterknoten unter den neuen übergeordneten Knoten "{parentName:string}" platziert.',
    'pt-br':
      'O nó {treeName:string} "{nodeName:string}" será colocado, juntamente com todos os seus descendentes, sob o novo pai "{parentName:string}".',
    'hr-hr': '',
  },
  nodeBulkMoveMessage: {
    'en-us':
      'The {treeName:string} node "{nodeName:string}" preparations will be placed under the new location "{parentName:string}".',
    'de-ch':
      'Die Vorbereitungen für den Knoten {treeName:string} "{nodeName:string}" werden unter dem neuen Standort "{parentName:string}" zusammengefasst.',
    'es-es':
      'Las preparaciones del nodo {treeName:string} "{nodeName:string}" se colocarán en la nueva ubicación "{parentName:string}".',
    'fr-fr':
      'Les préparatifs du nœud {treeName:string} « {nodeName:string} » seront placés sous le nouvel emplacement « {parentName:string} ».',
    'ru-ru':
      'Подготовка узла {treeName:string} "{nodeName:string}" будет размещена в новом месте "{parentName:string}".',
    'uk-ua':
      'Підготовка вузла {treeName:string} "{nodeName:string}" буде розміщена в новому місці розташування "{parentName:string}".',
    'pt-br':
      'Os preparativos do nó {treeName:string} "{nodeName:string}" serão colocados no novo local "{parentName:string}".',
    'hr-hr': '',
  },
  cantMoveHere: {
    'en-us': "Can't move this tree node here",
    'ru-ru': 'Невозможно переместить этот узел дерева сюда.',
    'es-es': 'No se puede mover este nodo del árbol aquí',
    'fr-fr': "Impossible de déplacer ce nœud d'arbre ici",
    'uk-ua': 'Неможливо перемістити цей вузол дерева сюди',
    'de-ch': 'Dieser Knoten kann nicht hierhin verschoben werden',
    'pt-br': 'Não é possível mover este nó da árvore para cá.',
    'hr-hr': '',
  },
  cantMergeHere: {
    'en-us': "Can't merge this tree node here",
    'ru-ru': 'Невозможно объединить этот узел дерева.',
    'es-es': 'No se puede fusionar este nodo de árbol aquí',
    'fr-fr': "Impossible de fusionner ce nœud d'arbre ici",
    'uk-ua': 'Неможливо об’єднати цей вузол дерева тут',
    'de-ch': 'Dieser Knoten kann hier nicht zusammengelegt werden',
    'pt-br': 'Não é possível mesclar este nó da árvore aqui.',
    'hr-hr': '',
  },
  cantMoveToSynonym: {
    'en-us': "Can't move to a synonym",
    'ru-ru': 'Невозможно перейти к синониму',
    'es-es': 'No se puede mover a un sinónimo',
    'fr-fr': 'Impossible de passer à un synonyme',
    'uk-ua': 'Неможливо перейти до синоніма',
    'de-ch': 'Kann nicht zu einem Synonym verschieben',
    'pt-br': 'Não é possível mover para um sinônimo',
    'hr-hr': '',
  },
  cantMergeIntoSynonym: {
    'en-us': "Can't merge into synonyms",
    'ru-ru': 'Невозможно объединить в синонимы.',
    'es-es': 'No se pueden fusionar en sinónimos',
    'fr-fr': 'Impossible de fusionner en synonymes',
    'uk-ua': 'Не можна об’єднувати в синоніми',
    'de-ch': 'Kann nicht zu Synonymen zusammenführen',
    'pt-br': 'Não é possível mesclar em sinônimos.',
    'hr-hr': '',
  },
  cantSynonymizeSynonym: {
    'en-us': "Can't synonymize with a synonym",
    'ru-ru': 'Нельзя использовать синоним для обозначения чего-либо.',
    'es-es': 'No se puede sinonimizar con un sinónimo',
    'fr-fr': 'Impossible de synonymiser avec un synonyme',
    'uk-ua': 'Не можна синонімізувати синонім',
    'de-ch': 'Kann nicht mit einem Synonym synonymisiert werden',
    'pt-br': 'Não é possível usar um sinônimo com outro sinônimo.',
    'hr-hr': '',
  },
  nodeMoveHintMessage: {
    'en-us': 'Select a new parent for "{nodeName:string}"',
    'ru-ru': 'Выберите нового родителя для "{nodeName:string}"',
    'es-es': 'Seleccione un nuevo padre para "{nodeName:string}"',
    'fr-fr': 'Sélectionnez un nouveau parent pour « {nodeName:string} »',
    'uk-ua': 'Виберіть новий батьківський елемент для "{nodeName:string}"',
    'de-ch': 'Wählen Sie ein neues Elternelement für "{nodeName:string}"',
    'pt-br': 'Selecione um novo pai para "{nodeName:string}"',
    'hr-hr': '',
  },
  mergeNode: {
    'en-us': 'Merge node',
    'ru-ru': 'Слияние узлов',
    'es-es': 'Fusionar el nodo',
    'fr-fr': 'Fusionner le nœud',
    'uk-ua': 'Вузол злиття',
    'de-ch': 'Knoten zusammenführen',
    'pt-br': 'Nó de mesclagem',
    'hr-hr': '',
  },
  mergeNodeHere: {
    'en-us': 'Merge "{nodeName:string}" here',
    'ru-ru': 'Объедините "{nodeName:string}" здесь',
    'es-es': 'Fusionar "{nodeName:string}" aquí',
    'fr-fr': 'Fusionner « {nodeName:string} » ici',
    'uk-ua': 'Об\'єднайте "{nodeName:string}" тут',
    'de-ch': 'Führe "{nodeName:string}" hier zusammen',
    'pt-br': 'Mescle "{nodeName:string}" aqui',
    'hr-hr': '',
  },
  mergeNodeHintMessage: {
    'en-us': 'Select a new target for "{nodeName:string}" to be merged into',
    'ru-ru': 'Выберите новый целевой объект для слияния "{nodeName:string}".',
    'es-es': 'Seleccione un nuevo objetivo para fusionar "{nodeName:string}"',
    'fr-fr':
      'Sélectionnez une nouvelle cible pour que « {nodeName:string} » soit fusionné dans',
    'uk-ua':
      'Виберіть нову ціль для «{nodeName:string}», у яку потрібно об’єднати',
    'de-ch': 'Wähle ein neues Ziel um "{nodeName:string}" zusammenzuführen',
    'pt-br':
      'Selecione um novo destino para "{nodeName:string}" a ser mesclado.',
    'hr-hr': '',
  },
  bulkMoveNodeHintMessage: {
    'en-us':
      'Select a new target for "{nodeName:string}" preparations to be moved into',
    'de-ch':
      'Wählen Sie ein neues Ziel für die "{nodeName:string}"-Vorbereitungen aus, die verschoben werden sollen.',
    'es-es':
      'Seleccione un nuevo objetivo para los preparaciones "{nodeName:string}" que se trasladarán a',
    'fr-fr':
      'Sélectionnez une nouvelle cible pour le déplacement des préparations « {nodeName:string} » dans',
    'ru-ru':
      'Выберите новую цель для перемещения подготовительных работ "{nodeName:string}".',
    'uk-ua':
      'Виберіть нову ціль для препаратів "{nodeName:string}", до якої потрібно переміститися',
    'pt-br':
      'Selecione um novo alvo para os preparativos "{nodeName:string}" a serem movidos para',
    'hr-hr': '',
  },
  mergeNodeMessage: {
    'en-us':
      'All references to {treeName:string} node "{nodeName:string}" will be replaced with "{parentName:string}", and all descendants of "{nodeName:string}" will be moved to "{parentName:string}" with any descendants matching in name and rank being themselves merged recursively.',
    'ru-ru':
      'Все ссылки на узел {treeName:string} "{nodeName:string}" будут заменены на "{parentName:string}", а все потомки "{nodeName:string}" будут перемещены в "{parentName:string}", при этом любые потомки, совпадающие по имени и рангу, будут рекурсивно объединены.',
    'es-es':
      'Todas las referencias al nodo {treeName:string} "{nodeName:string}" serán reemplazadas por "{parentName:string}", todos los descendientes de "{nodeName:string}" se moverán a "{parentName:string}" y todos los descendientes que coincidan en nombre y rango se fusionarán de forma recursiva.',
    'fr-fr':
      'Toutes les références au nœud {treeName:string} "{nodeName:string}" seront remplacées par "{parentName:string}", et tous les descendants de "{nodeName:string}" seront déplacés vers "{parentName:string}" avec tous les descendants correspondant en nom et en rang étant eux-mêmes fusionnés de manière récursive.',
    'uk-ua':
      "Усі посилання на вузол {treeName:string} «{nodeName:string}» буде замінено на «{parentName:string}», а всі нащадки «{nodeName:string}» буде переміщено до «{parentName:string}», а будь-які нащадки, що відповідають імені та рангу, будуть самі собою об'єднані рекурсивно.",
    'de-ch':
      'Alle Referenzen zu {treeName:string} "{nodeName:string}" werden mit "{parentName:string}" ersetzt. Alle Nachkommen von "{nodeName:string}" werden nach "{parentName:string}" verschoben, wobei alle Nachkommen, die in Name und Rang übereinstimmen, selbst rekursiv zusammengeführt werden.',
    'pt-br':
      'Todas as referências ao nó {treeName:string} "{nodeName:string}" serão substituídas por "{parentName:string}", e todos os descendentes de "{nodeName:string}" serão movidos para "{parentName:string}", com quaisquer descendentes correspondentes em nome e classificação sendo eles próprios mesclados recursivamente.',
    'hr-hr': '',
  },
  synonymizeNode: {
    'en-us': 'Synonymize node',
    'ru-ru': 'Синонимизировать узел',
    'es-es': 'Sinonimizar nodo',
    'fr-fr': 'Synonymiser le nœud',
    'uk-ua': 'Синонімізувати вузол',
    'de-ch': 'Knoten synonymisieren',
    'pt-br': 'Sinônimo de nó',
    'hr-hr': '',
  },
  makeSynonym: {
    'en-us': 'Make {nodeName:string} a synonym of {synonymName:string}',
    'ru-ru': 'Сделайте {nodeName:string} синонимом {synonymName:string}',
    'es-es': 'Hacer de {nodeName:string} un sinónimo de {synonymName:string}',
    'fr-fr': 'Faire de {nodeName:string} un synonyme de {synonymName:string}',
    'uk-ua': 'Зробити {nodeName:string} синонімом {synonymName:string}',
    'de-ch':
      'Aus {nodeName:string} ein Synonym von {synonymName:string} machen',
    'pt-br': 'Faça de {nodeName:string} um sinônimo de {synonymName:string}',
    'hr-hr': '',
  },
  synonymizeNodeHintMessage: {
    'en-us': 'Select a target for "{nodeName:string}" to be synonymized to',
    'ru-ru':
      'Выберите целевой объект для "{nodeName:string}", который будет синонимизирован.',
    'es-es':
      'Seleccione un objetivo para que "{nodeName:string}" se convierta en sinónimo',
    'fr-fr':
      'Sélectionnez une cible pour que « {nodeName:string} » soit synonymisé à',
    'uk-ua': 'Виберіть ціль для "{nodeName:string}", який буде синонімічним',
    'de-ch': 'Wähle Ziel um "{nodeName:string}" daran zu synonymisieren',
    'pt-br': 'Selecione um alvo para "{nodeName:string}" a ser sinônimo de',
    'hr-hr': '',
  },
  synonymizeMessage: {
    'en-us':
      'The {treeName:string} node "{nodeName:string}" will be made a synonym of "{synonymName:string}".',
    'ru-ru':
      'Узел {treeName:string} "{nodeName:string}" будет синонимом "{synonymName:string}".',
    'es-es':
      'El nodo {treeName:string} "{nodeName:string}" se convertirá en sinónimo de "{synonymName:string}".',
    'fr-fr':
      'Le nœud {treeName:string} «{nodeName:string}» sera rendu synonyme de «{synonymName:string}».',
    'de-ch':
      'Der {treeName:string}-Knoten "{nodeName:string}" wird zu einem Synonym von "{synonymName:string}".',
    'uk-ua':
      'Вузол {treeName:string} "{nodeName:string}" стане синонімом "{synonymName:string}".',
    'pt-br':
      'O nó {treeName:string} "{nodeName:string}" será transformado em sinônimo de "{synonymName:string}".',
    'hr-hr': '',
  },
  desynonymizeNode: {
    'en-us': 'Desynonymize node',
    'ru-ru': 'Десинонимизировать узел',
    'es-es': 'Desinonimizar nodo',
    'fr-fr': 'Désynonymiser le nœud',
    'uk-ua': 'Десинонімізувати вузол',
    'de-ch': 'Knoten desynonymisieren',
    'pt-br': 'Dessinonizar nó',
    'hr-hr': '',
  },
  desynonymizeNodeMessage: {
    'en-us':
      '"{nodeName:string}" will no longer be a synonym of "{synonymName:string}".',
    'ru-ru':
      '"{nodeName:string}" больше не будет синонимом "{synonymName:string}".',
    'es-es':
      '"{nodeName:string}" ya no será sinónimo de "{synonymName:string}".',
    'fr-fr':
      '« {nodeName:string} » ne sera plus synonyme de « {synonymName:string} ».',
    'de-ch':
      '"{nodeName:string}" wird nicht mehr ein Synonym von "{synonymName:string}" sein.',
    'uk-ua':
      '"{nodeName:string}" більше не буде синонімом "{synonymName:string}".',
    'pt-br':
      '"{nodeName:string}" deixará de ser sinônimo de "{synonymName:string}".',
    'hr-hr': '',
  },
  acceptedName: {
    'en-us': 'Preferred: {name:string}',
    'ru-ru': 'Предпочтительный вариант: {name:string}',
    'es-es': 'Preferido: {name:string}',
    'fr-fr': 'Préféré : {name:string}',
    'uk-ua': 'Бажано: {name:string}',
    'de-ch': 'Bevorzugt: {name:string}',
    'pt-br': 'Preferencial: {name:string}',
    'hr-hr': '',
  },
  synonyms: {
    'en-us': 'Synonyms: {names:string}',
    'de-ch': 'Synonyme: {names:string}',
    'es-es': 'Sinónimos: {names:string}',
    'fr-fr': 'Synonymes : {names:string}',
    'ru-ru': 'Синонимы: {names:string}',
    'uk-ua': 'Синоніми: {names:string}',
    'pt-br': 'Sinônimos: {names:string}',
    'hr-hr': '',
  },
  treeViewTitle: {
    'en-us': '{treeName:string} Tree',
    'ru-ru': '{treeName:string} Дерево',
    'es-es': '{treeName:string} Árbol',
    'fr-fr': '{treeName:string} Arbre',
    'uk-ua': '{treeName:string} Дерево',
    'de-ch': '{treeName:string} Baum',
    'pt-br': '{treeName:string} Árvore',
    'hr-hr': '',
  },
  searchTreePlaceholder: {
    'en-us': 'Search Tree',
    'ru-ru': 'Дерево поиска',
    'es-es': 'Árbol de búsqueda',
    'fr-fr': "Rechercher dans l'arbre",
    'uk-ua': 'Дерево пошуку',
    'de-ch': 'Baum durchsuchen',
    'pt-br': 'Árvore de pesquisa',
    'hr-hr': '',
  },
  opened: {
    'en-us': 'Opened',
    'ru-ru': 'Открыто',
    'es-es': 'Abierto',
    'fr-fr': 'Ouvert',
    'uk-ua': 'Відкрито',
    'de-ch': 'Geöffnet',
    'pt-br': 'Aberto',
    'hr-hr': '',
  },
  closed: {
    'en-us': 'Closed',
    'ru-ru': 'Закрыто',
    'es-es': 'Cerrado',
    'fr-fr': 'Fermé',
    'uk-ua': 'ЗАЧИНЕНО',
    'de-ch': 'Geschlossen',
    'pt-br': 'Fechado',
    'hr-hr': '',
  },
  leafNode: {
    'en-us': 'Leaf Node',
    'ru-ru': 'Листовой узел',
    'es-es': 'Nodo de hoja',
    'fr-fr': 'Nœud feuille',
    'uk-ua': 'Листковий вузол',
    'de-ch': 'Blattknoten',
    'pt-br': 'Nó foliar',
    'hr-hr': '',
  },
  nodeStats: {
    comment: "Used to show tree node's direct and indirect usages",
    'en-us': '({directCount:number|formatted}, {childCount:number|formatted})',
    'ru-ru': '({directCount:number|formatted}, {childCount:number|formatted})',
    'es-es': '({directCount:number|formatted}, {childCount:number|formatted})',
    'fr-fr': '({directCount:number|formatted}, {childCount:number|formatted})',
    'uk-ua': "({directCount:number|formatted}', {childCount:number|formatted})",
    'de-ch': '({directCount:number|formatted}, {childCount:number|formatted})',
    'pt-br': '({directCount:number|formatted}, {childCount:number|formatted})',
    'hr-hr': '',
  },
  leafNodeStats: {
    comment: "Used to show leaf tree node's direct usages",
    'en-us': '({directCount:number|formatted})',
    'ru-ru': '({directCount:number|formatted})',
    'es-es': '({directCount:number|formatted})',
    'fr-fr': '({directCount:number|formatted})',
    'uk-ua': "({directCount:number|formatted})'",
    'de-ch': '({directCount:number|formatted})',
    'pt-br': '({directCount:number|formatted})',
    'hr-hr': '',
  },
  directCollectionObjectCount: {
    comment: 'Example: Direct Collection Object count',
    'en-us': 'Direct {collectionObjectTable:string} Count',
    'ru-ru': 'Прямой {collectionObjectTable:string} подсчет',
    'es-es': 'Recuento directo {collectionObjectTable:string}',
    'de-ch': 'Direkte {collectionObjectTable:string} Anzahl',
    'fr-fr': 'Compte direct {collectionObjectTable:string}',
    'uk-ua': 'Прямий підрахунок {collectionObjectTable:string}',
    'pt-br': 'Contagem direta {collectionObjectTable:string}',
    'hr-hr': '',
  },
  indirectCollectionObjectCount: {
    comment: 'Example: Indirect Collection Object count',
    'en-us': 'Indirect {collectionObjectTable:string} Count',
    'ru-ru': 'Косвенный {collectionObjectTable:string} подсчет',
    'es-es': 'Recuento indirecto {collectionObjectTable:string}',
    'fr-fr': 'Compte indirect {collectionObjectTable:string}',
    'uk-ua': 'Непрямий підрахунок {collectionObjectTable:string}',
    'de-ch': 'Indirekte {collectionObjectTable:string} Anzahl',
    'pt-br': 'Contagem indireta {collectionObjectTable:string}',
    'hr-hr': '',
  },
  editRanks: {
    'en-us': 'Edit Ranks',
    'ru-ru': 'Редактировать ранги',
    'es-es': 'Editar rangos',
    'fr-fr': 'Modifier les rangs',
    'uk-ua': 'Редагувати ранги',
    'de-ch': 'Positionen bearbeiten',
    'pt-br': 'Editar classificações',
    'hr-hr': '',
  },
  resourceToDelete: {
    'en-us': 'This will permanently delete the following resource',
    'es-es': 'Esto eliminará permanentemente el siguiente recurso',
    'fr-fr': 'Cela supprimera définitivement la ressource suivante',
    'ru-ru': 'Это приведет к безвозвратному удалению следующего ресурса.',
    'uk-ua': 'Це призведе до остаточного видалення наступного ресурсу',
    'de-ch': 'Dadurch wird die folgende Ressource dauerhaft gelöscht',
    'pt-br': 'Isso excluirá permanentemente o seguinte recurso.',
    'hr-hr': '',
  },
  associatedNodesOnly: {
    'en-us': 'Show only nodes with associated objects',
    'de-ch': 'Es werden nur Knoten mit zugehörigen Objekten angezeigt.',
    'es-es': 'Mostrar solo nodos con objetos asociados',
    'fr-fr': 'Afficher uniquement les nœuds avec des objets associés',
    'ru-ru': 'Отображать только узлы, связанные с объектами.',
    'uk-ua': "Показувати лише вузли з пов'язаними об'єктами",
    'pt-br': 'Mostrar apenas os nós com objetos associados.',
    'hr-hr': '',
  },
  splitView: {
    'en-us': 'Split View',
    'de-ch': 'Geteilte Sicht',
    'es-es': 'Vista dividida',
    'fr-fr': 'Vue fractionnée',
    'ru-ru': 'Разделенный экран',
    'uk-ua': 'Розділений вид',
    'pt-br': 'Visão dividida',
    'hr-hr': '',
  },
  horizontal: {
    'en-us': 'Horizontal',
    'de-ch': 'Horizontal',
    'es-es': 'Horizontal',
    'fr-fr': 'Horizontal',
    'ru-ru': 'Горизонтальный',
    'uk-ua': 'Горизонтальний',
    'pt-br': 'Horizontal',
    'hr-hr': '',
  },
  vertical: {
    'en-us': 'Vertical',
    'de-ch': 'Vertikal',
    'es-es': 'Vertical',
    'fr-fr': 'Vertical',
    'ru-ru': 'Вертикальный',
    'uk-ua': 'Вертикальний',
    'pt-br': 'Vertical',
    'hr-hr': '',
  },
  synchronize: {
    'en-us': 'Synchronize',
    'de-ch': 'Synchronisieren',
    'es-es': 'Sincronizar',
    'fr-fr': 'Synchroniser',
    'uk-ua': 'Синхронізувати',
    'ru-ru': 'Синхронизировать',
    'pt-br': 'Sincronizar',
    'hr-hr': '',
  },
  addNewRank: {
    'en-us': 'Add New Rank',
    'de-ch': 'Neuen Rang hinzufügen',
    'es-es': 'Añadir nuevo rango',
    'fr-fr': 'Ajouter un nouveau rang',
    'ru-ru': 'Добавить новый ранг',
    'uk-ua': 'Додати новий ранг',
    'pt-br': 'Adicionar novo cargo',
    'hr-hr': '',
  },
  chooseParentRank: {
    'en-us': 'Choose Parent Rank',
    'de-ch': 'Übergeordneten Rang auswählen',
    'es-es': 'Elija el rango de los padres',
    'fr-fr': 'Choisir le rang du parent',
    'ru-ru': 'Выберите родительский ранг',
    'uk-ua': 'Виберіть батьківський рейтинг',
    'pt-br': 'Escolha a classificação principal',
    'hr-hr': '',
  },
  moveItems: {
    'en-us': 'Move Items',
    'de-ch': 'Gegenstände verschieben',
    'es-es': 'Mover elementos',
    'fr-fr': 'Déplacer des éléments',
    'ru-ru': 'Переместить предметы',
    'uk-ua': 'Переміщення елементів',
    'pt-br': 'Mover itens',
    'hr-hr': '',
  },
  addTree: {
    'en-us': 'Add Tree',
    'de-ch': 'Baum hinzufügen',
    'es-es': 'Agregar árbol',
    'fr-fr': 'Ajouter un arbre',
    'pt-br': 'Adicionar árvore',
    'ru-ru': 'Добавить дерево',
    'uk-ua': 'Додати дерево',
    'hr-hr': '',
  },
  treePicker: {
    'en-us': 'Tree Picker',
    'de-ch': 'Baumpflücker',
    'es-es': 'Selector de árboles',
    'fr-fr': "Cueilleur d'arbres",
    'pt-br': 'apanhador de árvores',
    'ru-ru': 'Сборщик деревьев',
    'uk-ua': 'Збирач дерев',
    'hr-hr': '',
  },
  botany: {
    'en-us': 'Botany',
    'de-ch': 'Botanik',
    'es-es': 'Botánica',
    'fr-fr': 'Botanique',
    'pt-br': 'Botânica',
    'ru-ru': 'Ботаника',
    'uk-ua': 'Ботаніка',
    'hr-hr': '',
  },
  entomology: {
    'en-us': 'Entomology',
    'de-ch': 'Entomologie',
    'es-es': 'Entomología',
    'fr-fr': 'Entomologie',
    'pt-br': 'Entomologia',
    'ru-ru': 'Энтомология',
    'uk-ua': 'Ентомологія',
    'hr-hr': '',
  },
  herpetology: {
    'en-us': 'Herpetology',
    'de-ch': 'Herpetologie',
    'es-es': 'Herpetología',
    'fr-fr': 'Herpétologie',
    'pt-br': 'Herpetologia',
    'ru-ru': 'Герпетология',
    'uk-ua': 'Герпетологія',
    'hr-hr': '',
  },
  ichthyology: {
    'en-us': 'Ichthyology',
    'de-ch': 'Fischkunde',
    'es-es': 'Ictiología',
    'fr-fr': 'Ichtyologie',
    'pt-br': 'Ictiologia',
    'ru-ru': 'Ихтиология',
    'uk-ua': 'Іхтіологія',
    'hr-hr': '',
  },
  invertpaleo: {
    'en-us': 'Invertebrate Paleontology',
    'de-ch': 'Wirbellosenpaläontologie',
    'es-es': 'Paleontología de invertebrados',
    'fr-fr': 'Paléontologie des invertébrés',
    'pt-br': 'Paleontologia de Invertebrados',
    'ru-ru': 'Палеонтология беспозвоночных',
    'uk-ua': 'Палеонтологія безхребетних',
    'hr-hr': '',
  },
  invertzoo: {
    'en-us': 'Invertebrate Zoology',
    'de-ch': 'Wirbellosenzoologie',
    'es-es': 'Zoología de invertebrados',
    'fr-fr': 'Zoologie des invertébrés',
    'pt-br': 'Zoologia de Invertebrados',
    'ru-ru': 'Зоология беспозвоночных',
    'uk-ua': 'Зоологія безхребетних',
    'hr-hr': '',
  },
  mammalogy: {
    'en-us': 'Mammalogy',
    'de-ch': 'Mammalogie',
    'es-es': 'Mastozoología',
    'fr-fr': 'Mammalogie',
    'pt-br': 'Mamalogia',
    'ru-ru': 'Маммология',
    'uk-ua': 'Мамалогія',
    'hr-hr': '',
  },
  ornithology: {
    'en-us': 'Ornithology',
    'de-ch': 'Vogelkunde',
    'es-es': 'Ornitología',
    'fr-fr': 'Ornithologie',
    'pt-br': 'Ornitologia',
    'ru-ru': 'Орнитология',
    'uk-ua': 'Орнітологія',
    'hr-hr': '',
  },
  paleobot: {
    'en-us': 'Paleobotany',
    'de-ch': 'Paläobotanik',
    'es-es': 'Paleobotánica',
    'fr-fr': 'Paléobotanique',
    'pt-br': 'Paleobotânica',
    'ru-ru': 'Палеоботаника',
    'uk-ua': 'Палеоботаніка',
    'hr-hr': '',
  },
  vascplant: {
    'en-us': 'Vascular Plants',
    'de-ch': 'Gefäßpflanzen',
    'es-es': 'Plantas vasculares',
    'fr-fr': 'Plantes vasculaires',
    'pt-br': 'Plantas Vasculares',
    'ru-ru': 'Сосудистые растения',
    'uk-ua': 'Судинні рослини',
    'hr-hr': '',
  },
  vertpaleo: {
    'en-us': 'Vertebrate Paleontology',
    'de-ch': 'Wirbeltierpaläontologie',
    'es-es': 'Paleontología de vertebrados',
    'fr-fr': 'Paléontologie des vertébrés',
    'pt-br': 'Paleontologia de Vertebrados',
    'ru-ru': 'Палеонтология позвоночных',
    'uk-ua': 'Палеонтологія хребетних',
    'hr-hr': '',
  },
  emptyTree: {
    'en-us': 'Empty Tree',
    'de-ch': 'Leerer Baum',
    'es-es': 'Árbol vacío',
    'fr-fr': 'Arbre vide',
    'pt-br': 'Árvore Vazia',
    'ru-ru': 'Пустое дерево',
    'uk-ua': 'Порожнє дерево',
    'hr-hr': '',
  },
  minerals: {
    'en-us': 'Minerals',
    'de-ch': 'Mineralien',
    'es-es': 'Minerales',
    'fr-fr': 'Minéraux',
    'pt-br': 'Minerais',
    'ru-ru': 'Минералы',
    'uk-ua': 'Мінерали',
    'hr-hr': '',
  },
  rocks: {
    'en-us': 'Rocks',
    'de-ch': 'Felsen',
    'es-es': 'Rocas',
    'fr-fr': 'Roches',
    'pt-br': 'Rochas',
    'ru-ru': 'Камни',
    'uk-ua': 'Скелі',
    'hr-hr': '',
  },
  meteorites: {
    'en-us': 'Meteorites',
    'de-ch': 'Meteoriten',
    'es-es': 'Meteoritos',
    'fr-fr': 'Météorites',
    'pt-br': 'Meteoritos',
    'ru-ru': 'Метеориты',
    'uk-ua': 'Метеорити',
    'hr-hr': '',
  },
  emptyTrees: {
    'en-us': 'Empty Trees',
    'de-ch': 'Leere Bäume',
    'es-es': 'Árboles vacíos',
    'fr-fr': 'Arbres vides',
    'hr-hr': '',
    'pt-br': 'Árvores vazias',
    'ru-ru': 'Пустые деревья',
    'uk-ua': 'Порожні дерева',
  },
  populatedTrees: {
    'en-us': 'Populated Trees',
    'de-ch': 'Besiedelte Bäume',
    'es-es': 'Árboles poblados',
    'fr-fr': 'Arbres peuplés',
    'hr-hr': '',
    'pt-br': 'Árvores Populadas',
    'ru-ru': 'Заселенные деревья',
    'uk-ua': 'Населені дерева',
  },
  defaultTreeCreationStarted: {
    'en-us': 'Default Tree Creation Started',
    'de-ch': 'Erstellung des Standardbaums gestartet',
    'es-es': 'Se inició la creación del árbol predeterminado',
    'fr-fr': "Création de l'arborescence par défaut démarrée",
    'hr-hr': '',
    'pt-br': 'Criação da árvore padrão iniciada',
    'ru-ru': 'Началось создание дерева по умолчанию.',
    'uk-ua': 'Розпочато створення дерева за замовчуванням',
  },
  defaultTreeCreationStartedDescription: {
    'en-us':
      'The tree will be created in the background. You will be notified once it is completed.',
    'de-ch':
      'Der Baum wird im Hintergrund erstellt. Sie werden benachrichtigt, sobald er fertiggestellt ist.',
    'es-es':
      'El árbol se creará en segundo plano. Recibirás una notificación cuando esté completo.',
    'fr-fr':
      "L'arbre sera créé en arrière-plan. Vous serez averti une fois la création terminée.",
    'hr-hr': '',
    'pt-br':
      'A árvore será criada em segundo plano. Você será notificado assim que o processo for concluído.',
    'ru-ru':
      'Дерево будет создано в фоновом режиме. Вы получите уведомление, как только процесс завершится.',
    'uk-ua':
      'Дерево буде створено у фоновому режимі. Ви отримаєте сповіщення, коли це буде завершено.',
  },
  defaultTreeTaskStarted: {
    'en-us': 'The default tree creation process has started.',
    'de-ch':
      'Der Standardprozess zur Erstellung der Baumstruktur wurde gestartet.',
    'es-es': 'Se ha iniciado el proceso de creación del árbol predeterminado.',
    'fr-fr': "Le processus de création de l'arborescence par défaut a démarré.",
    'hr-hr': '',
    'pt-br': 'O processo padrão de criação da árvore foi iniciado.',
    'ru-ru': 'Начался процесс создания дерева по умолчанию.',
    'uk-ua': 'Процес створення дерева за замовчуванням розпочато.',
  },
  defaultTreeTaskFailed: {
    'en-us': 'Default tree creation failed.',
    'de-ch': 'Die Erstellung des Standardbaums ist fehlgeschlagen.',
    'es-es': 'Error en la creación del árbol predeterminado.',
    'fr-fr': "La création de l'arborescence par défaut a échoué.",
    'hr-hr': '',
    'pt-br': 'A criação da árvore padrão falhou.',
    'ru-ru': 'Создание дерева по умолчанию не удалось.',
    'uk-ua': 'Не вдалося створити дерево за замовчуванням.',
  },
  defaultTreeTaskCancelled: {
    'en-us': 'Default tree creation was cancelled.',
    'de-ch': 'Die Erstellung des Standardbaums wurde abgebrochen.',
    'es-es': 'Se canceló la creación del árbol predeterminado.',
    'fr-fr': "La création de l'arborescence par défaut a été annulée.",
    'hr-hr': '',
    'pt-br': 'A criação da árvore padrão foi cancelada.',
    'ru-ru': 'Создание дерева по умолчанию было отменено.',
    'uk-ua': 'Створення дерева за замовчуванням скасовано.',
  },
  defaultTreeTaskCompleted: {
    'en-us': 'Default tree creation completed successfully.',
    'de-ch':
      'Die Erstellung der Standardbaumstruktur wurde erfolgreich abgeschlossen.',
    'es-es': 'La creación del árbol predeterminado se completó correctamente.',
    'fr-fr':
      "La création de l'arborescence par défaut s'est terminée avec succès.",
    'hr-hr': '',
    'pt-br': 'Criação da árvore padrão concluída com sucesso.',
    'ru-ru': 'Создание дерева по умолчанию успешно завершено.',
    'uk-ua': 'Створення дерева за замовчуванням успішно завершено.',
  },
  defaultTreeCreationProgress: {
    comment: 'E.x, Creating tree record 999/1,000',
    'en-us':
      'Creating tree record {current:number|formatted}/{total:number|formatted}',
    'de-ch':
      'Erstelle Baumdatensatz {current:number|formatted}/{total:number|formatted}',
    'es-es':
      'Creando registro de árbol {current:number|formatted}/{total:number|formatted}',
    'fr-fr':
      "Création de l'enregistrement d'arbre {current:number|formatted}/{total:number|formatted}",
    'hr-hr': '',
    'pt-br':
      'Criando registro de árvore {current:number|formatted}/{total:number|formatted}',
    'ru-ru':
      'Создание записи дерева {current:number|formatted}/{total:number|formatted}',
    'uk-ua':
      'Створення запису дерева {current:number|formatted}/{total:number|formatted}',
  },
  defaultTreeCreationLoadingMessage: {
    'en-us': 'Default tree creation is in progress, please wait...',
    'de-ch': 'Die Erstellung der Standardbaumstruktur läuft, bitte warten...',
    'es-es':
      'La creación del árbol predeterminado está en progreso, por favor espere...',
    'fr-fr':
      "La création de l'arborescence par défaut est en cours, veuillez patienter...",
    'hr-hr': '',
    'pt-br': 'A criação da árvore padrão está em andamento, aguarde...',
    'ru-ru':
      'Идет процесс создания дерева по умолчанию, пожалуйста, подождите...',
    'uk-ua': 'Триває створення дерева за замовчуванням, зачекайте...',
  },
  missingRanks: {
    'en-us': 'Missing Ranks',
    'de-ch': 'Fehlende Ränge',
    'es-es': 'Rangos faltantes',
    'fr-fr': 'Rangs manquants',
    'hr-hr': '',
    'pt-br': 'Patentes Ausentes',
    'ru-ru': 'Отсутствующие звания',
    'uk-ua': 'Відсутні ранги',
  },
  missingRanksDescription: {
    'en-us':
      'The populated tree you selected to download contains records in ranks that are missing from your tree.',
    'de-ch':
      'Der von Ihnen zum Herunterladen ausgewählte gefüllte Stammbaum enthält Datensätze in Rängen, die in Ihrem Stammbaum fehlen.',
    'es-es':
      'El árbol poblado que usted seleccionó para descargar contiene registros en rangos que faltan en su árbol.',
    'fr-fr':
      "L'arbre phylogénétique que vous avez sélectionné pour le téléchargement contient des enregistrements à des rangs qui sont absents de votre arbre.",
    'hr-hr': '',
    'pt-br':
      'A árvore genealógica que você selecionou para baixar contém registros em níveis hierárquicos que estão faltando na sua árvore.',
    'ru-ru':
      'Выбранное вами для загрузки дерево содержит записи в рангах, отсутствующих в вашем дереве.',
    'uk-ua':
      'Заповнене дерево, яке ви вибрали для завантаження, містить записи в рангах, яких бракує у вашому дереві.',
  },
  createMissingRanks: {
    'en-us': 'Should the missing ranks be created?',
    'de-ch': 'Sollen die fehlenden Dienstgrade geschaffen werden?',
    'es-es': '¿Se deberían crear los rangos que faltan?',
    'fr-fr': 'Faut-il créer les grades manquants ?',
    'hr-hr': '',
    'pt-br': 'Deveriam ser criadas as patentes que faltam?',
    'ru-ru': 'Следует ли создать недостающие звания?',
    'uk-ua': 'Чи слід створювати відсутні ряди?',
  },
  source: {
    'en-us': 'Source',
    'de-ch': 'Quelle',
    'es-es': 'Fuente',
    'fr-fr': 'Source',
    'hr-hr': '',
    'pt-br': 'Fonte',
    'ru-ru': 'Источник',
    'uk-ua': 'Джерело',
  },
  initializeEmptyTree: {
    'en-us': 'Initialize an empty tree',
    'de-ch': 'Initialisiere einen leeren Baum',
    'es-es': 'Inicializar un árbol vacío',
    'fr-fr': 'Initialiser un arbre vide',
    'hr-hr': '',
    'pt-br': 'Inicialize uma árvore vazia',
    'ru-ru': 'Инициализировать пустое дерево',
    'uk-ua': 'Ініціалізувати порожнє дерево',
  },
  treeManagement: {
    'en-us': 'Tree Management',
    'de-ch': 'Baumpflege',
    'es-es': 'Gestión de árboles',
    'fr-fr': 'Gestion des arbres',
    'pt-br': 'Gestão de árvores',
    'ru-ru': 'Управление деревьями',
    'uk-ua': 'Управління деревами',
    'hr-hr': '',
  },
  synonymizedNodes: {
    'en-us': 'Expand Synonym Behavior',
    'de-ch': 'Synonymverhalten erweitern',
    'es-es': 'Expandir el comportamiento de los sinónimos',
    'fr-fr': 'Développer le comportement des synonymes',
    'pt-br': 'Expandir o comportamento dos sinônimos',
    'ru-ru': 'Развернуть поведение синонимов',
    'uk-ua': 'Розгорнути поведінку синонімів',
    'hr-hr': '',
  },
  synonymizedNodesDescription: {
    'en-us':
      'If enabled, this allows users to add children to synonymized parents and to synonymize a node with children.',
    'de-ch':
      'Ist diese Funktion aktiviert, können Benutzer Kindknoten zu synonymisierten Elternknoten hinzufügen und einen Knoten mit Kindknoten synonymisieren.',
    'es-es':
      'Si está habilitada, esta opción permite a los usuarios agregar nodos hijos a nodos padres sinonimizados y sinonimizar un nodo con sus nodos hijos.',
    'fr-fr':
      "Si cette option est activée, elle permet aux utilisateurs d'ajouter des enfants à des parents synonymisés et de synonymiser un nœud avec ses enfants.",
    'pt-br':
      'Se ativada, essa opção permite que os usuários adicionem filhos a nós pais sinonimizados e sinonimizem um nó com seus filhos.',
    'ru-ru':
      'Если эта функция включена, она позволяет пользователям добавлять дочерние элементы к синонимизированным родительским элементам и синонимизировать узел с дочерними элементами.',
    'uk-ua':
      'Якщо це ввімкнено, користувачі можуть додавати дочірні елементи до синонімізованих батьківських елементів та синонімізувати вузол з дочірніми елементами.',
    'hr-hr': '',
  },
} as const);
