# Generated by Django 2.2.10 on 2021-02-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdataset',
            name='visualorder',
            field=models.JSONField(null=True),
        ),
    ]
