# Generated by Django 3.2.15 on 2024-08-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_auto_20210428_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdataset',
            name='isupdate',
            field=models.BooleanField(default=False),
        ),
    ]
