# Generated by Django 3.2.15 on 2024-11-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_auto_20210428_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdataset',
            name='isupdate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='spdataset',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backer', to='workbench.spdataset'),
        ),
    ]
