# Generated by Django 3.2.15 on 2025-02-25 16:43
'''
    This migration creates the spdatasetattachment table and adds it to the schema config.
'''

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import specifyweb.specify.models
from specifyweb.specify.migration_utils.update_schema_config import update_table_schema_config_with_defaults, revert_table_schema_config

MIGRATION_0006_TABLES = [
    ('SpDataSetAttachment', 'An attachment temporarily associated with a Specify Data Set for use in a WorkBench upload.')
]

def apply_migration(apps, schema_editor):
    # Update Schema config
    Discipline = apps.get_model('specify', 'Discipline')
    for discipline in Discipline.objects.all():
        for table, desc in MIGRATION_0006_TABLES:
            update_table_schema_config_with_defaults(table, discipline.id, desc, apps)

def revert_migration(apps, schema_editor):
    for table, _ in MIGRATION_0006_TABLES:
        revert_table_schema_config(table, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0023_update_schema_config_text'),
        ('workbench', '0005_auto_20210428_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpDataSetAttachment',
            fields=[
                ('id', models.AutoField(db_column='SpDataSetAttachmentID', primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(db_column='Ordinal')),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('timestampcreated', models.DateTimeField(db_column='TimestampCreated', default=django.utils.timezone.now)),
                ('timestampmodified', models.DateTimeField(blank=True, db_column='TimestampModified', default=django.utils.timezone.now, null=True)),
                ('version', models.IntegerField(blank=True, db_column='Version', default=0, null=True)),
                ('attachment', models.ForeignKey(db_column='AttachmentID', on_delete=specifyweb.specify.models.protect_with_blockers, related_name='spdatasetattachments', to='specify.attachment')),
                ('collectionmember', models.ForeignKey(db_column='CollectionMemberID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='spdatasetattachments', to='specify.collection')),
                ('createdbyagent', models.ForeignKey(db_column='CreatedByAgentID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.agent')),
                ('modifiedbyagent', models.ForeignKey(db_column='ModifiedByAgentID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.agent')),
                ('spdataset', models.ForeignKey(db_column='SpDataSetID', on_delete=django.db.models.deletion.CASCADE, related_name='spdatasetattachments', to='workbench.spdataset')),
            ],
            options={
                'db_table': 'spdatasetattachment',
                'ordering': (),
            },
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True)
    ]
