# Generated by Django 3.2.15 on 2024-08-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0006_spdataset_isupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdataset',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backer', to='workbench.spdataset'),
        ),
    ]
