# Generated by Django 3.2.15 on 2024-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0007_spdataset_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spdataset',
            name='isupdate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
