# Generated by Django 2.2.10 on 2021-07-23 16:04

from django.db import migrations, models
import django.db.models.deletion
import django_jsonfield_backport.models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0008_spdataset_remove_spdataset_data_and_result_cols'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spdatasetlock',
            fields=[
                ('spdataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workbench.Spdataset')),
                ('info', django_jsonfield_backport.models.JSONField()),
            ],
            options={
                'db_table': 'spdatasetlock',
            },
        ),
    ]
