# Generated by Django 2.2.10 on 2021-07-23 14:00

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

def copy_spdataset_status(apps, schema_editor):
    Spdataset = apps.get_model('workbench', 'Spdataset')
    Spdatasetlock = apps.get_model('workbench', 'Spdatasetlock')

    for dataset in Spdataset.objects.all():
        if dataset.uploaderstatus is not None:
            # there really shouldn't be any of these since it would imply
            # an upload is in progress while migrating!
            Spdatasetlock.objects.create(spdataset=dataset, info=dataset.uploaderstatus)

class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0009_spdataset_add_lock_table'),
    ]

    operations = [
        migrations.RunPython(copy_spdataset_status)
    ]
