# Generated by Django 2.2.10 on 2021-07-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0010_spdataset_move_status_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spdataset',
            name='uploaderstatus',
        ),
    ]
