# Generated by Django 3.2.15 on 2024-11-01 19:21

from django.db import migrations

from specifyweb.patches.migration_utils import update_is_accepted


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0001_restore_separators'),
    ]

    operations = [
        # Fixes an issue due to a bug in the WorkBench prior to 7.9.0 that did not
        # set accepted nodes to IsAccepted = 1 when they were not synonyms.
        # https://github.com/specify/specify7/issues/5131
        migrations.RunPython(update_is_accepted,
                             migrations.RunPython.noop, atomic=True),
    ]
