# Generated by Django 3.2.15 on 2024-11-02 00:46

from django.db import migrations

from specifyweb.patches.migration_utils import update_coordinates


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_fix_accepted_taxon'),
    ]

    operations = [
        # There are cases from Specify 6 where Longitude and Latitude are captured as decimal values but
        # the accompanying text fields are not populated. In cases where the text fields are not populated,
        # it appears the records do not have coordinates. This script will populate the text fields with the
        # decimal values where the text fields are empty but the decimal values are not.
        migrations.RunPython(update_coordinates,
                             migrations.RunPython.noop, atomic=True),
    ]
