# Generated by Django 3.2.15 on 2023-07-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import specifyweb.specify.build_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spmerging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('taskid', models.CharField(max_length=256)),
                ('mergingstatus', models.CharField(max_length=256)),
                ('timestampcreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestampmodified', models.DateTimeField(auto_now=True)),
                ('createdbyagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='specify.agent')),
                ('modifiedbyagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='specify.agent')),
            ],
            options={
                'db_table': 'spmerging'
            },
        ),
    ] 
