# Generated by Django 3.2.15 on 2024-06-18 15:53

from django.db import migrations, models
import specifyweb.specify.models as spmodels
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0001_initial'),
    ]

    operations = [
        # TODO: Remove this relationship once multiple trees is fully supported,
        # keeping temporarily for backwards compatibility
        # migrations.RemoveField(
        #     model_name='discipline',
        #     name='taxontreedef',
        # ),
        migrations.AddField(
            model_name="taxontreedef",
            name="discipline",
            field=models.ForeignKey(
                db_column="DisciplineID",
                default=spmodels.Discipline.objects.all().first().id,
                on_delete=specifyweb.specify.models.protect_with_blockers,
                related_name="+",
                to="specify.discipline",
            ),
            preserve_default=False,
        ),
    ]
