# Generated by Django 3.2.15 on 2024-11-12 20:28

from django.db import migrations, models
import django.db.models.deletion
import specifyweb.specify.models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# specifyweb.specify.migrations.0007_schema_config_update
# specifyweb.specify.migrations.0008_ageCitations_fix
# specifyweb.specify.migrations.0009_tectonic_ranks
# specifyweb.specify.migrations.0012_add_cojo_to_schema_config

class Migration(migrations.Migration):

    replaces = [('specify', '0005_collectionobjectgroup_parentcojo'), ('specify', '0006_fix_tectonic_tree_fields'), ('specify', '0007_schema_config_update'), ('specify', '0008_ageCitations_fix'), ('specify', '0009_tectonic_ranks'), ('specify', '0010_updateDelete_parentcojo'), ('specify', '0011_cascading_tree_nodes'), ('specify', '0012_add_cojo_to_schema_config')]

    dependencies = [
        ('specify', '0004_stratigraphy_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionobjectgroup',
            name='parentcojo',
            field=models.ForeignKey(db_column='CollectionObjectGroupJoinID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='collectionobjectgroup', to='specify.collectionobjectgroupjoin'),
        ),
        migrations.RenameField(
            model_name='tectonicunittreedefitem',
            old_name='parentitem',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='tectonicunit',
            name='tectonicunittreedef',
        ),
        migrations.RemoveField(
            model_name='tectonicunit',
            name='tectonicunittreedefitem',
        ),
        migrations.RemoveField(
            model_name='tectonicunittreedefitem',
            name='tectonicunittreedef',
        ),
        migrations.AddField(
            model_name='tectonicunit',
            name='definition',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='treeentries', to='specify.tectonicunittreedef'),
        ),
        migrations.AddField(
            model_name='tectonicunit',
            name='definitionitem',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefItemID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='treeentries', to='specify.tectonicunittreedefitem'),
        ),
        migrations.AddField(
            model_name='tectonicunittreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='treedefitems', to='specify.tectonicunittreedef'),
        ),
        migrations.AlterField(
            model_name='absoluteageattachment',
            name='id',
            field=models.AutoField(db_column='absoluteageattachmentid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='absoluteagecitation',
            name='id',
            field=models.AutoField(db_column='absoluteagecitationid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relativeage',
            name='agename',
            field=models.ForeignKey(db_column='AgeNameID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='agename', to='specify.geologictimeperiod'),
        ),
        migrations.AlterField(
            model_name='relativeage',
            name='agenameend',
            field=models.ForeignKey(db_column='AgeNameEndID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='agenameend', to='specify.geologictimeperiod'),
        ),
        migrations.AlterField(
            model_name='relativeage',
            name='id',
            field=models.AutoField(db_column='relativeageid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relativeageattachment',
            name='id',
            field=models.AutoField(db_column='relativeageattachmentid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relativeagecitation',
            name='id',
            field=models.AutoField(db_column='relativeagecitationid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='acceptedtectonicunit',
            field=models.ForeignKey(db_column='AcceptedID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='acceptedchildren', to='specify.tectonicunit'),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='id',
            field=models.AutoField(db_column='tectonicunitid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='tectonicunittreedefs', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='fullnamedirection',
            field=models.IntegerField(blank=True, db_column='FullNameDirection', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='id',
            field=models.AutoField(db_column='tectonicunittreedefid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedefitem',
            name='id',
            field=models.AutoField(db_column='tectonicunittreedefitemid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionobjectgroupjoin',
            name='parentcog',
            field=models.ForeignKey(db_column='ParentCOGID', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.collectionobjectgroup'),
        ),
        migrations.RunPython(
            code=specifyweb.specify.migrations.0007_schema_config_update.Migration.apply_migration,
            reverse_code=specifyweb.specify.migrations.0007_schema_config_update.Migration.revert_migration,
            atomic=True,
        ),
        migrations.AddField(
            model_name='absoluteage',
            name='absoluteagecitation',
            field=models.ForeignKey(db_column='AbsoluteAgeCitationID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='absoluteages', to='specify.absoluteagecitation'),
        ),
        migrations.AddField(
            model_name='relativeage',
            name='relativeagecitation',
            field=models.ForeignKey(db_column='RelativeAgeCitationID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='relativeages', to='specify.relativeagecitation'),
        ),
        migrations.RunPython(
            code=specifyweb.specify.migrations.0008_ageCitations_fix.Migration.apply_migration,
            reverse_code=specifyweb.specify.migrations.0008_ageCitations_fix.Migration.revert_migration,
            atomic=True,
        ),
        migrations.RunPython(
            code=specifyweb.specify.migrations.0009_tectonic_ranks.Migration.consolidated_python_django_migration_operations,
            reverse_code=specifyweb.specify.migrations.0009_tectonic_ranks.Migration.revert_cosolidated_python_django_migration_operations,
            atomic=True,
        ),
        migrations.AlterField(
            model_name='collectionobjectgroup',
            name='parentcojo',
            field=models.ForeignKey(db_column='CollectionObjectGroupJoinID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectionobjectgroup', to='specify.collectionobjectgroupjoin'),
        ),
        migrations.AlterField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.container'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.geography'),
        ),
        migrations.AlterField(
            model_name='geologictimeperiod',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.geologictimeperiod'),
        ),
        migrations.AlterField(
            model_name='lithostrat',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.lithostrat'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.storage'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.taxon'),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.tectonicunit'),
        ),
        migrations.RunPython(
            code=specifyweb.specify.migrations.0012_add_cojo_to_schema_config.Migration.apply_migration,
            reverse_code=specifyweb.specify.migrations.0012_add_cojo_to_schema_config.Migration.revert_migration,
            atomic=True,
        ),
    ]
