# Generated by Django 3.2.15 on 2024-10-16 16:13

from django.db import migrations, models
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0005_collectionobjectgroup_parentcojo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tectonicunittreedefitem',
            old_name='parentitem',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='tectonicunit',
            name='tectonicunittreedef',
        ),
        migrations.RemoveField(
            model_name='tectonicunit',
            name='tectonicunittreedefitem',
        ),
        migrations.RemoveField(
            model_name='tectonicunittreedefitem',
            name='tectonicunittreedef',
        ),
        migrations.AddField(
            model_name='tectonicunit',
            name='definition',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='treeentries', to='specify.tectonicunittreedef'),
        ),
        migrations.AddField(
            model_name='tectonicunit',
            name='definitionitem',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefItemID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='treeentries', to='specify.tectonicunittreedefitem'),
        ),
        migrations.AddField(
            model_name='tectonicunittreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='treedefitems', to='specify.tectonicunittreedef'),
        ),
        migrations.AlterField(
            model_name='absoluteageattachment',
            name='id',
            field=models.AutoField(db_column='absoluteageattachmentid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='absoluteagecitation',
            name='id',
            field=models.AutoField(db_column='absoluteagecitationid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relativeage',
            name='agename',
            field=models.ForeignKey(db_column='AgeNameID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='agename', to='specify.geologictimeperiod'),
        ),
        migrations.AlterField(
            model_name='relativeage',
            name='agenameend',
            field=models.ForeignKey(db_column='AgeNameEndID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='agenameend', to='specify.geologictimeperiod'),
        ),
        migrations.AlterField(
            model_name='relativeage',
            name='id',
            field=models.AutoField(db_column='relativeageid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relativeageattachment',
            name='id',
            field=models.AutoField(db_column='relativeageattachmentid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relativeagecitation',
            name='id',
            field=models.AutoField(db_column='relativeagecitationid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='acceptedtectonicunit',
            field=models.ForeignKey(db_column='AcceptedID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='acceptedchildren', to='specify.tectonicunit'),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='id',
            field=models.AutoField(db_column='tectonicunitid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='tectonicunittreedefs', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='fullnamedirection',
            field=models.IntegerField(blank=True, db_column='FullNameDirection', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='id',
            field=models.AutoField(db_column='tectonicunittreedefid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedefitem',
            name='id',
            field=models.AutoField(db_column='tectonicunittreedefitemid', primary_key=True, serialize=False),
        ),
    ]
