# Generated by Django 3.2.15 on 2024-10-07 19:18

from django.db import migrations, models
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0005_fix_tectonic_tree_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionobjectgroup',
            name='parentcojo',
            field=models.ForeignKey(db_column='CollectionObjectGroupJoinID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='collectionobjectgroup', to='specify.collectionobjectgroupjoin'),
        ),
    ]
