# Generated by Django 3.2.15 on 2024-10-23 14:31

from django.db import migrations, models
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0006_fix_tectonic_tree_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='absoluteage',
            name='absoluteagecitation',
            field=models.ForeignKey(db_column='AbsoluteAgeCitationID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='absoluteages', to='specify.absoluteagecitation'),
        ),
        migrations.AddField(
            model_name='relativeage',
            name='relativeagecitation',
            field=models.ForeignKey(db_column='RelativeAgeCitationID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='relativeages', to='specify.relativeagecitation'),
        ),
    ]
