# Generated by Django 3.2.15 on 2024-10-23 14:31

from django.db import migrations, models
import specifyweb.specify.models

from specifyweb.specify.migration_utils import update_schema_config as usc

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0007_schema_config_update'),
    ]

    def apply_migration(apps, schema_editor):
        usc.update_relative_age_fields(apps)

    def revert_migration(apps, schema_editor):
        usc.update_relative_age_fields(apps)

    operations = [
        migrations.AddField(
            model_name="absoluteage",
            name="absoluteagecitation",
            field=models.ForeignKey(
                db_column="AbsoluteAgeCitationID",
                null=True,
                on_delete=specifyweb.specify.models.protect_with_blockers,
                related_name="absoluteages",
                to="specify.absoluteagecitation",
            ),
        ),
        migrations.AddField(
            model_name="relativeage",
            name="relativeagecitation",
            field=models.ForeignKey(
                db_column="RelativeAgeCitationID",
                null=True,
                on_delete=specifyweb.specify.models.protect_with_blockers,
                related_name="relativeages",
                to="specify.relativeagecitation",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
