# Generated by Django 3.2.15 on 2024-10-23 14:31

from django.db import migrations, models
import specifyweb.specify.models
from specifyweb.specify.update_schema_config import revert_table_field_schema_config, update_table_field_schema_config_with_defaults

def update_fields(apps):
    Discipline = apps.get_model('specify', 'Discipline')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')

    # Add absoluteAgeCitation -> absoluteAge & Add relativeAgeCitation -> relativeAge
    for discipline in Discipline.objects.all():
        update_table_field_schema_config_with_defaults('AbsoluteAge', discipline.id, 'absoluteAgeCitations', apps)
        update_table_field_schema_config_with_defaults('RelativeAge', discipline.id, 'relativeAgeCitations', apps)

def revert_update_fields(apps):
    # Remove absoluteAgeCitation -> absoluteAge and relativeAgeCitation -> relativeAge
    revert_table_field_schema_config('AbsoluteAge', 'absoluteAgeCitations', apps)
    revert_table_field_schema_config('RelativeAge', 'relativeAgeCitations', apps)

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0007_schema_config_update'),
    ]

    def apply_migration(apps, schema_editor):
        update_fields(apps)

    def revert_migration(apps, schema_editor):
        revert_update_fields(apps)

    operations = [
        migrations.AddField(
            model_name='absoluteage',
            name='absoluteagecitation',
            field=models.ForeignKey(db_column='AbsoluteAgeCitationID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='absoluteages', to='specify.absoluteagecitation'),
        ),
        migrations.AddField(
            model_name='relativeage',
            name='relativeagecitation',
            field=models.ForeignKey(db_column='RelativeAgeCitationID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='relativeages', to='specify.relativeagecitation'),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True)
    ]
