# Generated by Django 3.2.15 on 2024-10-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #change dep when merge with prod 
        ('specify', '0007_schema_config_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionobjectgroup',
            name='parentcojo',
            field=models.ForeignKey(db_column='CollectionObjectGroupJoinID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectionobjectgroup', to='specify.collectionobjectgroupjoin'),
        ),
    ]
