# Generated by Django 3.2.15 on 2024-10-31 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0010_updateDelete_parentcojo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.container'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.geography'),
        ),
        migrations.AlterField(
            model_name='geologictimeperiod',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.geologictimeperiod'),
        ),
        migrations.AlterField(
            model_name='lithostrat',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.lithostrat'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.storage'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.taxon'),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='parent',
            field=models.ForeignKey(db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.tectonicunit'),
        ),
    ]
