# Generated by Django 3.2.15 on 2024-11-15 16:17

from django.db import migrations, models
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0012_add_cojo_to_schema_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionobjectgroup',
            name='parentcog',
            field=models.ForeignKey(db_column='ParentCogID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.collectionobjectgroup'),
        ),
    ]
