# Generated by Django 3.2.15 on 2024-11-19 15:29

from django.db import migrations, models
import specifyweb.specify.models
from specifyweb.specify.migration_utils import update_schema_config as usc

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0012_add_cojo_to_schema_config'),
    ]

    def apply_migration(apps, schema_editor):
        usc.update_cog_schema_config(apps)

    def revert_migration(apps, schema_editor):
        usc.revert_update_cog_schema_config(apps)

    operations = [
        migrations.RemoveField(
            model_name='collectionobjectgroup',
            name='parentcojo',
        ),
        migrations.AddField(
            model_name='collectionobjectgroup',
            name='parentcog',
            field=models.ForeignKey(db_column='ParentCogID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers,
                                    related_name='+', to='specify.collectionobjectgroup'),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
