# Generated by Django 3.2.15 on 2024-11-19 15:29

from django.db import migrations, models
import specifyweb.specify.models
from specifyweb.specify.update_schema_config import revert_table_field_schema_config, update_table_field_schema_config_with_defaults

def update_schema_config(apps):
    revert_table_field_schema_config('CollectionObjectGroup', 'parentCojo', apps)
    revert_table_field_schema_config('CollectionObjectGroup', 'parentCog', apps)

    Discipline = apps.get_model('specify', 'Discipline')
    for discipline in Discipline.objects.all():
        update_table_field_schema_config_with_defaults('CollectionObjectGroup', discipline.id, 'parentCog', apps)

def revert_update(apps):
    revert_table_field_schema_config('CollectionObjectGroup', 'parentCog', apps)
    Discipline = apps.get_model('specify', 'Discipline')
    for discipline in Discipline.objects.all():
        update_table_field_schema_config_with_defaults('CollectionObjectGroup', discipline.id, 'parentCojo', apps)

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0012_add_cojo_to_schema_config'),
    ]

    def apply_migration(apps, schema_editor):
        update_schema_config(apps)

    def revert_migration(apps, schema_editor):
        revert_update(apps)

    operations = [
        migrations.RemoveField(
            model_name='collectionobjectgroup',
            name='parentcojo',
        ),
        migrations.AddField(
            model_name='collectionobjectgroup',
            name='parentcog',
            field=models.ForeignKey(db_column='ParentCogID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.collectionobjectgroup'),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
