# Generated by Django 3.2.15 on 2024-11-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0013_collectionobjectgroup_parentcog'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionobjecttype',
            name='catalognumformatname',
            field=models.CharField(blank=True, db_column='CatalogFormatNumName', max_length=256, null=True),
        ),
    ]
