# Generated by Django 3.2.15 on 2024-10-01 21:19

from django.db import migrations, models
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0013_collectionobjectgroup_parentcog'),
    ]

    operations = [
        migrations.AddField(
            model_name='spqueryfield',
            name='isstrict',
            field=models.BooleanField(blank=True, db_column='IsStrict', null=True),
        )
    ]
