# Generated by Django 3.2.15 on 2024-12-03 18:59

from django.db import migrations, models
from specifyweb.specify.migration_utils import update_schema_config as usc

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0014_spqueryfield_strict'),
    ]

    def apply_migration(apps, schema_editor):
        usc.update_age_schema_config(apps)

    def revert_migration(apps, schema_editor):
        usc.revert_update_age_schema_config(apps)

    operations = [
        migrations.AddField(
            model_name='absoluteage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0, null=True),
        ),
        migrations.AddField(
            model_name='relativeage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0, null=True),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
