# Generated by Django 3.2.15 on 2024-12-03 18:59

from django.db import migrations, models
from specifyweb.specify.update_schema_config import revert_table_field_schema_config, update_table_field_schema_config_with_defaults

def update_schema_config(apps):
    # Revert before adding to avoid duplicates
    revert_update(apps)

    Discipline = apps.get_model('specify', 'Discipline')
    for discipline in Discipline.objects.all():
        update_table_field_schema_config_with_defaults('AbsoluteAge', discipline.id, 'version', apps)
        update_table_field_schema_config_with_defaults('RelativeAge', discipline.id, 'version', apps)

def revert_update(apps):
    revert_table_field_schema_config('AbsoluteAge', 'version', apps)
    revert_table_field_schema_config('RelativeAge', 'version', apps)

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0014_spqueryfield_strict'),
    ]

    def apply_migration(apps, schema_editor):
        update_schema_config(apps)

    def revert_migration(apps, schema_editor):
        revert_update(apps)

    operations = [
        migrations.AddField(
            model_name='absoluteage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0, null=True),
        ),
        migrations.AddField(
            model_name='relativeage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0, null=True),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
