# Generated by Django 3.2.15 on 2024-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0014_spqueryfield_strict'),
    ]

    operations = [
        migrations.AddField(
            model_name='absoluteage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0, null=True),
        ),
        migrations.AddField(
            model_name='relativeage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0, null=True),
        ),
    ]
