# Generated by Django 3.2.15 on 2024-11-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0015_add_version_to_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionobjecttype',
            name='catalognumberformatname',
            field=models.CharField(blank=True, db_column='CatalogNumberFormatName', max_length=255, null=True),
        ),
    ]
