# Generated by Django 3.2.15 on 2024-11-21 20:08

from django.db import migrations
from django.db.models import Q

from specifyweb.specify.datamodel import datamodel

SCHEMA_NAME = 'Catalog Number Format Name'

def add_cot_catnum_to_schema(apps, schema_editor): 
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')

    CollectionObjectType_Table  = datamodel.get_table_strict('collectionobjecttype')
    catalognumber_format_field = CollectionObjectType_Table.get_field_strict('catalogNumberFormatName')

    for container in Splocalecontainer.objects.filter(name='collectionobjecttype', schematype=0): 
        schema_item, created = Splocalecontaineritem.objects.get_or_create(name='catalogNumberFormatName', container=container)
        schema_item.type = catalognumber_format_field.type
        schema_item.isrequired = catalognumber_format_field.required
        if created: 
            schema_item.version = 0

        schema_item.save()
        Splocaleitemstr.objects.get_or_create(language='en', text=SCHEMA_NAME, itemname=schema_item)
        Splocaleitemstr.objects.get_or_create(language='en', text=SCHEMA_NAME, itemdesc=schema_item)

def remove_cot_catnum_from_schema(apps, schema_editor): 
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')

    containers = Splocalecontainer.objects.filter(name='collectionobjecttype', schematype=0)
    items = Splocalecontaineritem.objects.filter(name='catalogNumberFormatName', container__in=containers)

    filters = Q(language='en', text=SCHEMA_NAME) & (Q(itemname__in=items) | Q(itemdesc__in=items))
    locale_strings = Splocaleitemstr.objects.filter(filters)

    locale_strings.delete()
    items.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0015_collectionobjecttype_catalognumformatname'),
    ]

    operations = [
        migrations.RunPython(add_cot_catnum_to_schema, remove_cot_catnum_from_schema, atomic=True)
    ]
