# Generated by Django 3.2.15 on 2024-11-21 20:08

from django.db import migrations
from specifyweb.specify.migration_utils import update_schema_config as usc

"""
This migration fixes two bugs introduced in other migrations by the functions 
from .migration_utils.update_schema_config.

Specifically, this migration does the following: 

- Adds the 'type' and 'isrequired' fields to splocalecontaineritems
- The caption of tables was being set to their descriptions, this sets it to 
  the proper lables
"""

class Migration(migrations.Migration):
    dependencies = [
        ('specify', '0016_collectionobjecttype_catalognumformatname'),
    ]

    operations = [
        migrations.RunPython(usc.schemaconfig_fixes,
                             migrations.RunPython.noop, atomic=True)
    ]
