# Generated by Django 3.2.15 on 2024-11-21 20:08

from django.db import migrations
from specifyweb.specify.migration_utils import update_schema_config as usc

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0017_schemaconfig_fixes'),
    ]

    operations = [
        migrations.RunPython(usc.add_cot_catnum_to_schema,
                             usc.remove_cot_catnum_from_schema, atomic=True)
    ]
