# Generated by Django 3.2.15 on 2024-11-21 20:08

from django.db import migrations
from specifyweb.specify.migration_utils import migration_helpers as usc
from specifyweb.specify.migration_utils.migration_helpers.helper_0018_cot_catnum_schema import add_cot_catnum_to_schema, remove_cot_catnum_from_schema

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0017_schemaconfig_fixes'),
    ]

    operations = [
        migrations.RunPython(add_cot_catnum_to_schema,
                             remove_cot_catnum_from_schema, atomic=True)
    ]
