# Generated by Django 3.2.15 on 2024-12-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0018_cot_catnum_schema'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='collectionobjectgroup',
        #     name='parentcog',
        # ),
    ]
