# Generated by Django 3.2.15 on 2025-01-30 20:01

from django.db import migrations, models
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0023_update_schema_config_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionobjectgroupjoin',
            name='childco',
            field=models.OneToOneField(db_column='ChildCOID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='cojo', to='specify.collectionobject'),
        ),
    ]
