# Generated by Django 3.2.15 on 2025-01-30 20:01

"""
    This migration changes the cascading delete to a save blocker for childco.
"""

from django.db import migrations, models
import specifyweb.backend.datamodel.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0024_add_uniqueIdentifier_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionobjectgroupjoin',
            name='childco',
            field=models.OneToOneField(db_column='ChildCOID', null=True, on_delete=specifyweb.backend.datamodel.models.protect_with_blockers, related_name='cojo', to='specify.collectionobject'),
        ),
    ]
