# Generated by Django 3.2.15 on 2025-02-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0023_update_schema_config_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='definition',
            field=models.ForeignKey(db_column='TaxonTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.taxontreedef'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='definitionitem',
            field=models.ForeignKey(db_column='TaxonTreeDefItemID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.taxontreedefitem'),
        ),
        migrations.AlterField(
            model_name='taxontreedefitem',
            name='parent',
            field=models.ForeignKey(db_column='ParentItemID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.taxontreedefitem'),
        ),
        migrations.AlterField(
            model_name='taxontreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='TaxonTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treedefitems', to='specify.taxontreedef'),
        ),
    ]
