# Generated by Django 3.2.15 on 2025-04-11 15:35
import re
from django.core.exceptions import MultipleObjectsReturned
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q
from specifyweb.specify.models import datamodel
from specifyweb.specify.models_utils.load_datamodel import FieldDoesNotExistError


MIGRATION_0027_FIELDS = {
    'CollectionObject': ['parentCO', 'children'],
}

MIGRATION_0027_UPDATE_FIELDS = {
    'CollectionObject': [
        ('parentCO', 'Parent Collection Object', 'Parent CollectionObject'),
        ('children', 'Children', 'Children'),
    ]
}

HIDDEN_FIELDS = [
    "timestampcreated", "timestampmodified", "version", "createdbyagent", "modifiedbyagent"
]


def datamodel_type_to_schematype(datamodel_type: str) -> str:
    return "".join(map(lambda type_part: type_part.lower().capitalize(), datamodel_type.split('-')))


def camel_to_spaced_title_case(camel_case: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", " ", camel_case).title()


def update_table_field_schema_config_with_defaults(
    table_name,
    discipline_id: int,
    field_name: str,
    apps
):
    table = datamodel.get_table(table_name)
    if table is None:
        return

    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')

    try:
        sp_local_container, _ = Splocalecontainer.objects.get_or_create(
            name=table.name.lower(),
            discipline_id=discipline_id,
            schematype=0,
        )
    except MultipleObjectsReturned:
        sp_local_container = Splocalecontainer.objects.filter(
            name=table.name.lower(),
            discipline_id=discipline_id,
            schematype=0
        ).first()

    try:
        field = table.get_field_strict(field_name)
    except (FieldDoesNotExistError, AttributeError):
        if field_name in {'parentCog', 'parentCO', 'children', 'componentParent', 'components'}:
            return
        raise

    java_type = datamodel_type_to_schematype(field.type) if field.is_relationship else field.type
    sp_local_container_item, _ = Splocalecontaineritem.objects.get_or_create(
        name=field_name,
        container=sp_local_container,
        type=java_type,
        ishidden=field_name.lower() in HIDDEN_FIELDS,
        isrequired=field.required,
        issystem=table.system,
        version=0,
    )

    field_description = camel_to_spaced_title_case(field.name)
    for k, text in {
        "itemname": field_description,
        "itemdesc": field_description,
    }.items():
        itm_str = {
            'text': text,
            'language': 'en',
            'version': 0,
        }
        itm_str[k] = sp_local_container_item
        Splocaleitemstr.objects.get_or_create(**itm_str)


def revert_table_field_schema_config(table_name, field_name, apps):
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')

    containers = Splocalecontainer.objects.filter(name__iexact=table_name)
    items = Splocalecontaineritem.objects.filter(container__in=containers, name__iexact=field_name)
    Splocaleitemstr.objects.filter(
        Q(itemname__in=items) |
        Q(itemdesc__in=items)
    ).delete()
    items.delete()


def update_co_children_fields(apps):
    Discipline = apps.get_model('specify', 'Discipline')
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')

    for discipline in Discipline.objects.all():
        for table, fields in MIGRATION_0027_FIELDS.items():
            for field in fields:
                update_table_field_schema_config_with_defaults(table, discipline.id, field, apps)

    for table, fields in MIGRATION_0027_UPDATE_FIELDS.items():
        containers = Splocalecontainer.objects.filter(name=table.lower())
        for container in containers:
            for field_name, new_name, new_desc in fields:
                items = Splocalecontaineritem.objects.filter(
                    container=container,
                    name__iexact=field_name,
                )
                for item in items:
                    localized_items_desc = Splocaleitemstr.objects.filter(itemdesc_id=item.id).first()
                    localized_items_name = Splocaleitemstr.objects.filter(itemname_id=item.id).first()
                    if localized_items_desc is not None:
                        localized_items_desc.text = new_desc
                        localized_items_desc.save()
                    if localized_items_name is not None:
                        localized_items_name.text = new_name
                        localized_items_name.save()


def revert_co_children_fields(apps):
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')

    for table, fields in MIGRATION_0027_FIELDS.items():
        for field in fields:
            revert_table_field_schema_config(table, field, apps)

    for table, fields in MIGRATION_0027_UPDATE_FIELDS.items():
        containers = Splocalecontainer.objects.filter(name=table.lower())
        for container in containers:
            for field_name, _, _ in fields:
                items = Splocalecontaineritem.objects.filter(
                    container=container,
                    name__iexact=field_name,
                )
                for item in items:
                    item.ishidden = False
                    item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0026_taxontreedef_alter_delete'),
    ]

    def apply_migration(apps, schema_editor):
        update_co_children_fields(apps)

    def revert_migration(apps, schema_editor):
        revert_co_children_fields(apps)

    operations = [
        migrations.AddField(
            model_name='collectionobject',
            name='parentco',
            field=models.ForeignKey(db_column='ParentCOID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.collectionobject'),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
