# Generated by Django 3.2.15 on 2025-03-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0026_taxontreedef_alter_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='spquery',
            name='selectseries',
            field=models.BooleanField(blank=True, db_column='SelectSeries', null=True),
        ),
    ]
