# Generated by Django 3.2.15 on 2025-04-11 15:35
from django.apps import apps as specify_apps
from django.db import migrations, models
import django.db.models.deletion
from specifyweb.specify.migration_utils import update_schema_config as usc

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0026_taxontreedef_alter_delete'),
    ]

    def apply_migration(apps, schema_editor):
        usc.update_co_children_fields(apps)

    def revert_migration(apps, schema_editor):
        usc.revert_co_children_fields(apps)

    operations = [
        migrations.AddField(
            model_name='collectionobject',
            name='parentco',
            field=models.ForeignKey(db_column='ParentCOID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.collectionobject'),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
