# Generated by Django 3.2.15 on 2024-11-21 20:08

from django.db import migrations
from django.db.models import F

from specifyweb.specify.migration_utils.sp7_schemaconfig import (
MIGRATION_0028_TABLES
)

CONTAINER_MIGRATIONS = MIGRATION_0028_TABLES

def fix_table_description(apps):
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')

    for table_name, table_desc in CONTAINER_MIGRATIONS:
        containers = Splocalecontainer.objects.filter(
            name=table_name.lower(), schematype=0)

        Splocaleitemstr.objects.filter(
         containerdesc__in=containers
        ).update(text=table_desc)

def schemaconfig_fixes(apps, schema_editor):
    fix_table_description(apps)

class Migration(migrations.Migration):
    dependencies = [
        ('specify', '0027_CO_children'),
    ]

    operations = [
        migrations.RunPython(schemaconfig_fixes,
                             migrations.RunPython.noop, atomic=True)
    ]
