# Generated by Django 4.2.18 on 2025-05-12 07:30

from django.db import migrations, models
import django.db.models.deletion

from specifyweb.specify.migration_utils import update_schema_config as usc
class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0028_selectseries'),
    ]

    def apply_migration(apps, schema_editor):
        usc.remove_collectionobject_parentco(apps)

    def revert_migration(apps, schema_editor):
        usc.revert_remove_collectionobject_parentco(apps)

    operations = [
        migrations.RemoveField(
            model_name='collectionobject',
            name='parentco',
        ),
        migrations.AddField(
            model_name='collectionobject',
            name='componentParent',
            field=models.ForeignKey(db_column='ComponentParentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='specify.collectionobject'),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
