# Generated by Django 4.2.18 on 2025-05-21 10:53

"""
    This migration makes the selectseries column default to False.
    Also, updates old queries to make their selectseries value False.
"""

from django.db import migrations, models


def make_selectseries_false(apps):
    spquery = apps.get_model('specify', 'Spquery')
    spquery.objects.filter(selectseries=None).update(selectseries=False)

def revert_selectseries(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0030_fix_storage_uniqueidentifier'),
    ]

    def apply_migration(apps, schema_editor):
        make_selectseries_false(apps)

    operations = [
        migrations.AlterField(
            model_name='spquery',
            name='selectseries',
            field=models.BooleanField(blank=True, db_column='SelectSeries', default=False, null=True),
        ),
        # No revert function added since this patches faulty data
        migrations.RunPython(apply_migration, revert_selectseries, atomic=True)
    ]
