# Generated by Django 4.2.18 on 2025-05-01 08:47

from django.db import migrations, models

from django.apps import apps as specify_apps
from specifyweb.specify.migration_utils import migration_helpers as usc
from specifyweb.specify.migration_utils.migration_helpers.helper_0032_add_quantities_gift import add_quantities_gift, revert_add_quantities_gift

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0031_add_default_for_selectseries'),
    ]

    def apply_migration(apps, schema_editor):
        add_quantities_gift(apps)

    def revert_migration(apps, schema_editor):
        revert_add_quantities_gift(apps)

    operations = [
        migrations.AddField(
            model_name='giftpreparation',
            name='quantityresolved',
            field=models.IntegerField(blank=True, db_column='QuantityResolved', null=True),
        ),
        migrations.AddField(
            model_name='giftpreparation',
            name='quantityreturned',
            field=models.IntegerField(blank=True, db_column='QuantityReturned', null=True),
        ),
        migrations.RunPython(apply_migration, revert_migration, atomic=True),
    ]
