# Generated by Django 4.2.18 on 2025-07-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0032_remove_spquery_selectseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionobject',
            name='componentParent',
        ),
    ]
