# Generated by Django 4.2.18 on 2025-06-12 23:10

from django.db import migrations, models
from specifyweb.specify.migration_utils import update_schema_config as usc

def apply_migration(apps, schema_editor):
    usc.update_accession_date_fields(apps)

def revert_migration(apps, schema_editor):
    usc.revert_update_accession_date_fields(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0033_update_paleo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='date1',
            field=models.DateTimeField(blank=True, null=True, db_column='Date1'),
        ),
        migrations.AddField(
            model_name='accession',
            name='date1precision',
            field=models.SmallIntegerField(default=1, blank=True, null=True, db_column='Date1Precision'),
        ),
        migrations.AddField(
            model_name='accession',
            name='date2',
            field=models.DateTimeField(blank=True, null=True, db_column='Date2'),
        ),
        migrations.AddField(
            model_name='accession',
            name='date2precision',
            field=models.SmallIntegerField(default=1, blank=True, null=True, db_column='Date2Precision'),
        ),
        migrations.AddField(
            model_name='accession',
            name='dateaccessionedprecision',
            field=models.SmallIntegerField(default=1, blank=True, null=True, db_column='DateAccessionedPrecision'),
        ),
        migrations.AddField(
            model_name='accession',
            name='dateacknowledgedprecision',
            field=models.SmallIntegerField(default=1, blank=True, null=True, db_column='DateAcknowledgedPrecision'),
        ),
        migrations.AddField(
            model_name='accession',
            name='datereceivedprecision',
            field=models.SmallIntegerField(default=1, blank=True, null=True, db_column='DateReceivedPrecision'),
        ),
        migrations.RunPython(
            apply_migration,
            revert_migration,
            atomic=True,
        ),
    ]