# Generated by Django 3.2.15 on 2025-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0034_accession_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absoluteage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='absoluteageattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='absoluteagecitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='accession',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='accessionagent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='accessionattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='accessionauthorization',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='accessioncitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='addressofrecord',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='agentattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='agentgeography',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='agentspecialty',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='agentvariant',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='attachmentimageattribute',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='attachmentmetadata',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='attachmenttag',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='attributedef',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='autonumberingscheme',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='borrowagent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='borrowattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='borrowmaterial',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='borrowreturnmaterial',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingevent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingeventattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingeventattr',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingeventattribute',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingeventauthorization',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingtrip',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingtripattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingtripattribute',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectingtripauthorization',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobject',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectattr',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectattribute',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectcitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectgroup',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectgroupjoin',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectgrouptype',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjectproperty',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionobjecttype',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionrelationship',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collectionreltype',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='collector',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='commonnametx',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='commonnametxcitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='conservdescription',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='conservdescriptionattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='conservevent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='conserveventattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='deaccession',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='deaccessionagent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='deaccessionattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='determination',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='determinationcitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='determiner',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='disposalagent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='disposalattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='disposalpreparation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='division',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='dnaprimer',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='dnasequence',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='dnasequenceattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='dnasequencingrun',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='dnasequencingrunattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='dnasequencingruncitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exchangein',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exchangeinattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exchangeinprep',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exchangeout',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exchangeoutattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exchangeoutprep',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exsiccata',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='exsiccataitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='extractor',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='fieldnotebook',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='fieldnotebookattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='fieldnotebookpage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='fieldnotebookpageattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='fieldnotebookpageset',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='fieldnotebookpagesetattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='fundingagent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='geocoorddetail',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='geography',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='geographytreedef',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='geographytreedefitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='geologictimeperiod',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='geologictimeperiodtreedef',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='geologictimeperiodtreedefitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='gift',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='giftagent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='giftattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='giftpreparation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='institutionnetwork',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='journal',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='latlonpolygon',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='lithostrat',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='lithostrattreedef',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='lithostrattreedefitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='loanagent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='loanattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='loanpreparation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='loanreturnpreparation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='locality',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='localityattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='localitycitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='localitydetail',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='localitynamealias',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='materialsample',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='morphbankview',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='otheridentifier',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='paleocontext',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='pcrperson',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='permitattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='picklistitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='preparationattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='preparationattr',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='preparationattribute',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='preparationproperty',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='preptype',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='referencework',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='referenceworkattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='relativeage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='relativeageattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='relativeagecitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='repositoryagreement',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='repositoryagreementattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spappresource',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spappresourcedata',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spappresourcedir',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spauditlog',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spauditlogfield',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='specifyuser',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spexportschema',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spexportschemaitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spexportschemaitemmapping',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spexportschemamapping',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spfieldvaluedefault',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='splocalecontainer',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='splocalecontaineritem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='splocaleitemstr',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spprincipal',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spquery',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spqueryfield',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spreport',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spsymbiotainstance',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='sptasksemaphore',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spversion',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spviewsetobj',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='spvisualquery',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='storageattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='storagetreedef',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='storagetreedefitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='taxonattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='taxonattribute',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='taxoncitation',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='taxontreedef',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='taxontreedefitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedefitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='treatmentevent',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='treatmenteventattachment',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='voucherrelationship',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='workbench',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='workbenchrowexportedrelationship',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='workbenchtemplate',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
        migrations.AlterField(
            model_name='workbenchtemplatemappingitem',
            name='version',
            field=models.IntegerField(blank=True, db_column='Version', default=0),
        ),
    ]
