# Generated by Django 4.2.18 on 2025-06-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0035_version_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spquery',
            name='selectseries',
        ),
    ]