# Generated by Django 4.2.18 on 2025-06-04 16:59

from django.db import migrations

def add_column_if_missing(apps, schema_editor):
    SpQuery = apps.get_model('specify', 'SpQuery')
    table = SpQuery._meta.db_table
    column = 'SelectSeries'

    with schema_editor.connection.cursor() as c:
        c.execute(
            """
            SELECT 1
              FROM information_schema.columns
             WHERE table_schema = DATABASE()
               AND table_name   = %s
               AND column_name  = %s
            """,
            [table, column]
        )
        if not c.fetchone():
            c.execute(f'ALTER TABLE `{table}` ADD COLUMN `{column}` BIT NULL;')


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0035_version_required'),
    ]

    operations = [
        migrations.RunPython(add_column_if_missing, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='spquery',
            name='selectseries',
        ),
    ]
