# Generated by Django 4.2.22 on 2025-07-22 10:35

from django.db import migrations, models

def make_smushed_false(apps, schema_editor):
    Spquery = apps.get_model('specify', 'Spquery')
    Spquery.objects.filter(smushed__isnull=True).update(smushed=False)

def revert_smushed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0036_remove_spquery_selectseries'),
    ]

    def apply_migration(apps, schema_editor):
        make_smushed_false(apps, schema_editor)

    operations = [
        migrations.AlterField(
            model_name='spquery',
            name='smushed',
            field=models.BooleanField(blank=True, db_column='Smushed', default=False, null=True),
        ),
        migrations.RunPython(apply_migration, revert_smushed, atomic=True)

    ]
