# Generated by Django 4.2.22 on 2025-08-05 07:52

from django.db import migrations, models

def make_countonly_false(apps, schema_editor):
    Spquery = apps.get_model('specify', 'Spquery')
    Spquery.objects.filter(countonly__isnull=True).update(countonly=False)

def revert_countonly(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0037_make_smushed_default_false'),
    ]

    def apply_migration(apps, schema_editor):
        make_countonly_false(apps, schema_editor)

    operations = [
        migrations.AlterField(
            model_name='spquery',
            name='countonly',
            field=models.BooleanField(blank=True, db_column='CountOnly', default=False, null=True),
        ),
        migrations.RunPython(apply_migration, revert_countonly, atomic=True)
    ]
