# Generated by Django 4.2.22 on 2025-07-23 21:18

from django.apps import apps as specify_apps
from django.db import migrations, models
from specifyweb.specify.models import protect_with_blockers

from specifyweb.specify.migration_utils import update_schema_config as usc

def consolidated_0038_forward(apps, schema_editor):
    usc.update_loan_and_gift_agent_fields(apps)
    usc.update_loan_and_gift_agents(apps)

def consolidated_0038_backward(apps, schema_editor):
    usc.revert_loan_and_gift_agents(apps)
    usc.revert_loan_and_gift_agent_fields(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0038_make_countonly_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='agent1',
            field=models.ForeignKey(db_column='Agent1ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent2',
            field=models.ForeignKey(db_column='Agent2ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent3',
            field=models.ForeignKey(db_column='Agent3ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent4',
            field=models.ForeignKey(db_column='Agent4ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent5',
            field=models.ForeignKey(db_column='Agent5ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent1',
            field=models.ForeignKey(db_column='Agent1ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent2',
            field=models.ForeignKey(db_column='Agent2ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent3',
            field=models.ForeignKey(db_column='Agent3ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent4',
            field=models.ForeignKey(db_column='Agent4ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent5',
            field=models.ForeignKey(db_column='Agent5ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.RunPython(
            consolidated_0038_forward,
            consolidated_0038_backward,
            atomic=True,
        ),
    ]