# Generated by Django 4.2.22 on 2025-07-23 21:18

from django.apps import apps as specify_apps
from django.db import migrations, models
from specifyweb.specify.models import protect_with_blockers

from specifyweb.specify.migration_utils.update_schema_config import (
    revert_table_field_schema_config,
    update_table_field_schema_config_with_defaults,
)
from specifyweb.specify.migration_utils.sp7_schemaconfig import (
    MIGRATION_0038_FIELDS as SCHEMA_CONFIG_RAW_FIELDS,
    MIGRATION_0038_UPDATE_FIELDS as SCHEMA_CONFIG_FIELD_DESC,
)

def update_0038_fields(apps):
    """
    Update table-field schema entries for plain field names
    (e.g., MIGRATION_0038_FIELDS).
    """
    Discipline = apps.get_model('specify', 'Discipline')
    for discipline in Discipline.objects.all():
        for table, fields in SCHEMA_CONFIG_RAW_FIELDS.items():
            for field_name in fields:
                update_table_field_schema_config_with_defaults(table, discipline.id, field_name, apps)

def revert_0038_fields(apps):
    """
    Revert table-field entries for plain field names.
    """
    for table, fields in SCHEMA_CONFIG_RAW_FIELDS.items():
        for field_name in fields:
            revert_table_field_schema_config(table, field_name, apps)

def update_0038_schema_config_field_desc(apps, schema_editor):
    """
    Update field descriptions and display names using MIGRATION_0038_UPDATE_FIELDS
    (tuple: (fieldName, newLabel, newDesc)).
    """
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')
    Splocaleitemstr = apps.get_model('specify', 'Splocaleitemstr')

    for table, fields in SCHEMA_CONFIG_FIELD_DESC.items():
        containers = Splocalecontainer.objects.filter(name=table.lower())
        for container in containers:
            for (field_name, new_name, new_desc) in fields:
                items = Splocalecontaineritem.objects.filter(
                    container=container,
                    name=field_name.lower()
                )
                for item in items:
                    item.ishidden = True
                    item.save()
                    desc_str = Splocaleitemstr.objects.filter(itemdesc_id=item.id).first()
                    name_str = Splocaleitemstr.objects.filter(itemname_id=item.id).first()
                    if not desc_str or not name_str:
                        continue
                    desc_str.text = new_desc
                    desc_str.save()
                    name_str.text = new_name
                    name_str.save()

def revert_0038_schema_config_field_desc(apps, schema_editor):
    """
    Revert the field name/description updates.
    """
    Splocalecontainer = apps.get_model('specify', 'Splocalecontainer')
    Splocalecontaineritem = apps.get_model('specify', 'Splocalecontaineritem')

    for table, fields in SCHEMA_CONFIG_FIELD_DESC.items():
        containers = Splocalecontainer.objects.filter(name=table.lower())
        for container in containers:
            for (field_name, _, _) in fields:
                items = Splocalecontaineritem.objects.filter(
                    container=container,
                    name=field_name.lower()
                )
                for item in items:
                    # If needed, reset ishidden or revert text
                    pass

def consolidated_0038_forward(apps, schema_editor):
    update_0038_fields(apps)
    update_0038_schema_config_field_desc(apps, schema_editor)

def consolidated_0038_backward(apps, schema_editor):
    revert_0038_schema_config_field_desc(apps, schema_editor)
    revert_0038_fields(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0038_make_countonly_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='agent1',
            field=models.ForeignKey(db_column='Agent1ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent2',
            field=models.ForeignKey(db_column='Agent2ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent3',
            field=models.ForeignKey(db_column='Agent3ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent4',
            field=models.ForeignKey(db_column='Agent4ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='gift',
            name='agent5',
            field=models.ForeignKey(db_column='Agent5ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent1',
            field=models.ForeignKey(db_column='Agent1ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent2',
            field=models.ForeignKey(db_column='Agent2ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent3',
            field=models.ForeignKey(db_column='Agent3ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent4',
            field=models.ForeignKey(db_column='Agent4ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='agent5',
            field=models.ForeignKey(db_column='Agent5ID', null=True, on_delete=protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.RunPython(
            consolidated_0038_forward,
            consolidated_0038_backward,
            atomic=True,
        ),
    ]