# Generated by Django 4.2.24 on 2025-10-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0040_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='date1precision',
            field=models.SmallIntegerField(blank=True, db_column='Date1Precision', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='date2precision',
            field=models.SmallIntegerField(blank=True, db_column='Date2Precision', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='dateaccessionedprecision',
            field=models.SmallIntegerField(blank=True, db_column='DateAccessionedPrecision', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='dateacknowledgedprecision',
            field=models.SmallIntegerField(blank=True, db_column='DateAcknowledgedPrecision', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='datereceivedprecision',
            field=models.SmallIntegerField(blank=True, db_column='DateReceivedPrecision', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.AutoField(db_column='componentid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='identifieddate',
            field=models.DateTimeField(blank=True, db_column='IdentifiedDate', null=True),
        ),
        migrations.AlterField(
            model_name='taxontreedefitem',
            name='parent',
            field=models.ForeignKey(db_column='ParentItemID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='specify.taxontreedefitem'),
        ),
    ]
