# Generated by Django 4.2.24 on 2026-01-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0043_normalize_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='division',
            field=models.ForeignKey(db_column='DivisionID', on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='specify.division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='institution',
            field=models.ForeignKey(db_column='InstitutionID', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='specify.institution'),
        ),
        migrations.AlterField(
            model_name='geographytreedef',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographytreedefs', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='geologictimeperiodtreedef',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geologictimeperiodtreedefs', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='lithostrattreedef',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lithostratstreedefs', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='collection',
            field=models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, related_name='picklists', to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='spappresourcedir',
            name='collection',
            field=models.ForeignKey(db_column='CollectionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='spappresourcedir',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='spexportschema',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', on_delete=django.db.models.deletion.CASCADE, related_name='spexportschemas', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='splocalecontainer',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', on_delete=django.db.models.deletion.CASCADE, related_name='splocalecontainers', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='splocalecontaineritem',
            name='container',
            field=models.ForeignKey(db_column='SpLocaleContainerID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='specify.splocalecontainer'),
        ),
        migrations.AlterField(
            model_name='splocaleitemstr',
            name='containerdesc',
            field=models.ForeignKey(db_column='SpLocaleContainerDescID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descs', to='specify.splocalecontainer'),
        ),
        migrations.AlterField(
            model_name='splocaleitemstr',
            name='containername',
            field=models.ForeignKey(db_column='SpLocaleContainerNameID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='specify.splocalecontainer'),
        ),
        migrations.AlterField(
            model_name='splocaleitemstr',
            name='itemdesc',
            field=models.ForeignKey(db_column='SpLocaleContainerItemDescID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descs', to='specify.splocalecontaineritem'),
        ),
        migrations.AlterField(
            model_name='splocaleitemstr',
            name='itemname',
            field=models.ForeignKey(db_column='SpLocaleContainerItemNameID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='specify.splocalecontaineritem'),
        ),
        migrations.AlterField(
            model_name='sptasksemaphore',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='storagetreedef',
            name='institution',
            field=models.ForeignKey(db_column='InstitutionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storagetreedefs', to='specify.institution'),
        ),
        migrations.AlterField(
            model_name='taxontreedef',
            name='createdbyagent',
            field=models.ForeignKey(db_column='CreatedByAgentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specify.agent'),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedef',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tectonicunittreedefs', to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='collectionobjecttype',
            name='collection',
            field=models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, related_name='cotypes', to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='preptype',
            name='collection',
            field=models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, related_name='preptypes', to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='collectionobjectgrouptype',
            name='collection',
            field=models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, related_name='cogtypes', to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='taxontreedefitem',
            name='parent',
            field=models.ForeignKey(db_column='ParentItemID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specify.taxontreedefitem'),
        ),
    ]
