# Generated by Django 4.2.27 on 2026-01-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0043_alter_deletion_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionobjectgrouptype',
            name='collection',
            field=models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, related_name='cogtypes', to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='definition',
            field=models.ForeignKey(db_column='GeographyTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.geographytreedef'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='definitionitem',
            field=models.ForeignKey(db_column='GeographyTreeDefItemID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.geographytreedefitem'),
        ),
        migrations.AlterField(
            model_name='geologictimeperiod',
            name='definition',
            field=models.ForeignKey(db_column='GeologicTimePeriodTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.geologictimeperiodtreedef'),
        ),
        migrations.AlterField(
            model_name='geologictimeperiod',
            name='definitionitem',
            field=models.ForeignKey(db_column='GeologicTimePeriodTreeDefItemID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.geologictimeperiodtreedefitem'),
        ),
    ]
