# Generated by Django 5.2.13 on 2026-04-30

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('specify', '0044_alter_deletion_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonumberingscheme',
            name='collections',
            field=models.ManyToManyField(related_name='numberingschemes', through='specify.Autonumschcoll', through_fields=('autonumberingscheme', 'collection'), to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='autonumberingscheme',
            name='disciplines',
            field=models.ManyToManyField(related_name='numberingschemes', through='specify.Autonumschdsp', through_fields=('autonumberingscheme', 'discipline'), to='specify.discipline'),
        ),
        migrations.AlterField(
            model_name='autonumberingscheme',
            name='divisions',
            field=models.ManyToManyField(related_name='numberingschemes', through='specify.Autonumschdiv', through_fields=('autonumberingscheme', 'division'), to='specify.division'),
        ),
        migrations.AlterField(
            model_name='project',
            name='collectionobjects',
            field=models.ManyToManyField(related_name='projects', through='specify.Project_colobj', through_fields=('project', 'collectionobject'), to='specify.collectionobject'),
        ),
        migrations.AlterField(
            model_name='specifyuser',
            name='spprincipals',
            field=models.ManyToManyField(related_name='specifyusers', through='specify.Specifyuser_spprincipal', through_fields=('specifyuser', 'spprincipal'), to='specify.spprincipal'),
        ),
        migrations.AlterField(
            model_name='spexportschema',
            name='mappings',
            field=models.ManyToManyField(related_name='spexportschemas', through='specify.Spexportschema_exportmapping', through_fields=('spexportschema', 'spexportschemamapping'), to='specify.spexportschemamapping'),
        ),
        migrations.AlterField(
            model_name='spprincipal',
            name='sppermissions',
            field=models.ManyToManyField(related_name='spprincipals', through='specify.Spprincipal_sppermission', through_fields=('spprincipal', 'sppermission'), to='specify.sppermission'),
        ),
    ]
