# Generated by Django 4.2.27 on 2026-03-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0044_alter_deletion_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='spqueryfield',
            name='isstatic',
            field=models.BooleanField(blank=True, db_column='IsStatic', default=False, null=True),
        ),
        migrations.AddField(
            model_name='spqueryfield',
            name='staticvalue',
            field=models.TextField(blank=True, db_column='StaticValue', null=True),
        ),
        migrations.AddField(
            model_name='spqueryfield',
            name='term',
            field=models.CharField(blank=True, db_column='Term', max_length=255, null=True),
        ),
    ]
