# Generated by Django 4.2.30 on 2026-06-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0044_alter_deletion_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifyuser',
            name='spprincipals',
            field=models.ManyToManyField(related_name='specifyusers', through='specify.Specifyuser_spprincipal', to='specify.spprincipal'),
        ),
    ]
