# Generated by Django 4.2.27 on 2026-04-01 08:02

from django.db import migrations, models
from specifyweb.specify.migration_utils import update_schema_config as usc
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0044_alter_deletion_cascade'),
    ]

    def apply_migration(apps, schema_editor):
        usc.create_establishmentmeans_picklist(apps, schema_editor)
        usc.create_eventtype_picklist(apps, schema_editor)
        usc.create_basisofrecord_picklist(apps, schema_editor)
        usc.create_attachmenttype_picklist(apps, schema_editor)
        usc.create_institutionlicense_picklist(apps, schema_editor)
        usc.update_schema_config_fields(apps, schema_editor)
    
    def revert_migration(apps, schema_editor):
        usc.revert_establishmentmeans_picklist(apps)
        usc.revert_eventtype_picklist(apps)
        usc.revert_basisofrecord_picklist(apps)
        usc.revert_attachmenttype_picklist(apps)
        usc.revert_institutionlicense_picklist(apps)
        usc.revert_update_schema_config_fields(apps)

    operations = [
        migrations.AddField(
            model_name='collectionobject',
            name='disposition',
            field=models.CharField(blank=True, db_column='Disposition', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionobject',
            name='establishmentmeans',
            field=models.CharField(blank=True, db_column='EstablishmentMeans', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionobjectattribute',
            name='lifestage',
            field=models.CharField(blank=True, db_column='LifeStage', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionobjectattribute',
            name='sex',
            field=models.CharField(blank=True, db_column='Sex', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionobjectattribute',
            name='behavior',
            field=models.CharField(blank=True, db_column='Behavior', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectingevent',
            name='associatedtaxa',
            field=models.CharField(blank=True, db_column='AssociatedTaxa', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectingevent',
            name='eventtype',
            field=models.CharField(blank=True, db_column='EventType', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectingevent',
            name='habitat',
            field=models.CharField(blank=True, db_column='Habitat', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='basisofrecord',
            field=models.CharField(blank=True, db_column='BasisOfRecord', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localitydetail',
            name='verbatimdepth',
            field=models.CharField(blank=True, db_column='VerbatimDepth', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='determination',
            name='identificationverificationstatus',
            field=models.CharField(blank=True, db_column='IdentificationVerificationStatus', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='preparation',
            name='disposition',
            field=models.CharField(blank=True, db_column='Disposition', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='rightsholder',
            field=models.CharField(blank=True, db_column='RightsHolder', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='datasetname',
            field=models.CharField(blank=True, db_column='DatasetName', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='coordinateprecision',
            field=models.CharField(blank=True, db_column='CoordinatePrecision', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='footprintspatialfit',
            field=models.DecimalField(blank=True, db_column='FootprintSpatialFit', decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='footprintsrs',
            field=models.CharField(blank=True, db_column='FootprintSRS', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='footprintwkt',
            field=models.CharField(blank=True, db_column='FootprintWKT', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locationaccordingto',
            field=models.ForeignKey(db_column='LocationAccordingToID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AddField(
            model_name='locality',
            name='verbatimcoordinates',
            field=models.CharField(blank=True, db_column='VerbatimCoordinates', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='verbatimsrs',
            field=models.CharField(blank=True, db_column='VerbatimSRS', max_length=64, null=True),
        ),
        migrations.RunPython(
            apply_migration,
            revert_migration,
            atomic=True,
        ),
    ]
