# Generated by Django 4.2.27 on 2026-04-01 08:02

from django.db import migrations, models
from specifyweb.specify.migration_utils import update_schema_config as usc


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0044_alter_deletion_cascade'),
    ]

    def apply_migration(apps, schema_editor):
        usc.create_establishmentmeans_picklist(apps, schema_editor)
        usc.create_eventtype_picklist(apps, schema_editor)
        usc.update_schema_config_fields(apps, schema_editor)
    
    def revert_migration(apps, schema_editor):
        usc.revert_establishmentmeans_picklist(apps)
        usc.revert_eventtype_picklist(apps)
        usc.revert_update_schema_config_fields(apps)

    operations = [
        migrations.AddField(
            model_name='collectionobject',
            name='disposition',
            field=models.CharField(blank=True, db_column='Disposition', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionobject',
            name='establishmentmeans',
            field=models.CharField(blank=True, db_column='EstablishmentMeans', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionobjectattribute',
            name='lifestage',
            field=models.CharField(blank=True, db_column='LifeStage', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionobjectattribute',
            name='sex',
            field=models.CharField(blank=True, db_column='Sex', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectingevent',
            name='associatedtaxa',
            field=models.CharField(blank=True, db_column='AssociatedTaxa', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectingevent',
            name='eventtype',
            field=models.CharField(blank=True, db_column='EventType', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectingevent',
            name='habitat',
            field=models.CharField(blank=True, db_column='Habitat', max_length=64, null=True),
        ),
        migrations.RunPython(
            apply_migration,
            revert_migration,
            atomic=True,
        ),
    ]
