# Generated by Django 4.2.27 on 2026-03-31 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0044_alter_deletion_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemamapping',
            fields=[
                ('id', models.AutoField(db_column='schemamappingid', primary_key=True, serialize=False)),
                ('mapping_type', models.CharField(db_column='MappingType', max_length=16)),
                ('name', models.CharField(db_column='Name', max_length=256)),
                ('is_default', models.BooleanField(db_column='IsDefault', default=False)),
                ('createdbyagent', models.ForeignKey(db_column='CreatedByAgentID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.agent')),
                ('modifiedbyagent', models.ForeignKey(db_column='ModifiedByAgentID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.agent')),
                ('query', models.OneToOneField(db_column='queryid', on_delete=django.db.models.deletion.CASCADE, related_name='schemamapping', to='specify.spquery')),
                ('specifyuser', models.ForeignKey(db_column='SpecifyUserID', on_delete=specifyweb.specify.models.protect_with_blockers, related_name='schemamappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schemamapping',
                'ordering': (),
                'indexes': [models.Index(fields=['name'], name='SchemaMappingNameIDX')],
            },
        ),
    ]
