# Generated by Django 4.2.27 on 2026-01-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0044_alter_collectionobjectgrouptype_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographytreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='GeographyTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treedefitems', to='specify.geographytreedef'),
        ),
        migrations.AlterField(
            model_name='geologictimeperiodtreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='GeologicTimePeriodTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treedefitems', to='specify.geologictimeperiodtreedef'),
        ),
        migrations.AlterField(
            model_name='storagetreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='StorageTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treedefitems', to='specify.storagetreedef'),
        ),
    ]
