# Generated by Django 4.2.27 on 2026-01-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0045_alter_geographytreedefitem_treedef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='geographytreedef',
            field=models.ForeignKey(db_column='GeographyTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='specify.geographytreedef'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='geologictimeperiodtreedef',
            field=models.ForeignKey(db_column='GeologicTimePeriodTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='specify.geologictimeperiodtreedef'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='lithostrattreedef',
            field=models.ForeignKey(db_column='LithoStratTreeDefID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='specify.lithostrattreedef'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='taxontreedef',
            field=models.ForeignKey(db_column='TaxonTreeDefID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='specify.taxontreedef'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='tectonicunittreedef',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='specify.tectonicunittreedef'),
        ),
    ]
