# Generated by Django 4.2.27 on 2026-03-31 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0045_create_schemamapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportdataset',
            fields=[
                ('id', models.AutoField(db_column='ExportDatasetID', primary_key=True, serialize=False)),
                ('exportname', models.CharField(db_column='ExportName', max_length=255, unique=True)),
                ('filename', models.CharField(db_column='FileName', max_length=255, unique=True)),
                ('rss', models.BooleanField(blank=True, db_column='RSS', default=False, null=True)),
                ('frequency', models.IntegerField(blank=True, db_column='Frequency', null=True)),
                ('timestampcreated', models.DateTimeField(db_column='TimestampCreated', default=django.utils.timezone.now)),
                ('timestampmodified', models.DateTimeField(blank=True, db_column='TimestampModified', default=django.utils.timezone.now, null=True)),
                ('lastexported', models.DateTimeField(blank=True, db_column='LastExported', null=True)),
                ('collection', models.ForeignKey(db_column='CollectionID', on_delete=specifyweb.specify.models.protect_with_blockers, related_name='exportdatasets', to='specify.collection')),
                ('metadata', models.ForeignKey(db_column='MetadataID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportdatasets', to='specify.spappresource')),
                ('coremapping', models.ForeignKey(db_column='CoreMappingID', related_name='exportdatasets', null=False, on_delete=specifyweb.specify.models.protect_with_blockers, to='specify.schemamapping')),
            ],
            options={
                'db_table': 'exportdataset',
                'ordering': (),
                'indexes': [models.Index(fields=['exportname'], name='ExportNameIDX'), models.Index(fields=['filename'], name='FileNameIDX'), models.Index(fields=['collection'], name='ExportDatasetCollectionIDX')],
            },
        ),
    ]
