# Generated by Django 4.2.27 on 2026-01-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0046_alter_discipline_geographytreedef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithostrat',
            name='definition',
            field=models.ForeignKey(db_column='LithoStratTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.lithostrattreedef'),
        ),
        migrations.AlterField(
            model_name='lithostrat',
            name='definitionitem',
            field=models.ForeignKey(db_column='LithoStratTreeDefItemID', on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.lithostrattreedefitem'),
        ),
        migrations.AlterField(
            model_name='lithostrattreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='LithoStratTreeDefID', on_delete=django.db.models.deletion.CASCADE, related_name='treedefitems', to='specify.lithostrattreedef'),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='definition',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.tectonicunittreedef'),
        ),
        migrations.AlterField(
            model_name='tectonicunit',
            name='definitionitem',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefItemID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeentries', to='specify.tectonicunittreedefitem'),
        ),
        migrations.AlterField(
            model_name='tectonicunittreedefitem',
            name='treedef',
            field=models.ForeignKey(db_column='TectonicUnitTreeDefID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treedefitems', to='specify.tectonicunittreedef'),
        ),
    ]
