# Generated by Django 4.2.24 on 2026-07-29

from django.db import migrations, models
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0047_alter_many_to_many_through_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxontreedefitem',
            name='parent',
            field=models.ForeignKey(
                db_column='ParentItemID',
                null=True,
                on_delete=specifyweb.specify.models.delete_taxon_rank_parent_with_context,
                related_name='children',
                to='specify.taxontreedefitem',
            ),
        ),
    ]
