# Generated by Django 4.2.27 on 2026-01-13 15:38

from django.db import migrations, models
import django.db.models.deletion
import specifyweb.specify.models


class Migration(migrations.Migration):

    dependencies = [
        ('specify', '0047_alter_lithostrat_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxontreedef',
            name='createdbyagent',
            field=models.ForeignKey(db_column='CreatedByAgentID', null=True, on_delete=specifyweb.specify.models.protect_with_blockers, related_name='+', to='specify.agent'),
        ),
        migrations.AlterField(
            model_name='taxontreedef',
            name='discipline',
            field=models.ForeignKey(db_column='DisciplineID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxontreedefs', to='specify.discipline'),
        ),
    ]
