simple_query = {
    "id": 57,
    "contextname": "CollectionObject",
    "contexttableid": 1,
    "countonly": False,
    "formatauditrecids": False,
    "isfavorite": True,
    "name": "New Query",
    "ordinal": 32767,
    "remarks": None,
    "searchsynonymy": None,
    "selectdistinct": False,
    "smushed": None,
    "sqlstr": None,
    "timestampcreated": "2025-04-01T16:17:39",
    "timestampmodified": "2025-04-01T16:22:51",
    "version": 1,
    "createdbyagent": "/api/specify/agent/3/",
    "modifiedbyagent": "/api/specify/agent/3/",
    "specifyuser": "/api/specify/specifyuser/1/",
    "fields": [
        {
            "id": 1344,
            "allownulls": None,
            "alwaysfilter": None,
            "columnalias": None,
            "contexttableident": None,
            "endvalue": None,
            "fieldname": "catalogNumber",
            "formatname": None,
            "isdisplay": True,
            "isnot": False,
            "isprompt": None,
            "isrelfld": False,
            "operend": None,
            "operstart": 8,
            "position": 0,
            "sorttype": 0,
            "startvalue": "",
            "stringid": "1.collectionobject.catalogNumber",
            "tablelist": "1",
            "timestampcreated": "2025-04-01T16:22:51",
            "timestampmodified": "2025-04-01T16:22:51",
            "version": 0,
            "isstrict": None,
            "createdbyagent": "/api/specify/agent/3/",
            "modifiedbyagent": None,
            "query": "/api/specify/spquery/57/",
            "mappings": "/api/specify/spexportschemaitemmapping/?queryfield=1344",
            "resource_uri": "/api/specify/spqueryfield/1344/",
        },
    ],
    "reports": "/api/specify/spreport/?query=57",
    "resource_uri": "/api/specify/spquery/57/",
}
