from specifyweb.stored_queries.tests.tests import SQLAlchemySetup


class TestKMLContext(SQLAlchemySetup):

    def no_locality_fields(self): ...

    def direct_locality_fields(self): ...

    def to_many_locality_fields(self): ...

    def to_one_locality_fields(self): ...
