# Generated by Django 2.2.10 on 2022-03-04 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specify', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=1024)),
                ('action', models.CharField(max_length=1024)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specify.Collection')),
                ('specifyuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spuserpolicy',
            },
        ),
    ]
