# Generated by Django 2.2.10 on 2022-03-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_role_rolepolicy_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'splibraryrole',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rolepolicy',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='permissions.Role'),
        ),
        migrations.CreateModel(
            name='LibraryRolePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=1024)),
                ('action', models.CharField(max_length=1024)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='permissions.LibraryRole')),
            ],
            options={
                'db_table': 'splibraryrolepolicy',
            },
        ),
    ]
