# Generated by Django 2.2.10 on 2022-04-07 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20220321_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='specifyuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
