# Generated by Django 2.2.10 on 2022-04-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_intialize_defaults'),
        ('permissions', '0004_auto_20220407_1927'),
    ]

    operations = [] # type: ignore
