# Generated by Django 2.2.10 on 2022-04-13 16:20

from django.db import migrations

def initialize(apps, schema_editor):
    from specifyweb.permissions.initialize import initialize as init
    init(wipe=True, apps=apps)

class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20220321_1445'),
    ]

    operations = [
        migrations.RunPython(initialize),
    ]
