from specifyweb.specify.migration_utils.schema_writer import update_table_field_schema_config_params

# ##########################################
# Used in 0035_version_required.py
# ##########################################

MIGRATION_0035_FIELDS = {
    'AbsoluteAge': ['version'],
    'AbsoluteAgeAttachment': ['version'],
    'AbsoluteAgeCitation': ['version'],
    'Accession': ['version'],
    'AccessionAgent': ['version'],
    'AccessionAttachment': ['version'],
    'AccessionAuthorization': ['version'],
    'AccessionCitation': ['version'],
    'Address': ['version'],
    'AddressOfRecord': ['version'],
    'Agent': ['version'],
    'AgentAttachment': ['version'],
    'AgentGeography': ['version'],
    'AgentIdentifier': ['version'],
    'AgentSpecialty': ['version'],
    'AgentVariant': ['version'],
    'Appraisal': ['version'],
    'Attachment': ['version'],
    'AttachmentImageAttribute': ['version'],
    'AttachmentMetadata': ['version'],
    'AttachmentTag': ['version'],
    'AttributeDef': ['version'],
    'Author': ['version'],
    'AutoNumberingScheme': ['version'],
    'Borrow': ['version'],
    'BorrowAgent': ['version'],
    'BorrowAttachment': ['version'],
    'BorrowMaterial': ['version'],
    'BorrowReturnMaterial': ['version'],
    'CollectingEvent': ['version'],
    'CollectingEventAttachment': ['version'],
    'CollectingEventAttr': ['version'],
    'CollectingEventAttribute': ['version'],
    'CollectingEventAuthorization': ['version'],
    'CollectingTrip': ['version'],
    'CollectingTripAttachment': ['version'],
    'CollectingTripAttribute': ['version'],
    'CollectingTripAuthorization': ['version'],
    'Collection': ['version'],
    'CollectionObject': ['version'],
    'CollectionObjectAttachment': ['version'],
    'CollectionObjectAttr': ['version'],
    'CollectionObjectAttribute': ['version'],
    'CollectionObjectCitation': ['version'],
    'CollectionObjectGroup': ['version'],
    'CollectionObjectGroupJoin': ['version'],
    'CollectionObjectGroupType': ['version'],
    'CollectionObjectProperty': ['version'],
    'CollectionObjectType': ['version'],
    'CollectionRelationship': ['version'],
    'CollectionRelType': ['version'],
    'Collector': ['version'],
    'CommonNameTx': ['version'],
    'CommonNameTxCitation': ['version'],
    'ConservDescription': ['version'],
    'ConservDescriptionAttachment': ['version'],
    'ConservEvent': ['version'],
    'ConservEventAttachment': ['version'],
    'Container': ['version'],
    'DataType': ['version'],
    'Deaccession': ['version'],
    'DeaccessionAgent': ['version'],
    'DeaccessionAttachment': ['version'],
    'Determination': ['version'],
    'DeterminationCitation': ['version'],
    'Determiner': ['version'],
    'Discipline': ['version'],
    'Disposal': ['version'],
    'DisposalAgent': ['version'],
    'DisposalAttachment': ['version'],
    'DisposalPreparation': ['version'],
    'Division': ['version'],
    'DnaPrimer': ['version'],
    'DnaSequence': ['version'],
    'DnaSequenceAttachment': ['version'],
    'DnaSequencingRun': ['version'],
    'DnaSequencingRunAttachment': ['version'],
    'DnaSequencingRunCitation': ['version'],
    'ExchangeIn': ['version'],
    'ExchangeInAttachment': ['version'],
    'ExchangeInPrep': ['version'],
    'ExchangeOut': ['version'],
    'ExchangeOutAttachment': ['version'],
    'ExchangeOutPrep': ['version'],
    'Exsiccata': ['version'],
    'ExsiccataItem': ['version'],
    'Extractor': ['version'],
    'FieldNotebook': ['version'],
    'FieldNotebookAttachment': ['version'],
    'FieldNotebookPage': ['version'],
    'FieldNotebookPageAttachment': ['version'],
    'FieldNotebookPageSet': ['version'],
    'FieldNotebookPageSetAttachment': ['version'],
    'FundingAgent': ['version'],
    'GeoCoordDetail': ['version'],
    'Geography': ['version'],
    'GeographyTreeDef': ['version'],
    'GeographyTreeDefItem': ['version'],
    'GeologicTimePeriod': ['version'],
    'GeologicTimePeriodTreeDef': ['version'],
    'GeologicTimePeriodTreeDefItem': ['version'],
    'Gift': ['version'],
    'GiftAgent': ['version'],
    'GiftAttachment': ['version'],
    'GiftPreparation': ['version'],
    'GroupPerson': ['version'],
    'InfoRequest': ['version'],
    'Institution': ['version'],
    'InstitutionNetwork': ['version'],
    'Journal': ['version'],
    'LatLonPolygon': ['version'],
    'LithoStrat': ['version'],
    'LithoStratTreeDef': ['version'],
    'LithoStratTreeDefItem': ['version'],
    'Loan': ['version'],
    'LoanAgent': ['version'],
    'LoanAttachment': ['version'],
    'LoanPreparation': ['version'],
    'LoanReturnPreparation': ['version'],
    'Locality': ['version'],
    'LocalityAttachment': ['version'],
    'LocalityCitation': ['version'],
    'LocalityDetail': ['version'],
    'LocalityNameAlias': ['version'],
    'MaterialSample': ['version'],
    'MorphbankView': ['version'],
    'OtherIdentifier': ['version'],
    'PaleoContext': ['version'],
    'PcrPerson': ['version'],
    'Permit': ['version'],
    'PermitAttachment': ['version'],
    'PickList': ['version'],
    'PickListItem': ['version'],
    'Preparation': ['version'],
    'PreparationAttachment': ['version'],
    'PreparationAttr': ['version'],
    'PreparationAttribute': ['version'],
    'PreparationProperty': ['version'],
    'PrepType': ['version'],
    'Project': ['version'],
    'Recordset': ['version'],
    'ReferenceWork': ['version'],
    'ReferenceWorkAttachment': ['version'],
    'RelativeAge': ['version'],
    'RelativeAgeAttachment': ['version'],
    'RelativeAgeCitation': ['version'],
    'RepositoryAgreement': ['version'],
    'RepositoryAgreementAttachment': ['version'],
    'Shipment': ['version'],
    'SpAppResource': ['version'],
    'SpAppResourceData': ['version'],
    'SpAppResourceDir': ['version'],
    'SpAuditLog': ['version'],
    'SpAuditLogField': ['version'],
    'SpecifyUser': ['version'],
    'SpExportSchema': ['version'],
    'SpExportSchemaItem': ['version'],
    'SpExportSchemaItemMapping': ['version'],
    'SpExportSchemaMapping': ['version'],
    'SpFieldValueDefault': ['version'],
    'SpLocaleContainer': ['version'],
    'SpLocaleContainerItem': ['version'],
    'SpLocaleItemStr': ['version'],
    'SpPrincipal': ['version'],
    'SpQuery': ['version'],
    'SpQueryField': ['version'],
    'SpReport': ['version'],
    'SpSymbiotaInstance': ['version'],
    'SpTaskSemaphore': ['version'],
    'SpVersion': ['version'],
    'SpViewSetObj': ['version'],
    'SpVisualQuery': ['version'],
    'Storage': ['version'],
    'StorageAttachment': ['version'],
    'StorageTreeDef': ['version'],
    'StorageTreeDefItem': ['version'],
    'Taxon': ['version'],
    'TaxonAttachment': ['version'],
    'TaxonAttribute': ['version'],
    'TaxonCitation': ['version'],
    'TaxonTreeDef': ['version'],
    'TaxonTreeDefItem': ['version'],
    'TectonicUnit': ['version'],
    'TectonicUnitTreeDef': ['version'],
    'TectonicUnitTreeDefItem': ['version'],
    'TreatmentEvent': ['version'],
    'TreatmentEventAttachment': ['version'],
    'VoucherRelationship': ['version'],
    'Workbench': ['version'],
    'WorkbenchRowExportedRelationship': ['version'],
    'WorkbenchTemplate': ['version'],
    'WorkbenchTemplateMappingItem': ['version'],
}

def update_version_required(apps):
    Discipline = apps.get_model('specify', 'Discipline')
    updated_config_params = {
        'isrequired': False,
    }

    # Update the schema config for each discipline with the version isHidden change
    for discipline in Discipline.objects.all():
        for table, fields in MIGRATION_0035_FIELDS.items():
            for field in fields:    
                update_table_field_schema_config_params(table, discipline.id, field, updated_config_params, apps)

def revert_version_required(apps):
    Discipline = apps.get_model('specify', 'Discipline')
    updated_config_params = {
        'isrequired': True,
    }

    # Revert the schema config for each discipline with the version isHidden change
    for discipline in Discipline.objects.all():
        for table, fields in MIGRATION_0035_FIELDS.items():
            for field in fields:    
                update_table_field_schema_config_params(table, discipline.id, field, updated_config_params, apps)
