CREATE TABLE `borrowattachment` (
  `BorrowAttachmentID` int(11) NOT NULL AUTO_INCREMENT,
  `TimestampCreated` datetime NOT NULL,
  `TimestampModified` datetime DEFAULT NULL,
  `Version` int(11) DEFAULT NULL,
  `Ordinal` int(11) DEFAULT NULL,
  `Remarks` text,
  `CreatedByAgentID` int(11) DEFAULT NULL,
  `AttachmentID` int(11) NOT NULL,
  `BorrowID` int(11) NOT NULL,
  `ModifiedByAgentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`BorrowAttachmentID`),
  KEY `FK3263D4D87699B003` (`CreatedByAgentID`),
  KEY `FK3263D4D8C7E55084` (`AttachmentID`),
  KEY `FK3263D4D85327F942` (`ModifiedByAgentID`),
  KEY `FK3263D4D8F8BF6F28` (`BorrowID`),
  CONSTRAINT `FK3263D4D85327F942` FOREIGN KEY (`ModifiedByAgentID`) REFERENCES `agent` (`AgentID`),
  CONSTRAINT `FK3263D4D87699B003` FOREIGN KEY (`CreatedByAgentID`) REFERENCES `agent` (`AgentID`),
  CONSTRAINT `FK3263D4D8C7E55084` FOREIGN KEY (`AttachmentID`) REFERENCES `attachment` (`AttachmentID`),
  CONSTRAINT `FK3263D4D8F8BF6F28` FOREIGN KEY (`BorrowID`) REFERENCES `borrow` (`BorrowID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `giftattachment` (
  `GiftAttachmentID` int(11) NOT NULL AUTO_INCREMENT,
  `TimestampCreated` datetime NOT NULL,
  `TimestampModified` datetime DEFAULT NULL,
  `Version` int(11) DEFAULT NULL,
  `Ordinal` int(11) DEFAULT NULL,
  `Remarks` text,
  `CreatedByAgentID` int(11) DEFAULT NULL,
  `AttachmentID` int(11) NOT NULL,
  `ModifiedByAgentID` int(11) DEFAULT NULL,
  `GiftID` int(11) NOT NULL,
  PRIMARY KEY (`GiftAttachmentID`),
  KEY `FKC75A06539890879E` (`GiftID`),
  KEY `FKC75A06537699B003` (`CreatedByAgentID`),
  KEY `FKC75A0653C7E55084` (`AttachmentID`),
  KEY `FKC75A06535327F942` (`ModifiedByAgentID`),
  CONSTRAINT `FKC75A06535327F942` FOREIGN KEY (`ModifiedByAgentID`) REFERENCES `agent` (`AgentID`),
  CONSTRAINT `FKC75A06537699B003` FOREIGN KEY (`CreatedByAgentID`) REFERENCES `agent` (`AgentID`),
  CONSTRAINT `FKC75A06539890879E` FOREIGN KEY (`GiftID`) REFERENCES `gift` (`GiftID`),
  CONSTRAINT `FKC75A0653C7E55084` FOREIGN KEY (`AttachmentID`) REFERENCES `attachment` (`AttachmentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `referenceworkattachment` (
  `ReferenceWorkAttachmentID` int(11) NOT NULL AUTO_INCREMENT,
  `TimestampCreated` datetime NOT NULL,
  `TimestampModified` datetime DEFAULT NULL,
  `Version` int(11) DEFAULT NULL,
  `Ordinal` int(11) DEFAULT NULL,
  `Remarks` text,
  `CreatedByAgentID` int(11) DEFAULT NULL,
  `ReferenceWorkID` int(11) NOT NULL,
  `ModifiedByAgentID` int(11) DEFAULT NULL,
  `AttachmentID` int(11) NOT NULL,
  PRIMARY KEY (`ReferenceWorkAttachmentID`),
  KEY `FK9C9B5EFF7699B003` (`CreatedByAgentID`),
  KEY `FK9C9B5EFF69734F30` (`ReferenceWorkID`),
  KEY `FK9C9B5EFFC7E55084` (`AttachmentID`),
  KEY `FK9C9B5EFF5327F942` (`ModifiedByAgentID`),
  CONSTRAINT `FK9C9B5EFF5327F942` FOREIGN KEY (`ModifiedByAgentID`) REFERENCES `agent` (`AgentID`),
  CONSTRAINT `FK9C9B5EFF69734F30` FOREIGN KEY (`ReferenceWorkID`) REFERENCES `referencework` (`ReferenceWorkID`),
  CONSTRAINT `FK9C9B5EFF7699B003` FOREIGN KEY (`CreatedByAgentID`) REFERENCES `agent` (`AgentID`),
  CONSTRAINT `FK9C9B5EFFC7E55084` FOREIGN KEY (`AttachmentID`) REFERENCES `attachment` (`AttachmentID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
