# Generated by Django 3.2.15 on 2023-11-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specify', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniquenessRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDatabaseConstraint', models.BooleanField(db_column='isDatabaseConstraint', default=False)),
                ('discipline', models.ForeignKey(db_column='DisciplineID', on_delete=django.db.models.deletion.PROTECT, to='specify.discipline')),
            ],
            options={
                'db_table': 'uniquenessrule',
            },
        ),
        migrations.CreateModel(
            name='UniquenessRule_Splocalecontaineritem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isScope', models.BooleanField(default=False)),
                ('splocalecontaineritem', models.ForeignKey(blank=True, db_column='splocalecontaineritemid', null=True, on_delete=django.db.models.deletion.PROTECT, to='specify.splocalecontaineritem')),
                ('uniquenessrule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessrules.uniquenessrule')),
            ],
            options={
                'db_table': 'uniquenessrule_splocalecontaineritem',
            },
        ),
        migrations.AddField(
            model_name='uniquenessrule',
            name='splocalecontaineritems',
            field=models.ManyToManyField(related_name='_businessrules_uniquenessrule_splocalecontaineritems_+', through='businessrules.UniquenessRule_Splocalecontaineritem', to='specify.Splocalecontaineritem'),
        ),
    ]
