# Generated by Django 2.2.10 on 2021-12-08 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spuserexternalid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=256)),
                ('providerid', models.CharField(max_length=256)),
                ('specifyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spuserexternalid',
            },
        ),
        migrations.AddConstraint(
            model_name='spuserexternalid',
            constraint=models.UniqueConstraint(fields=('provider', 'providerid'), name='unique_spuser_external_id'),
        ),
    ]
