# Generated by Django 2.2.10 on 2021-12-23 12:06

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spuserexternalid',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spuserexternalid',
            name='idtoken',
            field=models.JSONField(null=True),
        ),
    ]
