# Generated by Django 2.2.10 on 2022-06-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211223_1206'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spuserexternalid',
            name='unique_spuser_external_id',
        ),
    ]
