# Generated by Django 3.2.15 on 2024-05-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_merge_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spmerging',
            old_name='mergingstatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='spmerging',
            name='collection',
            field=models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, to='specify.collection'),
        ),
        migrations.AlterField(
            model_name='spmerging',
            name='specifyuser',
            field=models.ForeignKey(db_column='SpecifyUserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spmerging',
            name="createdbyagent",
            field=models.ForeignKey(null=True, db_column="CreatedByAgentID", on_delete=models.SET_NULL, to='specify.agent', related_name="+")
        ),
        migrations.AlterField(
            model_name='spmerging',
            name="modifiedbyagent",
            field=models.ForeignKey(null=True, db_column="ModifiedByAgentID", on_delete=models.SET_NULL, to='specify.agent', related_name="+")
        )
    ]
