# Generated by Django 3.2.15 on 2024-05-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specify', '__first__'),
        ('notifications', '0005_auto_20240530_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityImport',
            fields=[
                ('id', models.AutoField(db_column='localityimportid', primary_key=True, serialize=False, verbose_name='localityimportid')),
                ('taskid', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('result', models.JSONField(null=True)),
                ('collection', models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, to='specify.collection')),
                ('recordset', models.ForeignKey(blank=True, db_column='RecordSetID', null=True, on_delete=django.db.models.deletion.CASCADE, to='specify.recordset')),
                ('specifyuser', models.ForeignKey(db_column='SpecifyUserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('createdbyagent', models.ForeignKey(db_column='CreatedByAgentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='specify.agent')),
                ('modifiedbyagent', models.ForeignKey(db_column='ModifiedByAgentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='specify.agent')),
                ('timestampcreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestampmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'localityimport',
            },
        ),
    ]
