# Generated by Django 3.2.15 on 2024-06-13 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_localityimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityImportRowResult',
            fields=[
                ('id', models.AutoField(db_column='LocalityImportRowResultID',
                 primary_key=True, serialize=False, verbose_name='localityimportrowresultid')),
                ('rownumber', models.IntegerField()),
                ('result', models.JSONField()),
                ('localityimport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='results', to='notifications.localityimport')),
            ],
            options={
                'db_table': 'localityimportrowresult',
            },
        ),
    ]
