/**
 * Configuration for what schema tables and fields are accessible in the WB
 *
 * @remarks
 * Replaces the need for separate Workbench Schema like in Specify 6
 *
 * @module
 */

import type { IR, RR } from '../../utils/types';
import { VALUE } from '../../utils/utils';
import type { TableFields } from './helperTypes';
import type { Tables } from './types';

export type TableConfigOverwrite =
  /*
   * Adds a table to the list of common base tables (shown on the base table
   *  selection screen even if "Show Advanced Tables" is not checked
   */
  | 'commonBaseTable'
  /*
   * Remove table from the list of base tables, but still make it available
   *  through relationships
   */
  | 'hidden'
  /*
   * Remove the table, all of it's fields/relationships and all
   *  fields/relationships from any table to this table
   */
  | 'system';

type FieldConfigOverwrite = Partial<{
  readonly accessibility:
    | 'optional' // Makes a required field optional
    | 'required'
    // Removes a field from the mapper (but not from Query Builder)
    | 'readOnly'
    // Hides a field. If it was required, it is made optional
    | 'hidden';

  // Indicates white space should not be ignored in the field
  readonly whiteSpaceSensitive: true;
}>;

const tableOverwrites: Partial<RR<keyof Tables, TableConfigOverwrite>> = {
  Accession: 'commonBaseTable',
  Agent: 'commonBaseTable',
  Borrow: 'commonBaseTable',
  CollectingEvent: 'commonBaseTable',
  CollectionObject: 'commonBaseTable',
  ConservEvent: 'commonBaseTable',
  Container: 'commonBaseTable',
  Deaccession: 'commonBaseTable',
  Determination: 'commonBaseTable',
  DNASequence: 'commonBaseTable',
  ExchangeIn: 'commonBaseTable',
  ExchangeOut: 'commonBaseTable',
  Geography: 'commonBaseTable',
  Gift: 'commonBaseTable',
  Loan: 'commonBaseTable',
  Locality: 'commonBaseTable',
  Permit: 'commonBaseTable',
  Preparation: 'commonBaseTable',
  Storage: 'commonBaseTable',
  Taxon: 'commonBaseTable',
  TreatmentEvent: 'commonBaseTable',
  CollectingEventAttr: 'system',
  CollectionObjectAttr: 'system',
  LatLonPolygonPnt: 'system',
  Collection: 'system',
  Discipline: 'system',
  Division: 'system',
  Institution: 'system',
  Workbench: 'hidden',
  WorkbenchDataItem: 'hidden',
  WorkbenchRow: 'hidden',
  WorkbenchRowExportedRelationship: 'hidden',
  WorkbenchRowImage: 'hidden',
  WorkbenchTemplate: 'hidden',
  WorkbenchTemplateMappingItem: 'hidden',
  SpVisualQuery: 'hidden',
  SpSymbiotaInstance: 'hidden',
  GeographyTreeDef: 'system',
  GeographyTreeDefItem: 'system',
  GeologicTimePeriodTreeDef: 'system',
  GeologicTimePeriodTreeDefItem: 'system',
  LithoStratTreeDef: 'system',
  LithoStratTreeDefItem: 'system',
  StorageTreeDef: 'system',
  StorageTreeDefItem: 'system',
  TaxonTreeDef: 'system',
  TaxonTreeDefItem: 'system',
};

// These field overrides apply to entire front-end
const globalFieldOverrides: {
  readonly [TABLE_NAME in keyof Tables]?: {
    readonly [FIELD_NAME in TableFields<
      Tables[TABLE_NAME]
    >]?: FieldConfigOverwrite;
  };
} & {
  readonly common: IR<FieldConfigOverwrite>;
} = {
  // Common overwrites apply to fields in all tables
  common: {
    timestampCreated: { accessibility: 'readOnly' },
    /**
     * This is read only in default forms, but not in schema config.
     * That causes problems as field is editable in autogenerated view.
     */
    timestampModified: { accessibility: 'readOnly' },
  },
  Attachment: {
    tableID: { accessibility: 'optional' },
  },
  CollectionRelationship: {
    collectionRelType: { accessibility: 'required' },
  },
  CollectionRelType: {
    name: { accessibility: 'required' },
  },
  DNASequence: {
    totalResidues: { accessibility: 'readOnly' },
    compA: { accessibility: 'readOnly' },
    compG: { accessibility: 'readOnly' },
    compC: { accessibility: 'readOnly' },
    compT: { accessibility: 'readOnly' },
    ambiguousResidues: { accessibility: 'readOnly' },
  },
  Taxon: {
    parent: { accessibility: 'required' },
    isAccepted: { accessibility: 'readOnly' },
    acceptedTaxon: { accessibility: 'readOnly' },
    fullName: { accessibility: 'readOnly' },
  },
  Geography: {
    parent: { accessibility: 'required' },
    isAccepted: { accessibility: 'readOnly' },
    acceptedGeography: { accessibility: 'readOnly' },
    fullName: { accessibility: 'readOnly' },
  },
  LithoStrat: {
    parent: { accessibility: 'required' },
    isAccepted: { accessibility: 'readOnly' },
    acceptedLithoStrat: { accessibility: 'readOnly' },
    fullName: { accessibility: 'readOnly' },
  },
  GeologicTimePeriod: {
    parent: { accessibility: 'required' },
    isAccepted: { accessibility: 'readOnly' },
    acceptedGeologicTimePeriod: { accessibility: 'readOnly' },
    fullName: { accessibility: 'readOnly' },
  },
  Storage: {
    parent: { accessibility: 'required' },
    isAccepted: { accessibility: 'readOnly' },
    acceptedStorage: { accessibility: 'readOnly' },
    fullName: { accessibility: 'readOnly' },
  },
  SpecifyUser: {
    isAdmin: { accessibility: 'readOnly' },
    password: { accessibility: 'hidden' },
  },
  TaxonTreeDef: {
    fullNameDirection: { accessibility: 'readOnly' },
  },
  TaxonTreeDefItem: {
    fullNameSeparator: { whiteSpaceSensitive: true },
  },
  GeographyTreeDef: {
    fullNameDirection: { accessibility: 'readOnly' },
  },
  GeographyTreeDefItem: {
    fullNameSeparator: { whiteSpaceSensitive: true },
  },
  StorageTreeDef: {
    fullNameDirection: { accessibility: 'readOnly' },
  },
  StorageTreeDefItem: {
    fullNameSeparator: { whiteSpaceSensitive: true },
  },
  GeologicTimePeriodTreeDef: {
    fullNameDirection: { accessibility: 'readOnly' },
  },
  GeologicTimePeriodTreeDefItem: {
    fullNameSeparator: { whiteSpaceSensitive: true },
  },
  LithoStratTreeDef: {
    fullNameDirection: { accessibility: 'readOnly' },
  },
  LithoStratTreeDefItem: {
    fullNameSeparator: { whiteSpaceSensitive: true },
  },
};

/*
 * All required fields are unhidden, unless they are overwritten to "hidden".
 * ReadOnly relationships are removed.
 *
 * These apply to Query Builder, Workbench, Leaflet and Specify Network
 */
const fieldOverwrites: typeof globalFieldOverrides = {
  common: {
    timestampCreated: { accessibility: 'hidden' },
    timestampModified: { accessibility: 'hidden' },
    createdByAgent: { accessibility: 'hidden' },
    modifiedByAgent: { accessibility: 'hidden' },
    collectionMemberId: { accessibility: 'hidden' },
    rankId: { accessibility: 'hidden' },
    definition: { accessibility: 'hidden' },
    definitionItem: { accessibility: 'hidden' },
    orderNumber: { accessibility: 'hidden' },
    isPrimary: { accessibility: 'hidden' },
    isHybrid: { accessibility: 'hidden' },
    isAccepted: { accessibility: 'hidden' },
    fullName: { accessibility: 'readOnly' },
  },
  Agent: {
    agentType: { accessibility: 'optional' },
  },
  LoanPreparation: {
    isResolved: { accessibility: 'optional' },
  },
  Locality: {
    srcLatLongUnit: { accessibility: 'optional' },
  },
  PrepType: {
    isLoanable: { accessibility: 'readOnly' },
  },
  Determination: {
    preferredTaxon: { accessibility: 'readOnly' },
    isCurrent: { accessibility: 'hidden' },
  },
};

/*
 * Same as fieldOverwrites, but matches with fieldName.endsWith(key),
 *  instead of fieldName===key.
 * endsWithFieldOverwrites are checked against fields in all tables.
 */
const endsWithFieldOverwrites: Partial<
  RR<keyof Tables | 'common', IR<FieldConfigOverwrite>>
> = {
  Attachment: {
    Attachments: { accessibility: 'hidden' },
  },
};

// Overwrite SpecifyTable.view
export const tableViews: Partial<RR<keyof Tables, string>> = {
  SpQuery: 'Query',
};

export const getTableOverwrite = (
  tableName: keyof Tables
): TableConfigOverwrite | undefined => tableOverwrites[tableName];

export const getGlobalFieldOverwrite = (
  tableName: keyof Tables,
  fieldName: string
): FieldConfigOverwrite | undefined =>
  globalFieldOverrides[tableName as 'Accession']?.[fieldName as 'text1'] ??
  globalFieldOverrides.common?.[fieldName];

export const getFieldOverwrite = (
  tableName: keyof Tables,
  fieldName: string
): FieldConfigOverwrite | undefined =>
  fieldOverwrites[tableName as 'Accession']?.[fieldName as 'text1'] ??
  fieldOverwrites.common?.[fieldName] ??
  Object.entries(endsWithFieldOverwrites[tableName] ?? {}).find(([key]) =>
    fieldName.endsWith(key)
  )?.[VALUE] ??
  Object.entries(endsWithFieldOverwrites.common ?? {}).find(([key]) =>
    fieldName.endsWith(key)
  )?.[VALUE];
