import { requireContext } from '../../../tests/helpers';
import { theories } from '../../../tests/utils';
import { localized } from '../../../utils/types';
import { getMappingLineData } from '../navigator';
import { navigatorSpecs } from '../navigatorSpecs';

requireContext();

// TEST: break this test into smaller tests
theories(getMappingLineData, [
  {
    in: [
      {
        baseTableName: 'CollectionObject',
        mappingPath: ['determinations', '#1', 'taxon', '$Family', 'name'],
        showHiddenFields: false,
        generateFieldData: 'all',
        spec: navigatorSpecs.wbPlanView,
      },
    ],
    out: [
      {
        defaultValue: 'determinations',
        customSelectSubtype: 'simple',
        selectLabel: localized('Collection Object'),
        fieldsData: {
          catalogNumber: {
            optionLabel: 'Cat #',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          catalogedDate: {
            optionLabel: 'Cat Date',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          reservedText: {
            optionLabel: 'CT Scan',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          guid: {
            optionLabel: 'GUID',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          leftSideRels: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Left Side Rels',
            tableName: 'CollectionRelationship',
          },
          altCatalogNumber: {
            optionLabel: 'Prev/Exch #',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          projectNumber: {
            optionLabel: 'Project Number',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          remarks: {
            optionLabel: 'Remarks',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          reservedText2: {
            optionLabel: 'Reserved Text2',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          rightSideRels: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Right Side Rels',
            tableName: 'CollectionRelationship',
          },
          fieldNumber: {
            optionLabel: 'Voucher',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          accession: {
            optionLabel: 'Accession #',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'Accession',
          },
          cataloger: {
            optionLabel: 'Cataloger',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'Agent',
          },
          cojo: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Cojo',
            tableName: 'CollectionObjectGroupJoin',
          },
          collectionObjectAttribute: {
            optionLabel: 'Col Obj Attribute',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'CollectionObjectAttribute',
          },
          collectionObjectCitations: {
            optionLabel: 'Collection Object Citations',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'CollectionObjectCitation',
          },
          collectionObjectType: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection Object Type',
            tableName: 'CollectionObjectType',
          },
          determinations: {
            optionLabel: 'Determinations',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: true,
            isRelationship: true,
            tableName: 'Determination',
          },
          dnaSequences: {
            optionLabel: 'DNA Sequences',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'DNASequence',
          },
          collectingEvent: {
            optionLabel: 'Field No: Locality',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'CollectingEvent',
          },
          collection: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection',
            tableName: 'Collection',
          },
          collectionObjectAttachments: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection Object Attachments',
            tableName: 'CollectionObjectAttachment',
          },
          preparations: {
            optionLabel: 'Preparations',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'Preparation',
          },
          voucherRelationships: {
            optionLabel: 'Voucher Relationships',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'VoucherRelationship',
          },
        },
        tableName: 'CollectionObject',
      },
      {
        defaultValue: '#1',
        customSelectSubtype: 'toMany',
        selectLabel: localized('Determination'),
        fieldsData: {
          '#1': {
            optionLabel: '#1',
            isRelationship: true,
            isDefault: true,
            tableName: 'Determination',
          },
          '#2': {
            optionLabel: 'Add',
            isRelationship: true,
            isDefault: false,
            tableName: 'Determination',
          },
        },
        tableName: 'Determination',
      },
      {
        defaultValue: 'taxon',
        customSelectSubtype: 'simple',
        selectLabel: localized('Determination'),
        fieldsData: {
          determinedDate: {
            optionLabel: 'Date',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          guid: {
            optionLabel: 'GUID',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          typeStatusName: {
            optionLabel: 'Type Status',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          determiner: {
            optionLabel: 'Determiner',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: true,
            tableName: 'Agent',
          },
          taxon: {
            optionLabel: 'Taxon',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: true,
            isRelationship: true,
            tableName: 'Taxon',
          },
        },
        tableName: 'Determination',
      },
      {
        defaultValue: '$Family',
        customSelectSubtype: 'tree',
        selectLabel: localized('Taxon'),
        fieldsData: {
          $Kingdom: {
            optionLabel: 'Kingdom',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Phylum: {
            optionLabel: 'Phylum',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Class: {
            optionLabel: 'Class',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Order: {
            optionLabel: 'Order',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Family: {
            optionLabel: 'Family',
            isRelationship: true,
            isDefault: true,
            tableName: 'Taxon',
          },
          $Subfamily: {
            optionLabel: 'Subfamily',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Genus: {
            optionLabel: 'Genus',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Subgenus: {
            optionLabel: 'Subgenus',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Species: {
            optionLabel: 'Species',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
          $Subspecies: {
            optionLabel: 'Subspecies',
            isRelationship: true,
            isDefault: false,
            tableName: 'Taxon',
          },
        },
        tableName: 'Taxon',
      },
      {
        defaultValue: 'name',
        customSelectSubtype: 'simple',
        selectLabel: localized('Taxon'),
        fieldsData: {
          author: {
            optionLabel: 'Author',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          commonName: {
            optionLabel: 'Common Name',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          guid: {
            optionLabel: 'GUID',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          name: {
            optionLabel: 'Name',
            isEnabled: true,
            isRequired: true,
            isHidden: false,
            isDefault: true,
            isRelationship: false,
          },
          remarks: {
            optionLabel: 'Remarks',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
          source: {
            optionLabel: 'Source',
            isEnabled: true,
            isRequired: false,
            isHidden: false,
            isDefault: false,
            isRelationship: false,
          },
        },
        tableName: 'Taxon',
      },
    ],
  },
  {
    in: [
      {
        baseTableName: 'CollectionObject',
        mappingPath: ['determinations', '#1', 'taxon', '$Family', 'name'],
        showHiddenFields: false,
        generateFieldData: 'all',
        spec: navigatorSpecs.queryBuilder,
      },
    ],
    out: [
      {
        customSelectSubtype: 'simple',
        defaultValue: 'determinations',
        fieldsData: {
          '-formatted': {
            isDefault: false,
            isEnabled: true,
            isRelationship: false,
            optionLabel: '(formatted)',
            tableName: 'CollectionObject',
          },
          accession: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Accession #',
            tableName: 'Accession',
          },
          age: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Age',
            tableName: undefined,
          },
          altCatalogNumber: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Prev/Exch #',
          },
          catalogNumber: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Cat #',
          },
          'catalogedDate-day': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Cat Date (Day)',
          },
          'catalogedDate-fullDate': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Cat Date',
          },
          'catalogedDate-month': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Cat Date (Month)',
          },
          'catalogedDate-year': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Cat Date (Year)',
          },
          cataloger: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Cataloger',
            tableName: 'Agent',
          },
          cojo: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Cojo',
            tableName: 'CollectionObjectGroupJoin',
          },
          collectingEvent: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Field No: Locality',
            tableName: 'CollectingEvent',
          },
          collection: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection',
            tableName: 'Collection',
          },
          collectionObjectAttachments: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection Object Attachments',
            tableName: 'CollectionObjectAttachment',
          },
          collectionObjectAttribute: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Col Obj Attribute',
            tableName: 'CollectionObjectAttribute',
          },
          collectionObjectCitations: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection Object Citations',
            tableName: 'CollectionObjectCitation',
          },
          collectionObjectType: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection Object Type',
            tableName: 'CollectionObjectType',
          },
          determinations: {
            isDefault: true,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Determinations',
            tableName: 'Determination',
          },
          dnaSequences: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'DNA Sequences',
            tableName: 'DNASequence',
          },
          fieldNumber: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Voucher',
          },
          guid: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'GUID',
          },
          leftSideRels: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Left Side Rels',
            tableName: 'CollectionRelationship',
          },
          modifiedByAgent: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Edited By',
            tableName: 'Agent',
          },
          preparations: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Preparations',
            tableName: 'Preparation',
          },
          projectNumber: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Project Number',
          },
          remarks: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Remarks',
          },
          reservedText: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'CT Scan',
          },
          reservedText2: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Reserved Text2',
          },
          rightSideRels: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Right Side Rels',
            tableName: 'CollectionRelationship',
          },
          'timestampModified-day': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date Edited (Day)',
          },
          'timestampModified-fullDate': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date Edited',
          },
          'timestampModified-month': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date Edited (Month)',
          },
          'timestampModified-year': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date Edited (Year)',
          },
          voucherRelationships: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Voucher Relationships',
            tableName: 'VoucherRelationship',
          },
        },
        selectLabel: localized('Collection Object'),
        tableName: 'CollectionObject',
      },
      {
        customSelectSubtype: 'simple',
        defaultValue: 'taxon',
        fieldsData: {
          '-formatted': {
            isDefault: false,
            isEnabled: true,
            isRelationship: false,
            optionLabel: '(aggregated)',
            tableName: 'Determination',
          },
          collectionObject: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Collection Object',
            tableName: 'CollectionObject',
          },
          'determinedDate-day': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date (Day)',
          },
          'determinedDate-fullDate': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date',
          },
          'determinedDate-month': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date (Month)',
          },
          'determinedDate-year': {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Date (Year)',
          },
          determiner: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Determiner',
            tableName: 'Agent',
          },
          determiners: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Determiners',
            tableName: 'Determiner',
          },
          guid: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'GUID',
          },
          isCurrent: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Current',
          },
          preferredTaxon: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Preferred Taxon',
            tableName: 'Taxon',
          },
          taxon: {
            isDefault: true,
            isEnabled: true,
            isHidden: false,
            isRelationship: true,
            isRequired: false,
            optionLabel: 'Taxon',
            tableName: 'Taxon',
          },
          typeStatusName: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Type Status',
          },
        },
        selectLabel: localized('Determination'),
        tableName: 'Determination',
      },
      {
        customSelectSubtype: 'tree',
        defaultValue: '$Family',
        fieldsData: {
          '$-any': {
            isDefault: false,
            isEnabled: true,
            isRelationship: true,
            optionLabel: '(any rank)',
            tableName: 'Taxon',
          },
          $Class: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Class',
            tableName: 'Taxon',
          },
          $Family: {
            isDefault: true,
            isRelationship: true,
            optionLabel: 'Family',
            tableName: 'Taxon',
          },
          $Genus: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Genus',
            tableName: 'Taxon',
          },
          $Kingdom: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Kingdom',
            tableName: 'Taxon',
          },
          $Order: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Order',
            tableName: 'Taxon',
          },
          $Phylum: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Phylum',
            tableName: 'Taxon',
          },
          $Species: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Species',
            tableName: 'Taxon',
          },
          $Subfamily: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Subfamily',
            tableName: 'Taxon',
          },
          $Subgenus: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Subgenus',
            tableName: 'Taxon',
          },
          $Subspecies: {
            isDefault: false,
            isRelationship: true,
            optionLabel: 'Subspecies',
            tableName: 'Taxon',
          },
        },
        selectLabel: localized('Taxon'),
        tableName: 'Taxon',
      },
      {
        customSelectSubtype: 'simple',
        defaultValue: 'name',
        fieldsData: {
          author: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Author',
          },
          fullName: {
            isDefault: false,
            isEnabled: true,
            isHidden: false,
            isRelationship: false,
            isRequired: false,
            optionLabel: 'Full Name',
          },
        },
        selectLabel: localized('Taxon'),
        tableName: 'Taxon',
      },
    ],
  },
]);
