name: Coverage

on: 
  push:
  workflow_dispatch:

jobs:
  check:
    name: Get cpu info
    runs-on: ubuntu-latest
    steps:
      - name: get cpuinfo
        id: cpuinfo
        run: |
          lscpu
      - name: get meminfo
        id: meminfo
        run: free -h
